### ISSUE TITLE
We should be more aggressive about pinning our deps.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#10]
Need to go through turning ^s to ~s in package.json for JS and React SDK to ensure 'minor' package updates don't break the world (like we just had with flux going from 2.1 to 2.2)

**Comment by kyrias** [comment]
If a minor update broke things that would be a bug from flux though, and the same thing could happen with a patch release, so I'm not sure what that would really solve.

**Comment by richvdh** [comment]
I'm with kyrias. I don't think we're going to do this.
