### ISSUE TITLE
First message ever in a room should be preceded by the Date timestamp bar

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1014]
We used to have this but it's got lost, at least for inbound 1:1s

**Comment by richvdh** [comment]
I thought it was. this must be a regression.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/issues/208

**Comment by richvdh** [comment]
It's still missing for rooms with short histories.

**Comment by richvdh** [comment]
Turns out that the issue for rooms with short histories is mostly due to https://matrix.org/jira/browse/SYN-645

**Comment by richvdh** [comment]
Properly fixed by https://github.com/matrix-org/matrix-js-sdk/issues/98
