### ISSUE TITLE
Need changelogs for the 0.2.0 release

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1019]
https://github.com/vector-im/vector-web/blob/master/CHANGES.rst
...and react-sdk doesn't even seem to have a changelog?
https://github.com/matrix-org/matrix-react-sdk/blob/master/CHANGES.rst

I don't suggest comprehensive changelog for vector web & react, other than explaining the magnitude of the update and spelling out that the layering is currently broken.

**Comment by dbkr** [comment]
Done
