### ISSUE TITLE
Clicking on a signup validation link in the wrong browser gives you no way to progress the signup in the browser you started with

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1027]

**Comment by ara4n** [comment]
1. Sign up in one browser
2. Receive validation email
3. Click link in validation email on phone; open mobile browser; pass CAPTCHA
4. No way to progress the signup on the first browser, short of refreshing and starting over as a login.

**Comment by ara4n** [comment]
@dbkr I hit a new problem with this (beyond polling to see if the email has been validated) earlier today: if you are signing up using a non-matrix.org HS, the session that loads in the 'wrong' browser will default to the wrong HS/IS and all hell breaks loose.  I think :/

**Comment by dbkr** [comment]
Ah yep, looks like this was broken in https://github.com/matrix-org/matrix-react-sdk/commit/0bb58dd60c3b23ac178b1767c8553ef7215c39d9
