### ISSUE TITLE
Emoji are very platform dependent currently

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1031]
This may be related to me upgrading the OpenSans WOFF possibly?

**Comment by ara4n** [comment]
![image](https://cloud.githubusercontent.com/assets/1294269/13349081/dedd0f4e-dc77-11e5-9370-065eca1af9e5.png)

**Comment by floviolleau** [comment]
![firefox_2016-02-26_10-59-41](https://cloud.githubusercontent.com/assets/5442973/13349112/1f926660-dc78-11e5-9879-61ee12363f92.png)

**Comment by dbkr** [comment]
No, it's just that Chrome on Windows 7 is using Segoe UI symbol for emoji characters, and I used 'grinning face' which is not in that font. 'smiling face with open mouth' works.

**Comment by ara4n** [comment]
I guess the right solution is to either use a WOFF or images to ensure that emoji are consistent cross-platform.

**Comment by vberger** [comment]
An approach could be to mimic what glowing-bear (a weechat client) is doing: it has a setting switch to enable non-native emoji support, when checked emojis are rendered as images using http://emojione.com/ rather than system fonts.

**Comment by aviraldg** [comment]
For anyone looking to work on this, I already have some WIP code here that uses emojione to swap out unicode emoji and Github style emoji references, but am waiting on a resolution to matrix-org/matrix-doc#92 and matrix-org/matrix-doc#93.

**Comment by ara4n** [comment]
As a first cut, I would strongly suggest just turning utf8 emoji into 
consistent images or font and ignoring github/slack-style textual emoji 
entirely.  This would be a very welcome PR right now.

It doesn't have to be blocked on resolving matrix-org/matrix-doc#92 and 
matrix-org/matrix-doc#93 in terms of deciding how to embed better emoji 
semantics in future.

**Comment by vberger** [comment]
Just forwarding: emojione provides a set of JS scripts that is able to dynamically replace UTF8 emoji sequences by `<img />` html codes. There is an example of this here, that looks quite straightforward:

https://github.com/Ranks/emojione/blob/master/demos/jsunicodetoimage.html#L85-L101

Might be a good direction to look at?

**Comment by aviraldg** [comment]
My (wip) implementation already uses emojione.

**Comment by aviraldg** [comment]
Fixed by https://github.com/aviraldg/matrix-react-sdk/commit/bed0a7c7feabfdc9299faeabeb60d9a1a371d42a
