### ISSUE TITLE
Double invite from a user, left one invite behind and it's broken so can't be removed

### ISSUE THREAD

**Issue by sbts** [vector-im/vector-web#1044]
This invite can't be accepted nor declined, from any client I have tried. 
(vector beta and develop, android console)
![screenshot from 2016-02-28 05 15 32](https://cloud.githubusercontent.com/assets/11002795/13375453/dd477598-ddda-11e5-9fc9-fbb20d4720d0.png)
^^^^ The Invite ^^^^

![screenshot from 2016-02-28 05 16 00](https://cloud.githubusercontent.com/assets/11002795/13375454/dd49e6ac-ddda-11e5-87b8-ee65045daa35.png)
^^^^ Accept / Decline screen ^^^^

![screenshot from 2016-02-28 05 16 25](https://cloud.githubusercontent.com/assets/11002795/13375456/dd515e6e-ddda-11e5-88c7-b8dd9859daa2.png)
^^^^ Accept Error ^^^^

![screenshot from 2016-02-28 05 16 45](https://cloud.githubusercontent.com/assets/11002795/13375455/dd4f7c48-ddda-11e5-8d8a-0cfcfb97f9d4.png)
^^^^ Decline Error ^^^^

**Comment by ara4n** [comment]
This is https://matrix.org/jira/browse/SYN-642

**Comment by sbts** [comment]
ara4n,
This bug nolonger causes a problem to end users due to the fixes done in SYN-642 and friends.
Although there are still issues to be dealt with related to correctly handling it at a federation level.

Can we close the bug?

**Comment by richvdh** [comment]
Yes, this is fixed. Thanks
