### ISSUE TITLE
Lots of 'event already in timeline' warnings

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1045]
My JS console is filling up with warnings like:

`room.js:491 Event $1456621160155193ZZdAy:matrix.org already in timeline [object Object]`

Seems to happen particularly when i have RoomSettings open in a small window that such that the settings hide the view of the timeline itself.

**Comment by ara4n** [comment]
This also seems to happen whenever we get a spinner stuck at the top or bottom of the page for whatever reason - particularly common that new rooms with little scrollback get a spinner stuck at the top.

**Comment by richvdh** [comment]
they aren't warnings; if anything, they are debug.

If we're making the same pagination requests over and over, that's a separate problem.

**Comment by ara4n** [comment]
right - the thing i was worried about here is the fact that they tightloop chewing 100% CPU.  Seems to happen on RoomViews with limited height.

**Comment by richvdh** [comment]
@ara4n: I was unclear on the repro conditions for this, but hopefully it's been fixed by https://github.com/matrix-org/matrix-js-sdk/issues/91. Could you see if it still happens?

**Comment by ara4n** [comment]
haven't seen it so much since, and can't repro now - the most i've seen are a 3 or 4 in a row every now and then.
