### ISSUE TITLE
Something leaks '/undefined' into URLs when acting as a guest

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1079]
I just started a fresh incognito tab against my local develop vector.  This put me as a guest in RoomDirectory view, but something rewrote the location bar as http://localhost:8080/#/room/undefined. I then hit refresh, which took me to a 'Join' page, presumably trying to join a room with room id of "undefined".  This also breaks URL-keyed page stats :(

**Comment by mebjas** [comment]
What is the expected behavior here?
@ara4n

**Comment by ara4n** [comment]
The app should take you to RoomDirectory view on initial launch, but the URL should either be something explicit (like /directory) and certainly not /#/room/undefined.

**Comment by mebjas** [comment]
@ara4n Now shows `/directory`

**Comment by mebjas** [comment]
@ara4n now shows `/directory`

**Comment by ara4n** [comment]
I'm still seeing this happen - e.g. loading http://localhost:8080/#/login leaves me sitting at http://localhost:8080/#/room/undefined

**Comment by mebjas** [comment]
Lemme check

**Comment by mebjas** [comment]
@ara4n This is strange, loading `http://localhost:8080/#/login` took me to `http://localhost:8080/#/directory`

More pointers on steps to reproduce?

**Comment by ara4n** [comment]
fixed - thanks @mebjas :)
