### ISSUE TITLE
Email notifications - either digest or realtime to tell you when you've missed a bing/invite/etc.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#108]

**Comment by ara4n** [comment]
This is higher priority than P3 - see also SYN-169.  It's a really important way to keep people engaged with Vector.

**Comment by ara4n** [comment]
I won't make it block v0 though.

**Comment by AmandineLP** [comment]
Proposed specs, can be discussed and completed:

![image](https://cloud.githubusercontent.com/assets/8582858/12487651/5a319a9c-c068-11e5-9451-fddc0b3a9209.png)

**Comment by Kegsay** [comment]
> I won't make it block v0 though.

Removed from v0

**Comment by ara4n** [comment]
Notes from discussing this with Amandine this morning:
 * If the user has been idle for at least 2 minutes, we send an email notif.
 * We batch email notifs together, exponentially backing off *per conversation*.
 * If there is a significant pause in a conversation (say 4x the current retry timer?), we reset its exponential backoff timer.
 * New conversations start a new retry schedule... but we batch all pending notifs into a single email, effectively preempting a retry for older conversations.  This doesn't reset the retry timer for those older conversations.

I wonder if this means we need the daily digest ones?  Perhaps they can be implemented as an entirely separate mechanism.  I find them quite annoying, and would probably prefer that we only spam people with updates when something new has actually happened (and these can contain the same overview stats as a digest would...)

**Comment by AmandineLP** [comment]
Don't forget invites in the above. I guess it can be just a single email everytime someone invites you, even if he used your mxid, and if don't join in the next 4 (?) minutes. (see table)

I wouldn't want to have metrics like who joined rooms and how many unread msg there are in the notifs  emails sent for highlight/sound or invites, but once a day it would be interesting. So I'm still quite keen on keeping the daily digest if something new happen only and which would include: 
* # unread messages in favourite rooms
* List of people who joined my favourite rooms
* List of pending invites

However I understand the spam concern, so an option would be to deploy first the notifications and see how spammy it feels and then add the digest on a second step

**Comment by ara4n** [comment]
(We've agreed that for now invites & messages should have the same idle timer before email notifs kick in - 2 mins for now)

**Comment by ara4n** [comment]
One refinement that came up when discussing with dave & erik just now: rather than sending if the user has been idle for 2 minutes, we should probably wait for 2 minutes (or whatever the retry timer is) of inactivity after seeing the event before sending the email.  If the user wakes up and uses the app, we should discard any pending email notifs and probably reset the timer schedule.  This stops us from spamming the user if they're actually responding to push notifs elsewhere.

**Comment by ara4n** [comment]
There are now designs for this in basecamp.

**Comment by eternaleye** [comment]
I'd really prefer separating this from hilight/sound notifications - as a case in point, I use Vector on the bus over cellular + tethering. However, there are various dead spots, some of which last for 5min or so.

The instant I exit the dead spot, I'm alerted by my phone, due to exactly hilight/sound notifications - but in the mean time, Vector may have sent me emails that are really just so much spam.

**Comment by ara4n** [comment]
(see also https://matrix.org/jira/browse/SYN-169)

**Comment by dbkr** [comment]
Have tried to summarise requirements on https://docs.google.com/document/d/1ZNxBMb9zoJNRZ12T-3_OCMgrcb3KhppTDaXtls1uDYs/edit

**Comment by ara4n** [comment]
this is pretty much live now.
