### ISSUE TITLE
if a 1:1 public room exists, starting again a 1:1 chat from RHS panel should start a new private 1:1 one

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1090]
I'm in 1:1 public chat
Starting a new chat with the same person from LHS "Start chat" opens a new private room.
Starting new chat with the same person from RHS "Start chat" (from the member list) opens the existing public 1:1.

I think the LHS button behaviour is the right one and should be implemented for the RHS button

**Comment by ara4n** [comment]
dup #473
