### ISSUE TITLE
Some guest joining events disappear

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1096]
Different views of the same room at the same time:
From a Guest 2323:
![image](https://cloud.githubusercontent.com/assets/8582858/13529793/42d99cd2-e21e-11e5-9887-15c11c713d67.png)

From Guest 2273 (who is a registered user):
![image](https://cloud.githubusercontent.com/assets/8582858/13529802/5838e01a-e21e-11e5-88d9-fa49daef2374.png)

The guest user is missing everything which happened today despite the history being visible since the room began to members

**Comment by AmandineLP** [comment]
This might be linked to: #768 combined with the fact that history made visible at some point is still available.
If the history was made visible at some point, the guest user would be able to access it (hence seeing partial bits of the conversation), plus the strange events lost in the middle from #768...

**Comment by erikjohnston** [comment]
That room seems to have a lot of changes to the history visibility settings, which is probably causing confusion. Hopefully when vector starts displaying visibility changes it will be clearer whats going on.

Also, in future could you give the room id in bug reports (if testing against matrix.org) please? As it makes it easier to track down what's going on server side :)

**Comment by ara4n** [comment]
@AmandineLP - please can you try this again now that we have explicit history visibility updates in the timeline, which should make it clearer as to what the history ACLs are doing?

**Comment by AmandineLP** [comment]
This is still utterly confusing. We need retroactive ACLs as per #1170 .
In teh meantime I need to define a better UX like huge warning messages when changing the history visibility so that the user doesn't get confused.

**Comment by AmandineLP** [comment]
replaced by #1214
