### ISSUE TITLE
Show history visibility changes in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1103]
Currently there are ambiguous blanks in the timeline when history visibility is changed such that the current user can't see those messages.  We should instead explicitly say "Room history has been restricted to joined users only" and conversely "Room history is now visible to all users" etc. in the timeline.

@erikjohnston This means that ACLs have to show us history visibility events when our visibility transitions on and off. I thought there was something that did this, but also vaguely remember someone removing it.  Does it work?

If it does, we'll just need to show them in the timeline in vector correctly.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/626

**Comment by erikjohnston** [comment]
The above PR is now merged into synapse develop.

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk@0e1186c
