### ISSUE TITLE
Some video files play at extremely large sizes

### ISSUE THREAD

**Issue by abrahimladha** [vector-im/vector-web#1112]
![2016-03-05-160657_1288x993_scrot](https://cloud.githubusercontent.com/assets/6496702/13550479/a727aaac-e2ec-11e5-8e33-cd9679d47887.png)
it seems for some type of gifs or mp4, it will display at a very large size. notice the horizontal scrollbar. 
Here is the file in question: https://mega.nz/#!kINC0BKb!NXXzvmqE8L2Mo2_LbDAwdIjNtgCztpV5zcV_n3jj3k8

**Comment by ara4n** [comment]
random! thanks - will check.

**Comment by ara4n** [comment]
@abrahimladha what client was the movie sent from? the bug is in whatever client sent it misdescribing the height - and that wasn't vector web.  I'm guessing Matrix Console Android, but want to check...

**Comment by abrahimladha** [comment]
I tested it from a few clients. It seems the issue is with as you said, Matrix Console Android. I also tested it on an alpha of Vector Android and they contain the same bug.

**Comment by dbkr** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/355
