### ISSUE TITLE
Notification settings order

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#1117]
Personally I find it confusing that the order of the notification settings is "On, Loud, Off":

![screenshot from 2016-03-08 11 43 39](https://cloud.githubusercontent.com/assets/8428120/13600772/078ccd36-e523-11e5-9c29-bb8a836bdf41.png)

Instinctively it feels like the notification setting between "On" and "Off" should be a lesser setting than "On", e.g. increase unread count but don't pop up desktop notification. However, the middle settings is "Loud" which means notify more strenuously than the "On" setting.

I think it would be more intuitive to have "Loud" to the left of "On", to indicate it some sort of increased setting.

**Comment by ara4n** [comment]
agreed

**Comment by ara4n** [comment]
@AmandineLP - i reckon that off, on, loud  (starting quietest to loudest) would be best; does that wfy?

**Comment by AmandineLP** [comment]
My brain doesn't like it at all, but apparently I'm not wired like others as I had the same feedback as Erik from others, and it does make sense. So yeah ok let's do it this way even if it makes me confused.

**Comment by ara4n** [comment]
done.
