### ISSUE TITLE
Poor UX when cancelling join-as-guest

### ISSUE THREAD

**Issue by dandv** [vector-im/vector-web#1121]
1. Go to the Matrix HQ room, https://vector.im/beta/#/room/!cURbafjkfsMDVwdRDQ:matrix.org
2. Click "join" in "Would you like to join this room"
3. Change your mind and attempt to close the dialog. There is no close button:
![image](https://cloud.githubusercontent.com/assets/33569/13652750/c7b4a220-e602-11e5-94be-1c193f3cb974.png)
4. Click outside the dialog.
5. The room appears stuck, with a spinner at the top:
![image](https://cloud.githubusercontent.com/assets/33569/13652791/0f45df78-e603-11e5-8974-a19316a7bf75.png)
6. Click "Start chat". A "Failed to create room" (which already exists) popup is displayed.
![image](https://cloud.githubusercontent.com/assets/33569/13652817/404515a8-e603-11e5-8972-76903331eeb7.png)

**Comment by ara4n** [comment]
This overlaps significantly with #934

**Comment by ara4n** [comment]
@dandv thanks for the great bug report btw :)
