### ISSUE TITLE
eventTriggersUnreadCount method is confused about m.notice's

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1127]
It contains:

```
        } else if (ev.getType == 'm.room.message' && ev.getContent().msgtype == 'm.notify') {
            return false;
        }
```

`m.notify` is not a known msg type though; it should be `m.notice`.  And even then we probably shouldn't ignore notices for unread counts.  I suspect the right soln is to delete this clause entirely?

**Comment by fuzzy76** [comment]
Could this be the reason I keep seeing IRC channels being marked as unread, with no new messages in the channel buffer?
