### ISSUE TITLE
HTML5 video elements should not have autoplay on by default

### ISSUE THREAD

**Issue by abrahimladha** [vector-im/vector-web#1144]
I join a room and the past 10-15 videos people post start playing all at the same time and blow up my speakers. Looking at the HTML is says <video .... autoplay="" ....></video> which may be the issue. I searched "autoplay" in this repo and no results came up so it might be a something thats defaulted.

**Comment by ara4n** [comment]
this was fixed on friday(?) on develop - can you repro on https://vector.im/develop?

**Comment by abrahimladha** [comment]
I tested it on vector.im/develop and it has indeed been fixed. Thank you.
