### ISSUE TITLE
Invite based on 3PIDs

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#115]

**Comment by Kegsay** [comment]
When the full server-side implementation lands, this should be pretty trivial to add the endpoint. The UI/switching based on 3PID/user ID may be more interesting.

**Comment by Kegsay** [comment]
From IRL:
 - Put it in the same box as inviting by user ID.
 - Don't send a `display_name`, let the HS mask the email addy instead.
 - Clients need to be able to check "for a given string, is this an email address" to hit the right endpoint.

**Comment by Kegsay** [comment]
Can invite by email now (needs HS updating). The UI for inviting users should be filed as a separate bug.
