### ISSUE TITLE
Hide status area when there is no status to be displayed

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/vector-web#1153]
While the status bar comes in handy for jumping to the bottom of scrollback and for showing typing status, I feel like it looks too unnatural and wastes too much space when there's nothing to display there. (This is even more pronounced in vector-android.) I think it would look better if the status area were hidden if nothing needed to be displayed there, much like the "unread messages" bar that appears at the top:

![screen shot 2016-03-14 at 7 13 25 pm](https://cloud.githubusercontent.com/assets/1923178/13762962/f8843a54-ea18-11e5-8bdb-04a0526eeb4d.png)

**Comment by ara4n** [comment]
The problem is that when it appears it'd push the whole scrollback upwards, which could get rather annoying and bouncy if someone was typing on/off etc.  I agree it's a bit redundant when empty though, especially on mobile. We'll have a think.

**Comment by jfrederickson** [comment]
Agreed, scrolling semantics are tricky with that. Might help if you only scroll the chat window if you're scrolled all the way to the bottom, else put the status bar in place without scrolling. It's similar to what other messengers do: Facebook Messenger and Hangouts for example put the typing notification in a chat bubble, which does cause the chat to bounce up and down if they stop and start typing.

Somewhat related, maybe it would be useful to have separate event types for "typing" and "has something typed, but has stopped typing" - XMPP has this for example, and it allows clients to have e.g. an animated typing icon when the other party is typing, and a static one when not. (Which avoids typing indicators bouncing off and on.)

**Comment by aviraldg** [comment]
One possible way to fix this without causing jumpiness is to keep its position fixed at the bottom, and hide it when not needed (instead of making it a part of the message list itself.) When it appears, it appears *above* existing messages, which works out fine since it shows up when you scroll up.

**Comment by ara4n** [comment]
dup #1991
