### ISSUE TITLE
MessageComposer's <textarea/> can get an explicit height of 0px under some unknown circumstances

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1172]
Erik saw this this morning; I saw it just now:

<img width="1912" alt="screen shot 2016-03-16 at 13 19 50" src="https://cloud.githubusercontent.com/assets/1294269/13813970/4bedf1bc-eb7c-11e5-9612-d75f3c447181.png">

**Comment by aviraldg** [comment]
Interesting. In #1155, it had an explicit height of 20px, but a computed height of 5px (hence the scrollbars.)

**Comment by ara4n** [comment]
hopefully workedaround by https://github.com/matrix-org/matrix-react-sdk/commit/3326a50c4b8257f4a73b806d00652ef23b979458
