### ISSUE TITLE
History visibility confirmations

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1214]
When changing the history visibility radio button we should issue a confirmation dialogbox to warn that it doesn't take effect retroactively and ask for confirmation.  I suggest we do this as soon as they hit the radiobutton.

@AmandineLP are you okay with that approach in the end?

**Comment by ara4n** [comment]
i went and did this anyway; landed in 68a391e24bb6447e127f9a1e81123ca6b5ba8a71

**Comment by AmandineLP** [comment]
As discussed: yes.
/me waits for the fix to land to check what you did and parks the UX she was defining.
