### ISSUE TITLE
Initial /sync seems to have got a lot slower since 0.14-rc1

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1234]
I don't think vector's doing anything different, but synapse seems to take much longer to generate the initial /sync response for the same account.  Possibly because we send kicked room state or push rules(?!) now?

**Comment by erikjohnston** [comment]
What timeline limit are we using ooi?

**Comment by erikjohnston** [comment]
Analysing the logs have shown no obvious regression.

@matthew Do we want to try making it faster or leave it as is?

**Comment by ara4n** [comment]
we're going to have to dig some more - the slowdown is still there and very noticeable, e.g.:

```
<dcg_mx>
Matthew: the speed of initial sync on opening a vector web tab seems to be getting slower.
I just turned my laptop on and opened firefox (linux mint) the only page open is vector. it took over 60 seconds sitting with the spinning wheel of lost time before the UI was displayed
```

**Comment by ara4n** [comment]
(i'm assuming this is serverside rather than clientside woes)

**Comment by ara4n** [comment]
erik sped this up a bit by re-parallelising /sync. i think it's gone roughly back to being as bad as it was before.
