### ISSUE TITLE
Infinite vector.im loading time

### ISSUE THREAD

**Issue by xdevelnet** [vector-im/vector-web#1248]
Browser: Firefox 38.0
OS: Linux mint 17.2

For some reason everything works great...
1) with Chromium
2) around 1-2 month ago

**Comment by ara4n** [comment]
Can you try again on https://vector.im/staging please?  If it still fails, please can you share the contents of your javascript console?

**Comment by xdevelnet** [comment]
Yea, works well enough.
but it takes around 6 seconds to load... is it ok?

Thank you :)

**Comment by ara4n** [comment]
yup, initial loading is known slow - we currently don't lazyload stuff but preemptive load quite a lot of data when you log in. We're improving that tho :)
