### ISSUE TITLE
Recaptcha is having problems on the demo server

### ISSUE THREAD

**Issue by hairychris** [vector-im/vector-web#1260]
When you try and register you will receive an email confirmation, clicking this will end up with this error message. I tried just 1 minute ago. 
<img width="454" alt="screenshot 2016-03-23 19 48 46" src="https://cloud.githubusercontent.com/assets/6599597/13998763/c25373ae-f130-11e5-8c5d-31f9da3ed4a8.png">

**Comment by ara4n** [comment]
Hi Chris,

thanks for this - precisely what URL did the screencap come from?

We're trying to repro it.

M

**Comment by hairychris** [comment]
Hey,

The link that is sent via email after registration, in my case it was:

https://vector.im/_matrix/identity/api/v1/validate/email/submitToken?token=693860&client_secret=<redacted>&sid=3066&nextLink=http%3A//chat.ipfs.io/%23/register%3Fclient_secret%<redacted>%26hs_url%3Dhttps%253A%252F%252Fmatrix.org%26is_url%3Dhttps%253A%252F%252Fvector.im%26session_id%3<redacted>%26sid%3D3066

If it is safe for me to post a link without the <redacted> bits I am happy to do so. This will then redirect to http://chat.ipfs.io/#/register

Thanks for picking up on this so fast.

**Comment by ara4n** [comment]
Right - so the url that contains the failed captcha is http://chat.ipfs.io/#/register ?

We don't run that URL - @davidar, do you know if the captcha is configured correctly on it?

Chris: a workaround is to register an account on vector.im itself but then login via chat.ipfs.io. NB that the chat.ipfs.io server is at least a few weeks stale and Vector has been under *very* heavy dev recently - the latest app can be found at vector.im (or vector.im/develop if you want up-to-the-minute bleeding edge :)

**Comment by hairychris** [comment]
That’s correct, thanks for the work around :)
