### ISSUE TITLE
Mark all as read button for room

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1289]
Currently to mark all messages in a room as read you have to click on the unread (^) button and then the (v) button and pray. I wonder if there should be a better way of doing this.

**Comment by richvdh** [comment]
Isn't this the (x) button in the "(^) unread" bar?

**Comment by ara4n** [comment]
hm, i guess it is.

**Comment by ara4n** [comment]
(this was clearly a premonition of https://github.com/vector-im/riot-web/issues/8666/)
