### ISSUE TITLE
Changing history setting not possible

### ISSUE THREAD

**Issue by simsasaile** [vector-im/vector-web#1291]
Hi,

if you try to change the "Who can read history?"-setting a warning is displayed: `"Privacy Warning: Changes to who can read history will only apply to future messages in this room.
The visibility of existing history will be unchanged."` with two options "Continue" and "Cancel". 

Unfortunately it's not possible to click on "Continue" so it's not possible to change this setting at all.

Beside this I like vector a lot, thank you for the good work.

**Comment by ara4n** [comment]
yup - sorry about this; it's fixed on vector.im/develop and will 
probably be deployed tomorrow.

**Comment by ara4n** [comment]
dup #1283
