### ISSUE TITLE
User can't leave the room

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1305]
I got into an edge case where user @4879:matrix.org (password: guest4879) can't leave the room !pbcGtpadvziFRIdrIv:matrix.org (testing fun).
He was a guest, made mod to see if he could invite people (as invite is limited to mods). Made back a user. Tried inviting others again. Registered (without email). Tried inviting people (3PID) and it worked. Then wanted to leave, got the confirmation pop-up. Then ran into #1304  so sent a message to try to raise the 'Please join' message but the message never appeared, only sent messages were unsent with appropriate error message. Tried to leave several times and got the confirmation popup but never left. Join another room to see if the unique room was the issue, and then when waanting to leave focus was moved to the other room but the left room was not left and still in "Rooms" rather than historical, with inability to send msg.
I might have changed the visibility from "World readable and accessible to guests" to "invite-only" at some point

I'm not going to change the room settings from now on so that you can investigate.

**Comment by richvdh** [comment]
Looking at this now, the user *did* leave, around the same time as Amandine filed this bug, so I think this was probably an instance of https://github.com/vector-im/vector-web/issues/368.
