### ISSUE TITLE
Vector gets confused by setting keyword notifs to 'loud'

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-web#1330]
If I try to make 'Messages containing keywords' 'loud', I get:
> There are advanced notifications which are not shown here. You might have configured them in another client than Vector. 
> You cannot tune them in Vector but they still apply.
> Notifications on the following keywords follow rules which can’t be displayed here: vdh

**Comment by ara4n** [comment]
@NegativeMjark is this an artefact of your recent push work?

**Comment by NegativeMjark** [comment]
In so far as I was the last one to touch the code maybe? (without any tests it's hard to tell if my changes made it any more broken that it was already)

**Comment by richvdh** [comment]
Fixed by https://github.com/vector-im/vector-web/commit/121fe3418010a441da4a8a7f45625a654194bf7
