### ISSUE TITLE
Conferences are hard coded to matrix.org

### ISSUE THREAD

**Issue by almereyda** [vector-im/vector-web#1338]
The ConferenceHandler currently only connects directly to the `matrix.org` AS (abbrev., glossary?) as specified in

https://github.com/vector-im/vector-web/blob/04b51f6f0fdc95e768921e8f9a7aa10593f16d59/src/VectorConferenceHandler.js#L24-L29

Fixing this will supposedly add a configuration variable to

https://github.com/vector-im/vector-web/blob/61f951a33e882864e47e56f35ab5968ea16f32eb/config.json

**Comment by ara4n** [comment]
Unfortunately this is a bit more than just a config option - we need to spec how to define the focal AS for a room otherwise the room may go splitbrained. Conf isn't remotely finished yet, but of course we'll solve this before it hits the spec :)

**Comment by richvdh** [comment]
dup of #503
