### ISSUE TITLE
Gaps and missing entries in read receipts row.

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#1345]
I've noticed two different, but probably related bugs:

1. When expanding to show all read receipts sometimes there's an empty gap between two of the avatars. Inspecting show that there is a valid avatar there, but has visibility set to hidden.

1. The message edit menu consistently did not appear for a particular message (which had a few read receipts), but did for all other messages.

**Comment by richvdh** [comment]
I've also seen cases where we put the generated avatar letters over people's faces. There is something pretty messed up with the read-receipts.

**Comment by ara4n** [comment]
rich's point is #1156

**Comment by richvdh** [comment]
I think this got fixed by https://github.com/matrix-org/matrix-react-sdk/pull/282.
