### ISSUE TITLE
When restoring tabs in firefox, vector gets stuck replaying old history

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1354]
Apparently vector's state is restored from the point of suspension and then replays forwards rather than jumping forwards via a gappy sync. Notifications fire too. Reported by @eternaleye and @aviraldg

**Comment by ara4n** [comment]
(meanwhile I just saw Thea's Chrome spawn a fleet of push notifications during catchup after unsleeping on /beta, which may or may not be related...)

**Comment by ara4n** [comment]
Yet more evidence of broken notifs: https://vector.im/develop/#/room/#freenode_#matrix:matrix.org/$14605455921524zIpus:half-shot.uk

**Comment by ara4n** [comment]
assigning to rich as it really sounds like something is going wrong with the timeline if we're replaying forwards rather than gappy-syncing

**Comment by richvdh** [comment]
I'm baffled by this. As far as I understand it, firefox session restore doesn't preserve anything that is in regular memory in javascript, and we don't (currently) use localstorage to save events or a sync token - so I don't know where the old events are coming from.

**Comment by richvdh** [comment]
With a bit of luck this might have been fixed by https://github.com/matrix-org/matrix-js-sdk/commit/0282021e090b6f97203eb316b856d21947d7c991
