### ISSUE TITLE
Inability to upload file for guests should be better explained

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1442]
Today: Guest tries to upload a file, he sees the progress bar and then "The file 'Penguins.jpg' failed to upload."

Guest should get the usual warning message when clicking on the file upload button ("This action cannot be performed by a guest user. Please register to be able to do this. [Register] [Cancel]" or similar)

**Comment by ara4n** [comment]
done in matrix-org/matrix-react-sdk@c3fc76c
