### ISSUE TITLE
User doing a 3PID invite gets a permission error while invite permission is set to user

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#1468]
Reproed in !veOTKzQPvsnxUVchpR:matrix.org. Potential link to #1208 
Amandine invited by Matthew tried to invite and email and got a "Forbidden" error. (Then invited a registered Matthew user which worked)

> bundle.js:82 Invite amxxxx@gmail.com to !veOTKzQPvsnxUVchpR:matrix.org - isEmail=true
> 2016-04-29 11:37:07.415 https://matrix.org/_matrix/client/r0/rooms/!veOTKzQPvsnxUVchpR%3Amatrix.org…NTE_____HR4hHHxvnEp-Cg Failed to load resource: the server responded with a status of 403 (Forbidden)
> 2016-04-29 11:37:07.418 bundle.js:82 Failed to invite: {"errcode":"M_FORBIDDEN","name":"M_FORBIDDEN","message":"You don't have permission to post that to the room. user_level (0) < send_level (50)","data":{"errcode":"M_FORBIDDEN","error":"You don't have permission to post that to the room. user_level (0) < send_level (50)"},"httpStatus":403}(anonymous function) @ bundle.js:82
> 2016-04-29 11:37:31.474 bundle.js:82 Invite @ matthew2:matrix.org to !veOTKzQPvsnxUVchpR:matrix.org - isEmail=false
> 2016-04-29 11:37:32.745 bundle.js:82 Invited @ matthew2:matrix.org

But the email was received anyway.Email is not linked to any account.
Accepting the invite in a incognito window (logged in as a guest) raises an internal server error.

> RoomView.js:155Attempting to peek into room !veOTKzQPvsnxUVchpR:matrix.org
> 2016-04-29 14:55:08.086 MatrixChat.js:665MatrixClient sync state => SYNCING
> 2016-04-29 14:55:08.093 https://matrix.org/_matrix/client/r0/rooms/!veOTKzQPvsnxUVchpR%3Amatrix.org…QgPSB0cnVlCjA____________d8yCBMRfAK Failed to load resource: the server responded with a status of 403 (Forbidden)
> 2016-04-29 14:55:29.442 https://matrix.org/_matrix/client/r0/join/!veOTKzQPvsnxUVchpR%3Amatrix.org?…QgPSB0cnVlCjA______________d8yCBMRfAK Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> RoomView.js:155Attempting to peek into room !veOTKzQPvsnxUVchpR:matrix.org
> 2016-04-29 14:55:08.086 MatrixChat.js:665MatrixClient sync state => SYNCING
> 2016-04-29 14:55:08.093 https://matrix.org/_matrix/client/r0/rooms/!veOTKzQPvsnxUVchpR%3Amatrix.org…QgPSB0cnVlCjA______________d8yCBMRfAK Failed to load resource: the server responded with a status of 403 (Forbidden)
> 2016-04-29 14:55:29.442 https://matrix.org/_matrix/client/r0/join/!veOTKzQPvsnxUVchpR%3Amatrix.org?…QgPSB0cnVlCjA______________d8yCBMRfAK Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by ara4n** [comment]
So the network logs for this show an `/invite` with params:

`{id_server: "vector.im", medium: "email", address: "test11@arasphere.net"}`

This returns:

`{"errcode":"M_FORBIDDEN","error":"You don't have permission to post that to the room. user_level (0) < send_level (50)"}`

but the email gets sent anyway.

My guess there are two bugs - the room doesn't give me permission to create third party invite events by default, but it's sent the email by the time it realises.

**Comment by ara4n** [comment]
looking at `_make_and_store_3pid_invite`, seems like the right fix is to check permissions before talking to the ID server... and special-case the 3rd party invite event type as per https://github.com/vector-im/vector-web/issues/1208. In fact, this is a dup.
