### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by dkelnar** [vector-im/vector-web#149]
Using Vector web app on MacBook Pro running Chrome. Tried to upload Balsamiq file. Upload appears to occur (progress through to completion of data transfer shown). But then no file listed in chat stream. Tried twice further, same result. Other files uploading fine earlier in same chat stream.

**Comment by dkelnar** [comment]
Occurred again 7th September 2015. Same setup except this time tried to upload Word file and then PDF. No success with either.

**Comment by dbkr** [comment]
Fixed by 682880d in matrix-js-sdk.
