### ISSUE TITLE
Email notification configuration

### ISSUE THREAD

**Issue by almereyda** [vector-im/vector-web#1558]
The latest issues suggest there is now an email notification system available for Vector.
It is only to guess that this could be related to the `sydent` somehow magically connected to this client application.

It would be interesting to find a note in `docs/` about how this is configured.

**Comment by almereyda** [comment]
Pardon the early issue, but #1547 and #1556 are apparently related to a development branch called `email_notifs` https://github.com/vector-im/vector-web/compare/dbkr/email_notifs

May a decent tag help out here, called `develop` and in lightgrey?

**Comment by ara4n** [comment]
Email notifs aren't released yet; they're still in dev.  They're nothing 
to do with sydent; they're simply the homeserver sending notifications 
when needed.  Don't worry - they'll be clearly documented once relesed 
from /develop :)

On 29/05/2016 01:49, jon r wrote:
> Pardon the early issue, but #1547
> <https://github.com/vector-im/vector-web/issues/1547> and #1556
> <https://github.com/vector-im/vector-web/issues/1556> are apparently
> related to a development branch called |email_notifs|
> https://github.com/vector-im/vector-web/compare/dbkr/email_notifs
>
> May a decent tag help out here, called |develop| and in lightgrey?
>
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/1558#issuecomment-222336531>,
>
>
or mute the thread
> <https://github.com/notifications/unsubscribe/ABO_vdXS4Dt7Y1NTkifjtuNG7m5SU0WOks5qGOKogaJpZM4IpL8E>.
>

**Comment by ara4n** [comment]
they have now been released, and hopefully the new config file gives sufficient information on how to configure them?

**Comment by almereyda** [comment]
Unfortunately not, as https://github.com/vector-im/vector-web/blob/master/config.json contains well the new keys `brand`, `integrations_ui_url` and `integrations_rest_url`, but from reading this file and https://github.com/vector-im/vector-web#configuring alone, or even after checking https://github.com/matrix-org/, too, it is not completely obvious what such an **integrations** service looks like and where it derives from.
