### ISSUE TITLE
Flashblock Firefox addon disallows video tag?

### ISSUE THREAD

**Issue by rubo77** [vector-im/vector-web#1571]
How can I allow flashblock content for vector?

I already added the domain, where I host vector, to the allow-list, but still flashblock blocks this part:

    <div class="mx_VideoView_remoteVideoFeed"><video style="display: none; max-height: 50px;"></video><audio></audio></div>

**Comment by ara4n** [comment]
Apparently flashblock blocks 'autoplaying html5 video'.  I have no idea what heuristic it uses for this, but I suspect the problem is that we do needlessly display this blank `<video/>` tag even when not in a call.

As such, the right solution is probably to fix #20 at last.

**Comment by ara4n** [comment]
I'm going to close this, as I have no idea how to drive flashblock, and #20 won't help us much given presumably you want webrtc video tags to work correctly anyway when you are on a call.
