### ISSUE TITLE
Adding moderator dropped own priveleges

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#1593]
There have been reports that trying to add another user as a moderator downgrades your own power level.

From DB, we see a change in power levels of:

```
"users":{"@Bankaiii:matrix.org":100}
"users":{"@Bankaiii:matrix.org":50}
```

Note that the sender was `@Bankaiii:matrix.org`

https://vector.im/develop/#/room/#freenode_#matrix:matrix.org/$146498205126460fDRqh:matrix.org

**Comment by bankaiii** [comment]
When you try to set an user with moderator level then the system drop my admin level to moderator level.
It happened with Vector.im/beta

**Comment by dbkr** [comment]
I've attempted to reproduce this issue both both vector.im/beta and latest develop using the following steps:

1) Create a new room
2) Invite another person
3) Have the invitee join the room
4) As the room creator, click on the invitee in the members list
5) Click, 'Make moderator' in the members list.

For me, the invitee correctly becomes a moderator. The power level of the room creator is not affected.

I've also tried inviting multiple people before making one of them a moderator, and also making them a moderator before they join. The app behaved as expected in these scenarios.

I'm closing this bug for now, but if you're able to reproduce this, please re-open it with as much detail as possible about how you reproduced the bug.
