### ISSUE TITLE
URL Preview should preview message if it's a permalink

### ISSUE THREAD

**Issue by sbts** [vector-im/vector-web#1622]
a permalink such as
https://vector.im/develop/#/room/!cURbafjkfsMDVwdRDQ:matrix.org/$1465638441263223qOhds:matrix.org
Should show the message in the preview
>Matthew (@matthew:matrix.org): I just looked at Packages and sort-of expected to find apk's for stable and dev vector android along with the vector web tarballs

At the moment you simply get ivar returning
> [1] Vector

**Comment by ara4n** [comment]
basically a dup of #1519
