### ISSUE TITLE
recaptcha broken when on custom server

### ISSUE THREAD

**Issue by sokoow** [vector-im/vector-web#1628]
re-captcha is showing me this error when running on custom server:

ERROR for site owner:
Invalid domain for site key

**Comment by ara4n** [comment]
When running on a custom synapse with its own recaptcha, you'll need to 
make sure the recaptcha is configured correctly as per:

https://github.com/matrix-org/synapse/blob/master/docs/CAPTCHA_SETUP

It should then work okay with clients like Vector.

**Comment by sokoow** [comment]
can you make sure this link is a part of setup instructions please?

**Comment by ara4n** [comment]
It is there in synapse's README.rst:

 > By default, registration of new users is disabled. You can either enable
registration in the config by specifying `enable_registration: true`
(it is then recommended to also set up CAPTCHA - see docs/CAPTCHA_SETUP), or
you can use the command line to register new users

...however agreed that it's a bit hidden.  Have added it into the 
default config too:

https://github.com/matrix-org/synapse/commit/33546b58aa0a235d159269b8705a8999d219f41a
