### ISSUE TITLE
audible notification for "messages sent by bot" received even in muted rooms

### ISSUE THREAD

**Issue by dovf** [vector-im/vector-web#1653]
When "Messages sent by bot" is set to "Highlight & sound", I'm receiving an audible notification for bot messages even in muted rooms.

**Comment by ara4n** [comment]
this is as expected. muting doesn't affect highlights.  we're working on improving the granularity here.

**Comment by dovf** [comment]
Hmmm... the distinction between "highlights" and "notifications" (what is it that muting *does* affect?) is not very clear...

The UI presents a single list of options, some of which ("Messages containing my name", "Messages sent by bot") appear to be unaffected my muting, whereas other options in the same list ("Messages in one-to-one chats", "Messages in group chats") *are* affected by it.

At the very least there's a UI issue here, I think the issue should be reopened until that's addressed (or a new issue for that created -- or if it already exists, please reference it here...).

Thanks!
