### ISSUE TITLE
JS error: Uncaught TypeError: Cannot read property 'sdp' of undefined

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#166]
Reported by @ john:matrix.freelock.com in Matrix HQ

> Hi, on my homeserver, we currently have 2 users having 0 issues whatsoever logging in via vector.im, and two who just get the spinning icon never going away.	
> One of them just reported this JS error: Uncaught TypeError: Cannot read property 'sdp' of undefined
> in bootstrap.js
> This is happening even after cache clearing,

...

> they've tried both chromium and firefox with same result for these two users
same browsers as I'm using, and I've never had any trouble
(all of us are on Linux, ubuntu 14.04 or 15.04)

**Comment by erikjohnston** [comment]
John:
> ok, looks like the one person having trouble with a matrix.freelock.com account has no trouble with a matrix.org account

`matrix.freelock.com` is running: Synapse 0.10.0

**Comment by erikjohnston** [comment]
![vectorbug](https://cloud.githubusercontent.com/assets/8428120/9916593/037ba6d2-5cb5-11e5-9f38-a215a89fdc1f.png)

**Comment by Kegsay** [comment]
Needs moar paranoia checks. This is actually a JS SDK bug.

**Comment by dbkr** [comment]
Paranoia check added.
