### ISSUE TITLE
[Feature] Set a sensible height limit on code blocks

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/vector-web#1664]
Currently there isn't a limit on the height of a code block. It would be nice to have them set to a certain maximum size and then display some scroll bars after that point. The current way I've been doing it is just hosting on third party sites which seems a little silly. 

Even better if there was some prompt for a "display more" option rather than a ugly scroll bar in my opinion, but that's debatable.

**Comment by Half-Shot** [comment]
Basically what @aviraldg did here 

![](https://half-shot.uk/_matrix/media/v1/download/matrix.org/cRjzmeAyyIBmAWrYlZTOtroS)

**Comment by aviraldg** [comment]
@ara4n @Half-Shot looks like this fixed?
