### ISSUE TITLE
HTML tags in URLs breaks linkification

### ISSUE THREAD

**Issue by aviraldg** [vector-im/vector-web#1683]
See: https://vector.im/develop/#/room/!DgvjtOljKujDBrxyHk:matrix.org/$14666322971057571tOJrl:matrix.org

![screenshot from 2016-06-23 03-29-25](https://cloud.githubusercontent.com/assets/238916/16285239/bc251e92-38f2-11e6-9e3b-dcbd68f8e76f.png)
![screenshot from 2016-06-23 03-29-06](https://cloud.githubusercontent.com/assets/238916/16285240/bc5ed498-38f2-11e6-8949-93af91166c75.png)

Should fix this or turn linkification off for rich text messages.

**Comment by ara4n** [comment]
dup #1561
