### ISSUE TITLE
Vector hangs and begins consuming an increasing amount of memory

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/vector-web#1691]
I just joined a new room and attempted to scroll up almost immediately after doing so. Then this happened:

![screen shot 2016-06-24 at 10 04 31 am](https://cloud.githubusercontent.com/assets/1923178/16340258/176db6e4-39f5-11e6-8b46-6cfc196697d3.png)

Vector pegged one of my CPU cores and ate up a few GB of memory:

<img width="592" alt="screen shot 2016-06-24 at 10 09 48 am" src="https://cloud.githubusercontent.com/assets/1923178/16340264/24807312-39f5-11e6-8482-ec04396f3e7b.png">

About 10 minutes later, memory usage had increased by another GB:

<img width="592" alt="screen shot 2016-06-24 at 10 19 06 am" src="https://cloud.githubusercontent.com/assets/1923178/16340270/2e96a632-39f5-11e6-9dc0-eafe3c29b01b.png">

I tried doing a JS profile recording from Chrome, but it hung on "Initializing recording." Nothing had been logged in the JS console.

**Comment by ara4n** [comment]
@jfrederickson thanks for this, and sorry for the delay in triaging it. have you seen it since, and did you get or remember any JS console logs?

**Comment by jfrederickson** [comment]
I've not seen it again since then, unfortunately. I'll try some more to reproduce it if I can.

**Comment by ara4n** [comment]
I reckon this might be the same as #2020, which luckily I can reproduce.

**Comment by ara4n** [comment]
...actually, it won't be #2020, given there are no invisible events in that particular room :(

**Comment by ara4n** [comment]
given this hasn't recurred and #2020 is now fixed, going to assume this was solved somewhere along the way too.
