### ISSUE TITLE
README.md ambiguity

### ISSUE THREAD

**Issue by mcat-ee** [vector-im/vector-web#1720]
The readme contains the following note regarding the default identity server URL:
`default_is_url is the default identity server url (this is the server used for verifying third party identifiers like email addresses). If this is blank, registering with an email address or adding an email address to your account will not work.`

what exactly is an identity server? Is it something that takes an email address and returns 200 for a valid address and 400 otherwise? 

Or is it similar to slack in that it's a URL that email addresses are checked against to ensure they're from the same domain? (Which seems incorrect, but I've included for the purposes of showing the ambiguity).

Additionally; when you say registering with an email address/adding an email address to an account doesn't work, what do you mean?

As in it won't be saved to the database, or that registration just straight up won't work?

Thanks!

**Comment by ara4n** [comment]
Hopefully the above commit fixes things.  Quickly responding here just in case it doesn't:

> what exactly is an identity server? Is it something that takes an email address and returns 200 for a valid address and 400 otherwise?

It's a server that maps email addresses to matrix IDs.

> Or is it similar to slack in that it's a URL that email addresses are checked against to ensure they're from the same domain? (Which seems incorrect, but I've included for the purposes of showing the ambiguity).

It's not, but ambiguity understood.

> Additionally; when you say registering with an email address/adding an email address to an account doesn't work, what do you mean?

We mean that you these bits of UI will error if you try to use them.

> As in it won't be saved to the database, or that registration just straight up won't work?

You'll get an error of some kind.
