### ISSUE TITLE
URL previewing multiple links to large images can crash synapse

### ISSUE THREAD

**Issue by Battleroid** [vector-im/vector-web#1731]
Hello, I'm not sure if I should be opening this report here or on Matrix's Synapse repository (not entirely sure which causes this), please let me know if I am in the wrong area.

Apparently posting multiple image links in a single post causes the server to crash. Not sure why. After a restart the thumbnails are generated though.

For example I posted the following that caused and abrupt crash:

```
https://really.neato.site/data/yWmUDVexUktpuCSh.JPG
https://really.neato.site/data/vvtpuhaJrjiUKliF.JPG
https://really.neato.site/data/CbtsCKl9tMZTQZ8v.JPG
https://really.neato.site/data/RlnzQN5ICOPRuFY0.JPG
https://really.neato.site/data/Qg7dv4XzwbU5B3El.JPG
https://really.neato.site/data/Rz3tCdhDelAjm4wM.JPG
```

**Comment by ara4n** [comment]
@Battleroid hmm. it's possible that going and spidering and thumbnailing all those images caused the synapse to consume too much RAM and get killed by some out-of-memory process killer.  Do you have the synapse logs to see what happened?

**Comment by Battleroid** [comment]
Here's the [log](https://really.neato.site/data/H2mOnNB0ZKfvtPNu.log) which I snipped to a little bit before and after posting the same set of six links again (which caused a crash once more).

**Comment by richvdh** [comment]
unfortunately if synapse is crashing there won't be anything useful in the homeserver log.

If it's been killed by the oom-killer, that will be recorded in the syslog. Otherwise you'll probably need to capture the stderr from the process, which typically means running it directly (`<virtualenv>/bin/python -m synapse.app.homeserver`) rather than using `synctl`.

**Comment by richvdh** [comment]
Lack of info here.
