### ISSUE TITLE
Membership list ordering broken

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-web#1740]
Expected: online, idle, offline then most recently active, actual: just by most recently active

**Comment by ara4n** [comment]
This seems to be a regression of https://github.com/matrix-org/matrix-react-sdk/pull/275

**Comment by dbkr** [comment]
Awaiting feedback to see if this is fixed

**Comment by dbkr** [comment]
It isn't, but having looked together, looks like this is actually behaving as intended and may be visual confusion because greyed out offline users can have sooner last active times than online-but-not-currently-active users.

To fix this, we're going to make offline users with a last active time the same mid-grey as idle users.

**Comment by ara4n** [comment]
...which then happened, and all is good in the world.
