### ISSUE TITLE
Context Menu: Restyle the LHS menu white

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1745]
Context Menu: Restyle the LHS menu white

- Needs some small design tweaks and assets to be marked ready

**Comment by AmandineLP** [comment]
behaviour: hovering over the room name shows the (...) over the avatar. context menu displayed on click on (...)

**Comment by bradlegge** [comment]
Screen reference for this ticket 
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=5746423e3135b1130ff70e56
