### ISSUE TITLE
Left panel "mention states" (room notification volume) indicator

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1747]
Left panel mention states: add mention indicator and restyle.

- Design: small tweaks and assets need to be marked ready

**Comment by AmandineLP** [comment]
what is the difference between #1746 ?

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=5775658fa7822070298d6fd2

Note: dev guys wanted a separate ticket for the mention indicator (this ticket) and one for the panel that pops out. Probably do it in one piece of work but I'm going with what they want for now as debating each and every little item just drains time ;)
