### ISSUE TITLE
Chat message states: implement new style

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1748]
Chat message states: implement the 6 different message states (style change) as per design

Notes:
- time appears inline with name always, but only for 1st message
- ellipses only on hover over
- people aligned on 1st line (bottom)

- Design: small tweaks and assets need to be marked ready

**Comment by bradlegge** [comment]
Screen URL:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=57472955e9be06520d813f80

**Comment by wmwragg** [comment]
See PR https://github.com/vector-im/vector-web/pull/1932 and https://github.com/matrix-org/matrix-react-sdk/pull/394 for the implementation discussion.

**Comment by wmwragg** [comment]
See PR #1987 and matrix-org/matrix-react-sdk#422 for the implementation discussion

**Comment by ara4n** [comment]
merged!
