### ISSUE TITLE
General design: implement new buttons

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1752]
General design (was Chat inline link 20a screen): implement all new buttons as per design  

* Design: all assets ready

**Comment by AmandineLP** [comment]
Includes: RHS panel icons (member list and notifications), room settings and search, send files and call buttons

Need design input for what happens when clicking on the phone button: how do we suggest voice or video to the user?

**Comment by wmwragg** [comment]
The RHS panel icons are taken care of in the https://github.com/vector-im/vector-web/issues/1747 issue are they not?

**Comment by wmwragg** [comment]
I think it might be a good idea to spin the new phone button and selection functionality into a new ticket. That way it doesn't block the button updates for all the updates.

**Comment by wmwragg** [comment]
Signed off and merged
