### ISSUE TITLE
Create room 3 and 4 (invite people to room) screen: User invite flow to be improved on 

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1758]
Create room 3 and 4 (invite people to room) screen:

**Original requirements from Amandine on basecamp**

Like for room creation we believe and have been supported by the users, that the invite flow is not right.

Today we have a single invite field to search and invite by email or by ID. People are completely missing the fact they can invite by email (Trevor’s question yesterday proves it again...). 

Our proposal was to display an “invite by email” button when starting typing in the room (basically replace the current first item of the suggestion list), which would open a modal popup where people can type emails or drop a list of them. We’re not entirely convinced that it will solve the email invite discovery problem (i.e. before you start typing into the box) but that could be a quick fix: any other suggestions? 

**(design only):** needs more design work as per comments (see how Dropbox handle this)

**Comment by bradlegge** [comment]
Screen URL's:
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577a596a405339122706de25
https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577a5966e557781e2d01545a

**Comment by ara4n** [comment]
After discussing further with @antikewl this morning, the suggestion is:

* We move the 'invite users' button to the bottom right, for (vague) symmetry with the buttons in the bottom-left-menu.
* We keep the old search filter box where it lives
* We (optionally) have a tooltip that appears when you start to search in the filter box to say "Do you want to invite instead?" that duplicates the 'invite users' button on the bottom right.
* We keep the Dropbox-style mass-invite screen, although it needs to be more fleshed out.

**Comment by antikewl** [comment]
Status update:
- We move the 'invite users' button to the bottom right, for (vague) symmetry with the buttons in the bottom-left-menu.
Done https://zpl.io/1BkPWb

- We keep the old search filter box where it lives
Done https://zpl.io/1BkPWb

- We (optionally) have a tooltip that appears when you start to search in the filter box to say "Do you want to invite instead?" that duplicates the 'invite users' button on the bottom right.
In progress (possibly not necessary, given the visibility of the bottom right button)

- We keep the Dropbox-style mass-invite screen, although it needs to be more fleshed out.
In progress
https://zpl.io/23ggM9
https://zpl.io/1iXBEQ
https://zpl.io/1VAP77
Copy to be improved, UI to be cleaned up (These screens are for 1:1, but multiple user invites will behave in a similar way).

**Comment by ara4n** [comment]
signed off

**Comment by ara4n** [comment]
Checking this again, I think @antikewl meant to link to https://zpl.io/Z1z0uAW and https://zpl.io/Z1cjXpn for the actual invite screens - which are very very similar to the "Start a chat" screens, but slightly different.

@wmwragg: might be worth bearing this ticket in mind whilst implementing #1882.

**Comment by ara4n** [comment]
A potential complication that I just realised is that we have some of this UI already in the form of the "invite by email" button.  This ticket will effectively be replacing this with the UI similar to #1882.  **However**, we will still need to preserve the logic & UI that the "invite by email" stuff does in order to gradually invite lots of users to a new room.

This is suddenly a bit trickier than I thought :/

**Comment by wmwragg** [comment]
@ara4n This shouldn't be too much of an issue, as the `ChatInviteDialog` handles "mx" and "email" addresses, only one at the moment. I can just copy the backend logic of the `MultiInviteDialog`.

**Comment by ara4n** [comment]
i've fed back on some of this as part of #1884

**Comment by ara4n** [comment]
closing this; anything else will be new tickets.
