### ISSUE TITLE
Chat message states (design only): needs design completion

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1762]
Chat message states (design only): needs design completion as per comments and feedback

**Comment by ara4n** [comment]
how does this differ from #1748 ooi?

**Comment by bradlegge** [comment]
Screen URL

https://app.zeplin.io/project.html#pid=573bea252e3e73497df13165&sid=577a3d414d0ec56367a415cf

**Comment by wmwragg** [comment]
@antikewl is using #1748 for his design work now, as the design is being implemented now by @stefanpearson
