### ISSUE TITLE
End-to-end encryption: room member devices

### ISSUE THREAD

**Issue by bradlegge** [vector-im/vector-web#1784]
Need a way to list the devices associated with a participant in a room.  Currently this is a list of devices in the right-hand "Member Info" panel.  The fields we need to show are:
 * A unique ID of some kind for the device (e.g. #123)
 * A friendly name for the device (e.g. "My iPhone")
 * Whether this device has been:
   - verified (big green tick, green padlock or something)
   - blocked (big red cross?)
   - unverified (question mark?)
 * A way of starting the verification process for a device
 * A way of blocking the device.

**Comment by ara4n** [comment]
Current placeholder UI is: 
![image](https://cloud.githubusercontent.com/assets/1294269/16842174/5e3cd908-49d4-11e6-9b1d-8fcef6964e29.png)
