### ISSUE TITLE
New dialog CSS causes arbitrary spinners to have background color?

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1814]
E.g. hitting the 'create room' button in the bottom left menu now has a white solid background on the spinner, which looks weird and wrong. @wmwragg, i think this might be a regression from your dialog PR last week?

**Comment by wmwragg** [comment]
Looking deeper into the code, it appears that some spinners are specified as Dialogs! The dialog box has now been specified to be 60% width, with a max of 704px. So I think what you are seeing is the Dialog box at 60%, with the height of the spinner, and the spinner sat in the middle. It looks like the CSS for the Dialog is effecting much more than just the Dialogs, despite the naming. It effects the Lightbox and the Spinners which are specified as Dialogs, and possibly other things that are using the Dialog (Modal) for other things. I have worked out a way around this, by supplying the Modal with a special glass (mx_Dialog_spinner) when being used as a spinner, and keying off that to reset the Dialog class (mx_Dialog) when being used as a spinner. I will work further on this on Monday.

**Comment by ara4n** [comment]
thanks for investigating Will, and sorry for intruding on your Sun!

On 17/07/2016 21:12, William Wragg wrote:
> Looking deeper into the code, it appears that some spinners are
> specified as Dialogs! The dialog box has now been specified to be
> 60% width, with a max of 704px. So I think what you are seeing is the
> Dialog box at 60%, with the height of the spinner, and the spinner
> sat in the middle. It looks like the CSS for the Dialog is effecting
> much more than just the Dialogs, despite the naming. It effects the
> Lightbox and the Spinners which are specified as Dialogs, and
> possibly other things that are using the Dialog (Modal) for other
> things. I have worked out a way around this, by supplying the Modal
> with a special glass (mx_Dialog_spinner) when being used as a
> spinner, and keying off that to reset the Dialog class (mx_Dialog)
> when being used as a spinner. I will work further on this on Monday.
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/1814#issuecomment-233201391>,
>
>
or mute the thread

**Comment by wmwragg** [comment]
See #1822 for the fix
