### ISSUE TITLE
Implement new "talk to a person" UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1882]
Filing this as a design-tagged issue to differentiate from the existing https://github.com/vector-im/vector-web/issues/1392 and friends.

The result of talking to @antikewl this morning about having clear separate first-class citizens for "talk to user" versus "join/create a room" was to discuss 3 options:

1. make the (+) button in the bottom left give the choice of 'are you adding a direct chat or a room' before proceeding. this was dismissed as the thing users are complaining about is the idea that you have to 'add' or 'create' anything when you start talking to a person. People exist already; you just want to talk to them.

2. make the (+) button take you to a modal "Start!" screen of some kind which has both "talk to peeople" and "join/create rooms" sections or tabs.  Dismissed for same reason as the first option.

3. replace the current (+) and (directory) buttons with two new buttons: one for initiating direct chats; the other for joining/creating rooms.  Thus creating new rooms could be seen as part of directory management (or perhaps vice versa).  => Trevor to flesh this out.

### Conclusion:

1. [x] Switch icons on bottom-left menu for design (as per http://zpl.io/1BkPWb)
2. [x] Add hoverover tooltip as per design for bottom-left menu icons (as per http://zpl.io/1BkPWb)
3. [x] Implement new 'Start chat with a person' screen (as per http://zpl.io/23ggM9 and http://zpl.io/1iXBEQ and http://zpl.io/1VAP77).  We do not need the "manage networks" or searching external networks for now, we can search the current user DB that vector's old invite code maintains.

We do not need the final screen (http://zpl.io/Z7mQSg) as far as I can see.

**Comment by antikewl** [comment]
Status update: Complete, BUT bottom left icons (rooms/new 1:1) need to be changed now that I’ve used the “add person” icon for the icon in the bottom right to invite someone to a room.
https://zpl.io/1BkPWb

**Comment by ara4n** [comment]
This looks very promising - thanks.  I still think that the (+) icon for 'join/start a room' may need to somehow indicate rooms, rather than being a generic plus.

Something we have lost (and it seems to be my fault when writing up our conversation when I was in Rennes the other week) is the ability to locate who we are trying to talk to (or the room we are trying to join) based on remote network.

So, if I want to "speak to Trevor on ribot.slack.com", how do I tell the search thing that the 'trevor' i'm autocompleting should be looking for him on ribot.slack.com, rather than a different slack, or a different IRC network, or indeed Matrix proper?  Likewise if I want to join "#general", how do I say that's on ribot.slack.com, rather than an IRC channel called #general on (say) Freenode?

Both finding people & rooms is going to need some way to specify the target network.  For people, we also have the (existing) option of inviting by email address and giving them the option of how to join.

**Comment by antikewl** [comment]
Ah, ok. I think this is probably a sub-task of #1756. I'll add your comment there.

**Comment by ara4n** [comment]
The design here is good to go for the 'find people' screens as per:
 * zpl.io/1BkPWb (and the next 4 screens, linked below for completness):
 * zpl.io/23ggM9
 * zpl.io/1iXBEQ <-- with the simplification of skipping remote networks until the contact lookup API is available.
 * zpl.io/1VAP77
 * zpl.io/Z7mQSg  <-- I don't think this screen is actually needed, as per the comment on it.

The one proviso is that the 'room' icon still doesn't seem right, but this can be changed down the line.

The 'find room' screens are not finished or signed off yet, however.

**Comment by ara4n** [comment]
Plan is to split this into a People and a Room ticket so that @wmwragg can proceed on People unfettered.

**Comment by ara4n** [comment]
with #2054 split off, this is now signed off for real and good to go for @wmwragg

**Comment by wmwragg** [comment]
@ara4n Would you be able to update the description of this ticket with what it now represents, i.e. what I need to implement, cheers

**Comment by ara4n** [comment]
@wmwragg gah - sorry, missed this and got hijacked by other stuff. have updated the description now.

**Comment by ara4n** [comment]
have split out #2070 from this as discussed.

One issue that has come up however is what the behaviour should be if there are multiple 1:1 rooms already in existence to the target user.  Options are:

1. We either select one to reuse at random
2. Always create new 1:1s
3. or prompt the user to select from the choice of existing rooms somehow (which requires more design for displaying that choice).

**Comment by ara4n** [comment]
Conclusion on the above from talking to @wmwragg today was to reuse the oldest one.

**Comment by ara4n** [comment]
Feedback from the #2181 PR:

 * the overflow scrollbar on the RHS of the input field seems to be stuck on?
 * ...likewise on the autocomplete selection
 * the padding of the autocomplete doesn't match the design (compare the height of 3 rows between @antikewl's zeplin design and the implementation)
 * the autocomplete doesn't take up the full width (but this may be deliberate?
 * the entirety of the invite tile in MemberList should probably be a hit target
 * it would be really nice if tab completed manual mxids (as well as space and comma), given tab-complete is our common idiom here.

Final question: is a deliberate design that the 'User ID, Name or email' prompt is always on the last line, rather than flowing inline and moving over the autocomplete bar to match? (superficially, removing the width of the textarea, setting display: inline-block and putting a relative offset on the autocomplete bar seems to work)

**Comment by wmwragg** [comment]
@ara4n I have updated the above points, please tick off the sections that you're happy with the explanation for, and ping me any you aren't

**Comment by ara4n** [comment]
Okay, the ones i'm not happy with are: hit target for 'invite user' tile.  Given visually it's aligned with the rest of memberlist, i'd really really expect it to behave like the other tiles there, even if technically the round thing is a button rather than an avatar.

Tab-complete rather than Return-complete.  In autocomplete (both pre- and post-RTE) in the editor, we use tab to mean "please complete the current suggestion and move on".  We can keep return-to-complete too, but please can we have tab as well.  thanks!

**Comment by wmwragg** [comment]
@ara4n OK will do

**Comment by ara4n** [comment]
closed - thanks! :D
