### ISSUE TITLE
Custom message types are processed differently to m.text

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/vector-web#1901]
With the same body, a ``m.text`` will be processed differently to a custom event type. The example shows a newlines not being processed correctly. 

```
{
  "content": {
    "body": "Ben Prunty Music - MilkyWay (Explore) \nBen Prunty Music - MilkyWay (Battle) \n",
    "code": 0,
    "msgtype": "m.text",
   }
}
```
```
{
  "content": {
    "body": "Ben Prunty Music - MilkyWay (Explore) \nBen Prunty Music - MilkyWay (Battle) \n",
    "code": 0,
    "msgtype": "uk.half-shot.mpd.listing",
  }
}
```
will provide the result
![newline](https://cloud.githubusercontent.com/assets/2072976/17264265/b7c320da-55dd-11e6-8d8c-a58bdc7a06b6.png)

**Comment by Half-Shot** [comment]
Okay, so it comes down to the former having the CSS rule ``white-space: pre-wrap;``.
My next question is would there be any reason why unknown events can't be rendered as ``<span class="mx_EventTile_body">`` seeing as they are dealt with the same way internally.

**Comment by ara4n** [comment]
i'd expect they should be.

**Comment by ara4n** [comment]
PR welcome? O:-)

**Comment by Half-Shot** [comment]
Fixed :)
