### ISSUE TITLE
Vector crashes on firefox with unreachable code problems

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#191]
pztrn
Hey, I have problems with latest vector git and firefox... :)
It says in console: unreachable code after return statement
https://paste.pztrn.name/1364/ here is a snippet, it claims on line "actualHsUrl.href = this.getHsUrl();"

ivarbot
[1] #1364 • Some flood and nothing more

pztrn
it's on nodejs 4.1.0

Dave
pztrn: ah yes, that one has come up before, seems like firefox is erroorin out because it's found there's unreachable code

**Comment by dbkr** [comment]
I deleted this code in the refactor anyway, so the fix for this has just landed on master.
