### ISSUE TITLE
Until we can upgrade voip to video calls, we need a dedicated icon for placing video calls

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#1910]
@antikewl, @bradlegge - unsure if this is already being tracked somewhere, but it's fairly high priority, as otherwise the work in https://github.com/vector-im/vector-web/pull/1828 is a bit undermined.

**Comment by antikewl** [comment]
Temporary icon available at https://zpl.io/Z1wjxgY

**Comment by ara4n** [comment]
thanks trevor :)
