### ISSUE TITLE
LHS Implementation feedback

### ISSUE THREAD

**Issue by wmwragg** [vector-im/vector-web#1922]
This collects the feedback on the LHS changes made for tickets #1746 and #1841

**Comment by wmwragg** [comment]
- [ ] hitmask on the selectors of the dropdown mentions menu should include the bullets

**Comment by ara4n** [comment]
* [ ] Bolded long truncated can collide with the badge and look ugly (this on Chrome 52 on Linux):

![screenshot from 2016-08-03 17 3a39 3a00](https://cloud.githubusercontent.com/assets/1294269/17373744/826f149e-59a1-11e6-8f98-fc9c3ef2e45c.png)

**Comment by ara4n** [comment]
The only remaining item here is on the weighting question for @antikewl

**Comment by ara4n** [comment]
this wave of feedback all got gathered and sorted.
