### ISSUE TITLE
Show connectivity state and manage resending messages correctly

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#197]
The screens show the intended design

![08 1 no connection](https://cloud.githubusercontent.com/assets/1294269/10371352/93f5d828-6da8-11e5-9f68-41a628484cfa.png)
![08 2 timed out](https://cloud.githubusercontent.com/assets/1294269/10371351/93e7cbb6-6da8-11e5-9e4d-c0f54bb46715.png)
![08 3 timed out resend individual](https://cloud.githubusercontent.com/assets/1294269/10371350/93bf4f24-6da8-11e5-81f7-59f11c74b244.png)

**Comment by dbkr** [comment]
Can you clarify what causes the red bar to appear in the first screenshot when the messages are grey?

**Comment by ara4n** [comment]
the JS SDK being unable to poll the events stream. N.B. that artwork has updated since this.

**Comment by ara4n** [comment]
These screenies are old; see zeplin for latest & greatest
