### ISSUE TITLE
Autocompletion UX

### ISSUE THREAD

**Issue by jansol** [vector-im/vector-web#1973]
The current tab completion is still a mess UX-wise and some coherent design is needed before releasing it to the mainstream public.

IMHO a sensible behaviour would be similar to e.g. zsh's or slack's completion. My suggestion:

1.  The completion popup may show automatically, but has no entry selected and does not insert a completion until the user presses tab.
2.  Pressing tab inserts the first completion but does not dismiss the popup. (or maybe dismiss, this needs some thought)
3.  Subsequent presses of tab cycle through possible completions.
--  Arrow keys may navigate through completions as well.
5.  Pressing enter inserts the currently selected completion and closes the popup.
6.  Furthermore, pressing esc at any point dismisses the popup without further modifying the input box.

**Comment by superdump** [comment]
Agree with all of the above points.

For point 2, I agree with tab should not dismiss the popup. The reasoning is that the popup list gives context for how many times one may need to press tab for point 3.

**Comment by jansol** [comment]
Closing as a duplicate of #1761
