### ISSUE TITLE
Type errors when trying to swap rooms

### ISSUE THREAD

**Issue by Kegsay** [vector-im/vector-web#199]
Left `/beta` overnight and then tried to swap rooms and noticed that it wasn't doing it (recents would indicate it was selected but the room view didn't update). Looked in the console and got:
```
bundle.js:28 Uncaught TypeError: Cannot read property 'size' of undefined
bundle.js:95 Presence: online
bundle.js:29 Uncaught TypeError: Cannot read property '_currentElement' of null
bundle.js:105 Uncaught Error: Invariant Violation: Dispatcher.unregister(...): `ID_289` does not map to a registered callback.
```

It looks like maybe an event caused it to barf, since the errors map into Q callbacks (dunno the original stack trace frustratingly - bluebird would be a better choice in that regard, will make a bug in the JS-SDK to do that). Not sure if this is JS-SDK / React-SDK / Vector so filing here mainly to document it.

**Comment by ara4n** [comment]
Pretty sure Dave fixed this in react - it was barfing on an invalid event.
