### ISSUE TITLE
Doesn't gate you behind a loading screen when directly going to a room

### ISSUE THREAD

**Issue by Kegsay** [vector-im/vector-web#200]
`/beta`: Tried going to `https://vector.im/beta/#/room/#freenode_#matrix:matrix.org` and got to a screen with unpopulated recents, a "join room" button and that's it. It should've gated me behind the spinner until it had synced. Nothing in the logs to suggest an error was thrown. Bizarrely getting presence events though.

**Comment by dbkr** [comment]
Fixed in matrix-react-sdk 53a7f4b
