### ISSUE TITLE
Guests don't see other's messages in a room

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2044]
feels linked to #2039 
steps: 
- new guest user, 
- join #test:matrix.org or similar (notice issue #2039 and #2040 )
- send a message
-> other user can see it and replies
- guest doesn't see the other user's message,even after sending a new one, and even after scrolling up and down
reproed on both FF 

On Chrome, by scrolling up and down the "go to last message" grey arrow eventually appears and the user can reach the last message

**Comment by ara4n** [comment]
guest access was broken; now fixed
