### ISSUE TITLE
Inbound calls are invisible if the RoomSubList is collapsed

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2049]

**Comment by wmwragg** [comment]
@ara4n Any further details? What exactly does it mean by invisible, as apposed to what?

**Comment by ara4n** [comment]
if you place an inbound call, and the RoomSubList is collapsed, the inbound call tooltip is not displayed at all
sorry for lack of details on the bug; i filed it against myself at first

**Comment by wmwragg** [comment]
Gotcha. It's probably because they are aligned (though if I recall, not correctly) with the room element, but when collapsed, they don't exist.

**Comment by wmwragg** [comment]
@ara4n Is there any reason the incoming call box is trying to be aligned with a room tile (and also scrolling with it when LHS Panel is scrolled), as it's a pretty large dialog for that sort of thing. Wouldn't it be better to show in the centre or, top left/right?

**Comment by wmwragg** [comment]
Or if it must be against the LHS Panel, why not position next to the section header, as the room name appears in the call box?

**Comment by wmwragg** [comment]
Well for want of feedback, I'll place it against to header of the section the call's room is in, and also track it as it scrolls

**Comment by ara4n** [comment]
sorry - was eating. the reason for showing it with the room tile is to associate it with the relevant room. We could conceivably break that, although i quite like the idea that it's basically a speech bubble for the room in question.  Just putting it on the section header would be fine.  thanks!

**Comment by ara4n** [comment]
thanks @wmwragg!
