### ISSUE TITLE
Chrome can't view (some) PDF uploads

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2052]

**Comment by ara4n** [comment]
Failed to load 'https://matrix.org/_matrix/media/v1/download/matrix.org/AISHUFDDGSQDW' as a plugin, because the frame into which the plugin is loading is sandboxed."

@erikjohnston - i guess this is the anti XSS thingio backfiring.  Any thoughts on how we should treat PDFs so they load in-browser?  Or should we just set disposition for them to download straight to disk?

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/1071 should fix this
