### ISSUE TITLE
Presence updates can cause vector to chew CPU and lock up

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#206]
This must be a dup, but I can't find the original.

Every time I receive a presence update whilst in Matrix HQ, Chrome totally locks up for 100-500ms whilst doing something to the membership list.  This is still happening on very latest develop.

**Comment by dbkr** [comment]
I've updated vector.im/beta with some changes that should make presence updates faster. If were's still getting batches of presence updates from synapse, I think these will still be delivered individually by the js sdk so one of these would be the next target to improve if this is still a problem I think.

**Comment by ara4n** [comment]
haven't noticed this recently - closing for now
