### ISSUE TITLE
m.call.* needs to be E2E'd in an encrypted room

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2066]

**Comment by ara4n** [comment]
...and generally any non-state event should be, obviously.

**Comment by ara4n** [comment]
We presumably need to think about this more carefully, given the server really needs to know the underlying type of an encrypted event (or at least whether it's m.call.* or not) in order to send the right pushes around the place...

**Comment by richvdh** [comment]
This got fixed by matrix-org/matrix-js-sdk#277.
