### ISSUE TITLE
Multiple browsers from the same user can't each other's megolm's messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2079]
I assume this is because the olm session update messages aren't self-decryptable

**Comment by richvdh** [comment]
Multiple browsers? One browser, multiple tabs? Are you sure this isn't just that we don't actively check for new devices?

**Comment by richvdh** [comment]
So I repeated what I think you'd seen. This is just a special case of any other "I don't get the megolm keys when I log in again": you can't read *anybody's* messages (including your own) until they share the keys with you (which currently we only do when starting a new megolm session, which only happens on reload and join/part events).

**Comment by richvdh** [comment]
so this is basically a dup of #2088.
