### ISSUE TITLE
Vector crashes Safari 8.0.7 about 50% of the time with memory explosion

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#208]
About half of the time I try to launch current vector develop on Safari, the browser explodes, eating all the memory in my box and chewing 100% CPU, before it can even escape the initial spinner.

**Comment by Kegsay** [comment]
This may be related to various perf woes on Chrome/FF too (namely the "unresponsive" dialog on Chrome and the "Not Responding" dialog on FF). We're probably churning processing initial sync results: will need to profile it.

**Comment by Kegsay** [comment]
Fixed from https://github.com/vector-im/vector-web/issues/212
