### ISSUE TITLE
numbers with dot (ex. dates) are changed somehow

### ISSUE THREAD

**Issue by simsasaile** [vector-im/vector-web#2086]
How to reproduce:

Type for example a date in vector: `10. September` and send it: Vector shows `1. September`.
But if you only type `10.` (without any other word following) it dosen't change.

**Comment by ara4n** [comment]
This is markdown behaving correctly.  We are going to make markdown 
optional shortly - see #1763 for details, which will effectively fix this.

@aviraldg: this is a great example of where the MD icon should warn that 
MD has kicked in (if you have MD enabled)

**Comment by simsasaile** [comment]
Thanks for the fast reply and the explanation!
