### ISSUE TITLE
VoIP conference rooms now show up in the Rooms list

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2091]
I assume this is a regression introduced with @wmwragg's sticky headers

**Comment by wmwragg** [comment]
Well not the sticky headers but the direct message section, my apologies. Should be pretty simple to fix. In the `RoomList.js` file, within the `getRoomLists` method, just check if the room is a 1:1 room in the `// Used to split rooms via tags` section, if the other member of the 1:1 room is a conference user, then depending on the HIDE_CONFERENCE_CHANS variable, either keep it or ignore it:

```javascript
if (ConferenceHandler && ConferenceHandler.isConferenceUser(otherMember.userId)) {
    // depending on the HIDE_CONFERENCE_CHANS variable either keep it or ignore it
}
```

**Comment by ara4n** [comment]
this seems fixed now
