### ISSUE TITLE
Parted DMs are visible in the DM sublist

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2095]
I just found a parted DM from Yannick at the bottom of my DM Sublist.

**Comment by dbkr** [comment]
He left, or you did?

**Comment by ara4n** [comment]
I had left.

**Comment by ara4n** [comment]
I then hit the 'forget' button to remove it entirely, but it shouldn't have been visible at all - it should have been in the historical rooms list.

**Comment by dbkr** [comment]
I can't repro this on current develop: if I leave a DM room, it goes into Historical.

**Comment by ara4n** [comment]
It's possible I was on a slightly older develop. NB that this was an 
existing parted room which was left months ago rather than one that i 
parted on the fly.

On 06/09/2016 15:01, David Baker wrote:
> I can't repro this on current develop: if I leave a DM room, it goes
> into Historical.
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/2095#issuecomment-244959407>,
>
>
or mute the thread

**Comment by dbkr** [comment]
Oh, now I can.

**Comment by dbkr** [comment]
Fixed now
