### ISSUE TITLE
Megolm messages fail if one of the servers in the room is unreachable

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-web#2107]

**Comment by ara4n** [comment]
We should dial down the timeout for querying remote device keys in synapse, and presumably also uphold the retry schedule from the `destinations` table.

**Comment by richvdh** [comment]
We'll need to add some semantics to the `/query` and `/claim` APIs to mean "server unreachable". Possibly just omitting the user/device from the results.

**Comment by ara4n** [comment]
mjark fixed this ^
