### ISSUE TITLE
Initial load of vector is slow and takes >20s of 100% CPU

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#212]
When I, `@erikj:jki.re`, open vector or reload vector, it can take over 30s to load. All but 2s (max) of this is it sitting churning 100% CPU rather than waiting for initial sync.

This in Chrome on Ubuntu.

**Comment by Kegsay** [comment]
Strongly suspect this and https://github.com/vector-im/vector-web/issues/208 are related.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/30

**Comment by Kegsay** [comment]
Fixed and landed.
