### ISSUE TITLE
Support E2E for guests

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2155]

**Comment by ara4n** [comment]
At the least we should disable it for them.

**Comment by richvdh** [comment]
breaks how, exactly? As a guest I see "**Encryption not enabled**" for encrypted messages, and messages I send in encrypted rooms are sent in the clear.

Once I register, it all seems fine.

The only thing we might do here (other than actually supporting E2E for guests) is to give a better error message for encrypted messages.

**Comment by ara4n** [comment]
The point of this one was that E2E should be able available to guests, so that if a guest follows a link into an e2e room, they can participate.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/1653, hopefully.
