### ISSUE TITLE
New users (& devices?) joining a megolm room are not being recognised and encrypted for (O HAI is broken?)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2156]
Specifically, the m.new_device my test account sent a broken O HAI with content `{ messages: {}}`, but https://github.com/matrix-org/matrix-js-sdk/pull/200/files#diff-3d7f0c7d5957a1a25c5f62640040bb6bR873 suggests it should be spamming all my users to tell them about my new device.

**Comment by richvdh** [comment]
It shouldn't be issing oh hais at all in the case of a user joining a room (we have m.room.member to do that for us). So, uh, dunno.

**Comment by ara4n** [comment]
i guess then a related problem is that other people in the room aren't 
picking up the new user/device, so the new user can't see what's going 
on (and sees only 'unknown group session' errors from everyone else).

On 10/09/2016 19:23, Richard van der Hoff wrote:
> It shouldn't be issing oh hais at all in the case of a user joining
> a room (we have m.room.member to do that for us). So, uh, dunno.
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/2156#issuecomment-246127386>,
>
>
or mute the thread

**Comment by ara4n** [comment]
@erikjohnston  was also saying that he was seeing his HS choking on O HAI message received over federation somehow and failing to wakeup the eventstream to deliver them to clients?

**Comment by NegativeMjark** [comment]
It looks like the ``m.new_device`` (O HAI) messages are working as intended. However there are a few race conditions when joining rooms that won't be handled by them.

As a workaround I'm think of making the following changes to the JS sdk:
 1) Include the sender device_id in the encrypted messages.
 2) When vector receives a message that it cannot decrypt it will send a ``m.new_device`` message to the sender device.

This means that at least it will be able to decrypt subsequent messages from that sender device.

@ara4n Does that sound sane?

**Comment by NegativeMjark** [comment]
Turns out that the issue that @ara4n was seeing was because he was using a local build of vector using a stale version of olm. This has been fixed by upgrading his version of olm.
