### ISSUE TITLE
In 'Start new chat', I am shown as "@matthew:matrix.org @matthew:matrix.org" rather than having a displayname

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2184]

**Comment by ara4n** [comment]
Arguably i shouldn't be able to try to start a chat with myself at all.  And even if i do, the displayName should be right...

**Comment by ara4n** [comment]
comme ça:
<img width="686" alt="screen shot 2016-09-13 at 22 48 36" src="https://cloud.githubusercontent.com/assets/1294269/18492687/8a715a66-7a04-11e6-9223-a542df94a937.png">

**Comment by wmwragg** [comment]
I can't replicate this, you show correctly for me, and in the backend, all I'm doing is calling `MatrixClientPeg.get().getUser` to get the user from the MXiD, and then calling `userId` and `displayName` to get these. If it can't find the `displayName` it will use the `userId` instead. Do you have replication steps?

**Comment by ara4n** [comment]
does it work for your user? i assume it's a self-chat problem.  (If i'm 
logged in as @matthew:matrix.org I wouldn't expect @matthew:matrix.org 
to show up as a chat target at all, anyway!)

**Comment by wmwragg** [comment]
@ara4n Yep checked that, as I thought that might be the problem, but I'm shown fine:

![screen shot 2016-09-14 at 13 58 37](https://cloud.githubusercontent.com/assets/327409/18512999/800c1d3e-7a83-11e6-86eb-f58882828799.png)

I left the logged in user in the list, as you may be adding yourself to a new room... but actually thinking about that, that's never going to happen is it, as you will always be part of any room you are inviting users too, and if you are creating a room, then you are added as the first user anyway. Is this correct? If so I'll removed the logged in user from the list

**Comment by ara4n** [comment]
it's correct. thanks
