### ISSUE TITLE
Guest access is broken.

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2194]
a new user (guest, or newly upgraded from guest or newly registered) can't access rooms like #testingGuest:matrix.org from the directory. They can join if explicitely invited from the room. A registered user can join a public room where Guest access is not enabled like #test123:matrix.org

![image](https://cloud.githubusercontent.com/assets/8582858/18513246/001c60e8-7a8d-11e6-806c-ce56ff659997.png)

**Comment by ara4n** [comment]
fixed in matrix-org/matrix-react-sdk@7b126a0
