### ISSUE TITLE
Can't start a chat from 'start new chat' icon with a matrix ID if I don't share a room with this user already

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2195]
Eg as Amandine I can't start a chat with a guest ID if we don't share a room. As a newly registered user I can't start a chat with @Amandine:matrix.org if we don't share a room

![image](https://cloud.githubusercontent.com/assets/8582858/18513263/16b9536a-7a8d-11e6-9dcc-20ddde789962.png)

**Comment by wmwragg** [comment]
@AmandineLP You need to make sure that you convert it into an address tile before trying to send, by pressing space or comma. You can then hit the "Start Chat" button. I can see that this is not very intuitive, especially for just one user. I'll ask @antikewl for some guidance

**Comment by wmwragg** [comment]
@AmandineLP I have made it so that if there is an unconverted address in the input field, it will now check it and use it, rather than having to convert it first
