### ISSUE TITLE
The "Login Failure" error is way too ambiguous

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#220]
If users try to log in with an invalid email address, you get told "Login Failure". It's very unclear to the user whether this is because an email address doesn't exist, or something else is wrong.  A better warning ("Unrecognised login") would be much better.

**Comment by Kegsay** [comment]
It's ambiguous because Synapse is 500ing the `/login` request from the looks of it. SYN-502

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/21

**Comment by Kegsay** [comment]
Both PRs are now merged; closing this.
