### ISSUE TITLE
Remove old filter-based invite UI from MemberList

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2200]
If necessary, we can just comment out the bit which renders the invite-search results? i.e. the top half of the filtered MemberList

**Comment by wmwragg** [comment]
@ara4n Cool. So we'd just see a list of users in the room, and no search/invite, as that should be pretty simple

**Comment by ara4n** [comment]
no - we need to keep the filtered search results; i'm just suggesting we hide the div which shows the invite results (as an ugly workaround) if a bigger refactor is going to be hard.

**Comment by wmwragg** [comment]
Right, When I looked at that yesterday, it was a little more complicated than that, as you then see some member tile as the first position rather than the Invite email. But I was in  a rush yesterday, so I'll take another look

**Comment by wmwragg** [comment]
Implement the RHS Panel from https://zpl.io/Z13pkVG well just the filter section
