### ISSUE TITLE
Receiving a 1:1 invite from a client that doesn't do is_direct is not heuristically recognised as a DM

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2205]

**Comment by ara4n** [comment]
ex3ndr just invited me to a 1:1. presumably it wasn't from a DM-aware client, so it appears as a normal room. If it's not DM-aware, should we be doing heuristics on incoming invites to try to guess if they are DMs (for legacy clients?)

**Comment by ara4n** [comment]
actually, isn't this pretty important given the mobile clients aren't DM aware yet?

**Comment by dbkr** [comment]
I can apply the heuristic on join, although this won't catch invites if you join on a non-web client
