### ISSUE TITLE
Received push notifications for a room before joining it(!?!)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2207]
I got an invite into a federated room which already had users on matrix.org and a remote server.  Befoer joining, I saw I was getting iOS push notifs for the room despite me not yet having joined!!

**Comment by ara4n** [comment]
@erikjohnston - please can you investigate this? i can give more details offline for the room if needed, but i swear it happened....

**Comment by erikjohnston** [comment]
It was fixed this morning.

**Comment by ara4n** [comment]
then close it dear liza, dear liza... O:)
