### ISSUE TITLE
Let users manually join rooms by room alias in RoomDirectory.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2217]
Our RoomDirectory implementation is currently converging on zpl.io/Z1RCiSd (but with the Create Room button being in the bottom-left rather than the top menu).

However, we've just realised that we are missing UX for joining a room by room alias (e.g. #matrix:matrix.org).

The current behaviour in Vector is that if you enter a name like #matrix:matrix.org into the search field and hit return, it joins you to it - however, this is very unintuitive.  Suggestions on how to make it more discoverable would be very appreciated.

**Comment by antikewl** [comment]
Hello. The behaviour is similar, but I added some explanatory text to the search field in this newer version. https://zpl.io/ZCjdQJ

![chat directory search](https://cloud.githubusercontent.com/assets/3658981/18553421/4698ef20-7b58-11e6-997a-d6454ba355bc.png)

**Comment by ara4n** [comment]
This is okay, but it's very unintuitive to the user that having typed #supersecret:wherever.com into the box they need to hit return to actually join it (especially given the directory list will have been filtered down to nothing).

How about having a line at the top of the search results saying "Join #supersecret:wherever.com"?

**Comment by ara4n** [comment]
Trevor came up with a design: https://zpl.io/ZFNz6j where if the user enters something that looks like a room alias a join button pops up. just need to implement it now.....
