### ISSUE TITLE
setting an address for a room systematically fails with M_NOT_FOUND

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2221]
but the address is still set

![image](https://cloud.githubusercontent.com/assets/8582858/18569270/dcb737e8-7ba1-11e6-900a-3de4be021933.png)

**Comment by AmandineLP** [comment]
pick a room or use a new one
select an accessibility setting which requires an address
click on the link to go to the address setting anchor
enter an address
press enter (I think I never use the '+' button)
use the drop down to select the address you just created
click Save on the settings page

**Comment by ara4n** [comment]
i fixed this.
