### ISSUE TITLE
Exit settings page /after/ using scalar, not before, if there are no changes

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2225]
Otherwise postmessage breaks

**Comment by ara4n** [comment]
@lukebarnard1 - fixed; sorry about that

**Comment by ara4n** [comment]
(in matrix-org/matrix-react-sdk@77595320a71dc5643ca1b896b777fb59c6cc4c45)

**Comment by lukebarnard1** [comment]
Wahoo! Thanks :+1:
