### ISSUE TITLE
Room tiles are no longer visible when being drag & dropped between sublists

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2226]

**Comment by ara4n** [comment]
my fix for this last time was to experiment with different `display: table-cell` style displays until Chrome deigned to render the placeholder during drag.

**Comment by wmwragg** [comment]
This looks like its working for me on Safari, Chrome and Firefox.

**Comment by wmwragg** [comment]
@ara4n Do you have reproducible steps for this?

**Comment by ara4n** [comment]
...and it's working for me now too. no idea what was going on there. sorry :-/
