### ISSUE TITLE
Starting a new chat with someone by using the keyboard entry raises an error

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2236]
steps: 
- start new chat (bottom left menu), 
- start entering the name of someone eg Matt, 
- press enter to autocomplete and select the first selection, 
- press enter to validate the start 
-> failure to invite. 

Feels like it tries to invite the empty line

![image](https://cloud.githubusercontent.com/assets/8582858/18588335/5089a3e8-7c26-11e6-911e-d5233d608946.png)

**Comment by ara4n** [comment]
just for a change, i can't repro this...

**Comment by ara4n** [comment]
nor can @AmandineLP
