### ISSUE TITLE
searching in new invite dialog for users with space in their displayname doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2245]
e.g. searching for Matthew Hodgson fails when you hit space, as it doesn't let you press space

**Comment by ara4n** [comment]
@wmwragg heads up I fixed this with some other keyboard shortcut tweaks in matrix-org/matrix-react-sdk@da85df9.

(that code is a pleasure to hack on - thanks! :)

**Comment by wmwragg** [comment]
@ara4n Cheers. Taking a quick look at the commit, you should probably also trim spaces from the begining and end of the input before checking or adding to the invite list, as neither the mxid or email addresses allow these, and should also help confusing error messages

**Comment by ara4n** [comment]
mm. good point.

On 17/09/2016 16:11, William Wragg wrote:
> @ara4n <https://github.com/ara4n> Cheers. Taking a quick look at the
> commit, you should probably also trim spaces from the begining and
> end of the input before checking or adding to the invite list, as
> neither the mxid or email addresses allow these, and should also help
> confusing error messages
>
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/2245#issuecomment-247779934>,
>
>
or mute the thread

**Comment by ara4n** [comment]
Done in matrix-org/matrix-react-sdk@6e57fae - thanks :)
