### ISSUE TITLE
Inviting a user from the bottom right invite button fails with wrong error

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2246]
the room is pretty new, default settings, includes a guest and a registered user. the guest in the room tries to invite another guest
![image](https://cloud.githubusercontent.com/assets/8582858/18602936/9e3a73e6-7c6d-11e6-9d4c-dc3ffcbe17f2.png)

**Comment by AmandineLP** [comment]
Actually this is true for any user in the room, inviting any user

**Comment by ara4n** [comment]
fixed
