### ISSUE TITLE
"Large" (~3MB) file uploads crash with connection reset on beta

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#227]
Results in JS console errors looking like:

POST https://matrix.org/_matrix/media/v1/upload?access_token=censored&filename=censored net::ERR_CONNECTION_RESET
(index):1 Uncaught SyntaxError: Unexpected end of inputu.onreadystatechange @ http-api.js:114

**Comment by ara4n** [comment]
This is using today's https://vector.im/beta

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-js-sdk/commit/2c805bbeceb4482715916ed523b6bcaab8525b29 fixes the error, but doesn't fix the fact that your connections are being reset. I can't repro the connection woes.

**Comment by ara4n** [comment]
The connection woes are 100% reproducable currently on our office wifi (but not the wired LAN). ops are investigating.

**Comment by Kegsay** [comment]
If this is unrelated to vector, we should close this issue. The `Uncaught SyntaxError` was valid and has been fixed in the JS-SDK, so I see no actionable work to do here.

**Comment by ara4n** [comment]
Whilst this isn't a bug on vector itself, I don't have anywhere better to track it so would rather leave it open here.  Current status is that the network is working okay today, but was reliably broken yesterday - clearly some conntrack table is maxing out somewhere or similar.

**Comment by ara4n** [comment]
Ftr this looks to be some kind of bad interaction between apple hardware and cisco aironet access points.  OSX cranks up the window size to be huge and is sending as fast as it can (12MB/s); something then interrupts the stream (possibly the cisco doing layer-4 inspection even though it shouldn't be) and it wedges.  Turning off window scaling on OSX (sysctl net.inet.tcp.rfc1323=0) is a workaround for now, although it still bites iOS.  Closing now I at least have a workaround.

**Comment by ara4n** [comment]
This is back, thanks to Apple inexplicably removing the rfc1323 sysctl in OSX 10.11 >:(

**Comment by ara4n** [comment]
https://discussions.apple.com/thread/7408993?start=0&tstart=0

**Comment by ara4n** [comment]
...and fixed again as per https://discussions.apple.com/message/30072519#30072519 via `sudo sysctl net.inet.tcp.broken_peer_syn_rexmit_thres=0`
