### ISSUE TITLE
Would be nice if 'start new direct chat' label was fitting on the same line as the buttom

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#2279]
in member info

![image](https://cloud.githubusercontent.com/assets/8582858/18620525/80db2b08-7de2-11e6-9412-90250128ef2a.png)

**Comment by aaronraimist** [comment]
It should be on the same line now. The text was changed from "Start new direct chat" to "Start new chat" so this bug can be closed now.

https://github.com/matrix-org/matrix-react-sdk/commit/a2904ad33f9f45d5e7caf21158078c00e779b275

![screen shot 2016-10-01 at 11 19 30 pm](https://cloud.githubusercontent.com/assets/5855073/19018638/6a1bf034-8830-11e6-9361-6f3630bff2ad.png)

**Comment by ara4n** [comment]
...except didn't work for some reason. hopefully fixed again in 24239c8
