### ISSUE TITLE
Tab completion w/ RTE breaks with multiple emoji in nick

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/vector-web#2294]
When tab completing a nick with multiple emoji in it when RTE is enabled, the cursor doesn't show up at the end.

![screen shot 2016-09-19 at 4 15 23 pm](https://cloud.githubusercontent.com/assets/1923178/18647623/d267d082-7e84-11e6-8ca3-02744fb8032f.png)
![screen shot 2016-09-19 at 4 16 39 pm](https://cloud.githubusercontent.com/assets/1923178/18647625/d26b1b8e-7e84-11e6-93d5-2efde277e62f.png)

**Comment by aviraldg** [comment]
Closing as duplicate of #2180
