### ISSUE TITLE
We create a blank E2E device with no displayname on initial login

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2296]
Surely this should have a displayname?

**Comment by richvdh** [comment]
by initial login, do you mean registration?

This is actually a surprisingly annoying thing to fix, and ties into the workings of the registration API. But yes, we should.

**Comment by ara4n** [comment]
no, i think it happens whenever i login.

**Comment by richvdh** [comment]
Really? I can't reproduce that at all.

**Comment by richvdh** [comment]
I don't think this is a thing. Please reopen if you can repeat it!
