### ISSUE TITLE
Failure to recognise E2E rooms as being E2E

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2306]
User DM'd me; i answered on iOS; they turned on E2E; i then switched to Web.  I couldn't decrypt their inbound sessions (which is possibly surprising, given joining the room from iOS should presumably have caused them to download my device details and encrypt for me anyway), but more worriedly when I responded it sent it unencrypted :-/

**Comment by richvdh** [comment]
can't repro
