### ISSUE TITLE
speech bubble with pointer to the left instead

### ISSUE THREAD

**Issue by rubo77** [vector-im/vector-web#2327]
I tweaked a bit at the CSS, so the number uf unread posts points to the left instead:

![auswahl_049](https://cloud.githubusercontent.com/assets/1591563/18730385/5ed64f1c-8056-11e6-80d6-84e6f84bc517.png)

so instead of 

    position:absolute
   
use `relative` and `top: -8px`

- use `margin-left: -12px;`
- instead of `border-top` and -right use left and bottom (like in the screenshot)

**Comment by ara4n** [comment]
the layout of the speech bubble is currently deliberate. i suggest you keep this in a userstyle or so for now - thanks :)

**Comment by rubo77** [comment]
But why do you point the bubble to the baseline of the target row and not the middle of the line?

**Comment by rubo77** [comment]
What do you mean with "deliberate" is it wanted, that the pointer goes too deep?
