### ISSUE TITLE
Guest access : "log in" link does not respond in App banner

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-web#2329]
Observed whereas I joined a room as a guest 
To reproduce : 

- Join a public room as a guest
- Click the "log in" button in the banner
- Url is changed (https://riot.im/app/#/login) but the page is not refreshed.

Note : It works correctly if I don't join a room previously.

**Comment by dbkr** [comment]
MessageComposer.js:70Uncaught TypeError: Cannot read property 'removeListener' of null
RightPanel.js:199Uncaught TypeError: Cannot read property 'getRoom' of null
