### ISSUE TITLE
Unable to remove improperly defined Gitter bridge

### ISSUE THREAD

**Issue by neurocis** [vector-im/vector-web#2340]
If you attempt to create a Gitter bridge and specify an invalid room upon initial setup you are unable to remove the bridge and then redefine it.

Riot/Vector thinks the bridge has not been defined yet, although an incomplete definition does exist, so you can re-specify a Gitter room but it will reply with an "Bridge returned HTTP 500 Internal Server Error: map[error:matrix-id !XyZ:matrix.org is already linked to undefined]" error.

**Comment by leonerd** [comment]
I've moved this over to https://github.com/matrix-org/matrix-appservice-gitter/issues/22
