### ISSUE TITLE
Room Organisation: Categories/Tags

### ISSUE THREAD

**Issue by neomodern** [vector-im/vector-web#2350]
A way to organise rooms. Could operate like a categories (one category per room), tags (can be multiple tags per room) or both. 

How about a dropdown menu here to swap between these different contexts:
![Room Organisation](http://i.imgur.com/AmTsVDJ.png "Room Organisation")

**Comment by ara4n** [comment]
So Riot already supports this as an easter-egg - there just isn't UI to configure it yet.

#1650 is the existing bug for this - thanks for highlighting it though!
