### ISSUE TITLE
Can we put placeholder text on the new 'select network' text/select field in RoomDir when blank?

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2374]
To spell out to people that they can put HS/DS URLs there

**Comment by ara4n** [comment]
hm, @dbkr - i'm not seeing the placeholder? I'm thinking of saying "homeserver URL" or something in the text field (but greyed out) when it's prompting you to enter something, so that you know what input it's expecting there, as it's not immediately obvious at all that you can enter a HS URL there.

**Comment by richvdh** [comment]
well, the PR hasn't landed yet, and we have this (bogus imho) convention of closing the bug once the PR is in progress.
