### ISSUE TITLE
When RHS panel is collapsed, the icon to expand it has the wrong title attribute

### ISSUE THREAD

**Issue by uhoreg** [vector-im/vector-web#2381]
When the RHS panel is collapsed, the icon to expand it looks like a "<", but the title attribute is a ">"

![screenshot - 290916 - 10 43 17 am](https://cloud.githubusercontent.com/assets/1012976/18958856/2011db16-8632-11e6-839a-c88c66b997f0.png)

**Comment by dbkr** [comment]
Good spot, thanks!
