### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by volkfried** [vector-im/vector-web#2397]
I have an account. Upon attempting to login, I get the little spinning symbol that says it's loading, but it very quickly stops, having done nothing. I tried resetting my password. It confirmed that the reset was successful. The problem remains. 

I'm using the Iceweasel browser, which is a fork of firefox that removes all of the non-free and DRM nonsense.

**Comment by richvdh** [comment]
please could you share your console logs.

**Comment by volkfried** [comment]
I'm afraid I don't know what you mean :s Not actually a programmer, I just like this stuff

**Comment by ara4n** [comment]
@volkfried what version of IceWeasel are you on?

To share the logs, right click on the page and select 'show inspector' or similar.  A pane will appear at the bottom; switch to the 'Console' tab; hit refresh; and then copy&paste whatever it shows into here once it's failed to work.

**Comment by volkfried** [comment]
Sorry for the late reply. Hardware problems on my laptop :s 

Iceweasel version is 1:49.0.deb4-2 in the Parabola repos. 

The problem also appears to have gone away on its own :p
