### ISSUE TITLE
Typing notifications never change in Firefox

### ISSUE THREAD

**Issue by leonerd** [vector-im/vector-web#2429]
After I switch to a new room, the first time someone starts typing I get a `Someone is typing` notification, but then that message never goes away once they've stopped typing. Nor does it update if other users start typing. The message remains right until I switch to a different room; the new room will now show its correct state, up until the first typing notification it receives, which too will get stuck. Switching back to the original room will once again be correct for a short while, until it gets stuck again.

This appears to be Firefox-specific, because if I run a Chrome side-by-side showing the same rooms on the same user account (and obviously the same homeserver), then the Chrome appears to behave correctly, dismissing the notice when required.

(Browser: Firefox 45.3.0)

**Comment by leonerd** [comment]
Actually, it seems worse than that. They never change while it's open. If they were typing when I switch then I see that they're typing but they never stop. If nobody was typing then I never see them start.

**Comment by leonerd** [comment]
Having updated to Firefox 49 it seems to have gone away.

**Comment by richvdh** [comment]
Reopened at #2456
