### ISSUE TITLE
Unread messages marker cannot be dismissed by keyboard alone

### ISSUE THREAD

**Issue by leonerd** [vector-im/vector-web#2450]
As far as I can tell, moving the mouse is the only user action that can clear the unread messages green bar. No amount of keyboard activity alone will clear it. This makes it awkward for keyboard-heavy mouse-light users such as myself to interact nicely with it.

Doubly annoying from a laptop wherein there is no scroll wheel, so I tend to scroll by using the Page Up / Page Down keys.

**Comment by ara4n** [comment]
dup #2346
