### ISSUE TITLE
If scalar button disappears, say why in the UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2468]
e.g. if uMatrix is blocking it

**Comment by ara4n** [comment]
...or noscript...

**Comment by lukebarnard1** [comment]
I feel it might be difficult to detect such errors. Having hacked something together, it appears that the only error message that might be available is something about the CORS request failing.

**Comment by ara4n** [comment]
Well, rather than just disappearing coyly, can we just replace it with 
an error saying "Can't connect to integration server" or something?


On 07/11/2016 17:58, Luke Barnard wrote:
> I feel it might be difficult to detect such errors. Having hacked
> something together, it appears that the only error message that might
> be available is something about the CORS request failing.
>
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub
> <https://github.com/vector-im/vector-web/issues/2468#issuecomment-258910896>,
>
>
or mute the thread

**Comment by lukebarnard1** [comment]
(For the relevant PRs: https://github.com/vector-im/vector-web/pull/2554, https://github.com/matrix-org/matrix-react-sdk/pull/543)

**Comment by lukebarnard1** [comment]
Yep, WFM!

**Comment by lukebarnard1** [comment]
FTR, those PRs landed with something looking like this:

![2016-11-08-112813_276x104_scrot](https://cloud.githubusercontent.com/assets/6750344/20097466/7bda7726-a5a6-11e6-9306-3f854929e3c3.png)
