### ISSUE TITLE
UI should spell out explicitly that rooms are not e2e by default

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#2471]

**Comment by ara4n** [comment]
We've had a few disasters with people assuming that normal 1:1s are encrypted, given there's nothing that says they aren't.  We should shove unlocked padlocks on the composer and possibly roomheader.  (Doing it per-message is probably overkill though)

**Comment by richvdh** [comment]
We've done it on the composer - assuming this is sufficient unless you say otherwise.
