### ISSUE TITLE
Unknown key-share attack on Olm

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-web#2483]
* Bob publishes his Ed25519 fingerprint key, Curve25519 identity key, and Curve25519 one-time keys.
* Mallory publishes her own Ed25519 fingerprint key, but Bob's Curve25519 identity key and one-time keys (signed with her own Ed25519 key).
* Alice claims one of Mallory's one-time keys, and sends a pre-key message to Mallory.
* Mallory cannot read it, but forwards it to Bob.
* Bob believes the message came from Alice; Alice believes she only sent it to Mallory.

**Comment by richvdh** [comment]
The fix here is to include recipient identification (for example, the userid) in the cleartext of (at least) the prekey messages. Bob could then tell that Mallory has forwarded a message sent to her.

**Comment by richvdh** [comment]
Resolved by https://github.com/matrix-org/matrix-js-sdk/issues/239

**Comment by pik** [comment]
I don't know much of the context here but could this be fixed by altering key-signing on upload or olm? Otherwise it really relies on the client not forgetting to implement this check.

**Comment by richvdh** [comment]
I don't think so... Bob's userid could be included in the signature of the public one-time keys (it already is for the identity keys), but there's still nothing stopping Mallory extracting the one-time key and re-signing it with her own user-id (as she has to with the identity keys).
