### ISSUE TITLE
Cannot connect to my matrix server using the riot iOS app

### ISSUE THREAD

**Issue by AlonAlmog** [vector-im/vector-web#2485]
Hi All,

when I try login to my internal matrix server externally using the riot iOS application, the app keeps on saying that "an SSL error has occured and a secure connection to the server cannot be made"

I'm using a wildcard certificate and the matrix server is located behind a reserve proxy. the certificate chain seems to be fine since the andriod app and the browser work.

would really appreciate your help.
Thanks

**Comment by richvdh** [comment]
Not a vector-web issue.

Suggest you try connecting to the homeserver directly from the browser on your phone (https://your.homeserver/_matrix/client/versions or similar). If that works, send a bug report from riot-ios.
