### ISSUE TITLE
ability to turn off matrix.to permalinks

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/vector-web#2525]
when HS is in internal or airgapped network, one might not want to leak any information outside nor can't even use the matrix.to service.

**Comment by ara4n** [comment]
n.b. that using matrix.to does not leak any information - the info about the target stays only in the browser as it's a URL fragment.  that said, agreed that the permalink service should be configurable - this is already filed as https://github.com/vector-im/vector-web/issues/2446
