### ISSUE TITLE
Weird blank tiles break vertical spacing and suggest missing events

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#253]
This may be because I set the timestamps to visibility: hidden rather than display: none, but nevertheless we have weird blank continuation li's which break everything.

<img width="995" alt="screen shot 2015-10-23 at 21 41 35" src="https://cloud.githubusercontent.com/assets/1294269/10704478/fef8ac5e-79ce-11e5-9367-fdbccb49c744.png">

**Comment by ara4n** [comment]
Meanwhile, I'm seeing entirely blank tiles altogether, which (from clicking 'view source') appear to be lost join events?

<img width="1804" alt="screen shot 2015-10-25 at 11 58 20" src="https://cloud.githubusercontent.com/assets/1294269/10715475/d4d6862a-7b0f-11e5-8cbc-6d8ef6569ac2.png">

**Comment by stevenhammerton** [comment]
This can be quite bad / ugly in quite channels with many joins / parts.

![image](https://cloud.githubusercontent.com/assets/1847703/10879377/7905b5ae-814b-11e5-9380-92f382a847a9.png)

**Comment by dbkr** [comment]
Fixed.
