### ISSUE TITLE
Ability to caption images while sending

### ISSUE THREAD

**Issue by Qwertie-** [vector-im/vector-web#2545]
Almost every time I need to post an image I also need a line of text explaining the image. Telegram like captions under images.

Here is an example from telegram of what I'm talking about https://i.imgur.com/kLWIrB2.png

**Comment by ara4n** [comment]
agreed - this is very much on the radar. the official bug for tracking this is #1818 - i'll close this as a dup.

**Comment by ara4n** [comment]
(ps good choice of example image :D)
