### ISSUE TITLE
if you scroll up a bit, sometimes you can't scroll back down

### ISSUE THREAD

**Issue by richvdh** [vector-im/vector-web#2590]
Somewhat similar to #1427

**Comment by lukebarnard1** [comment]
So the current thinking on this is that `canPaginateForwards` (or similar) in `TimelinePanel` is not being set to true when it should be, which means it doesn't try to paginate forwards, despite there being room to do so (with the most recent events never being re-paginated).

**Comment by richvdh** [comment]
This got fixed in https://github.com/matrix-org/matrix-react-sdk/issues/561
