### ISSUE TITLE
Room invitations don't trigger a browser notification

### ISSUE THREAD

**Issue by jaragunde** [vector-im/vector-web#2592]
When I'm invited to some room I don't receive a browser notification about it, despite those being set as 'noisy'. Notifications are enabled and work for other cases (one-to-one chats, pings, etc.).

Probably related to #1649, but reporting as a new issue as it is not exactly the same bug.

Thank you!

**Comment by richvdh** [comment]
Sorry, what is the difference to #1649?

**Comment by jaragunde** [comment]
#1649 is about playing a sound notification while this is about invoking the browser notification API. But if the code that does both things is the same, then they are the same bug :-)

**Comment by richvdh** [comment]
Ah right. Yup sounds like the same thing. Thanks.
