### ISSUE TITLE
Cannot Destroy/Close Create Room / Start Chat Modals (develop)

### ISSUE THREAD

**Issue by pik** [vector-im/vector-web#2601]
I am running the up-to-date `develop` of vector-web/matrix-react-sdk/matrix-js-sdk (following the development instructions of the vector-web Readme) and certain modals (Create Room, Start Chat) cannot be destroyed or escaped. The following error is logged: 

```
invariant.js:38 Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).```

All PhantomJS tests still pass.. 

Output for `npm ls react`:
```
vector-web@0.8.4 /home/pik/git/vector-web
├─┬ matrix-react-sdk@0.7.5 -> /home/pik/git/matrix-react-sdk invalid
│ └── react@15.4.0  extraneous
└── react@15.4.0 

npm ERR! invalid: matrix-react-sdk@0.7.5 /home/pik/git/vector-web/node_modules/matrix-react-sdk
npm ERR! extraneous: react@15.4.0 /home/pik/git/vector-web/node_modules/matrix-react-sdk/node_modules/react
```

**Comment by richvdh** [comment]
heh; I was just investigating exactly this. I'm slightly mystified by it currently.

**Comment by richvdh** [comment]
Fixed by https://github.com/vector-im/vector-web/pull/2603, hopefully
