### ISSUE TITLE
tools-menu on every message should open on mouseover hover

### ISSUE THREAD

**Issue by rubo77** [vector-im/vector-web#2604]
It would be really handy, if the menu on the right of each message would automatically open on mouseover

**Comment by richvdh** [comment]
Not sure I agree with this.

**Comment by rubo77** [comment]
what is the reason, that the options are hidden behind an extra click?

**Comment by ara4n** [comment]
i think this would get very noisy. if you want it, feel free to maintain a patch, but we're not going to add it to the main branch - sorry.

**Comment by rubo77** [comment]
Ok. 

What do you mean with"noisy"?
