### ISSUE TITLE
Turn off URL previewing by default in encrypted rooms

### ISSUE THREAD

**Issue by uhoreg** [vector-im/vector-web#2609]
URL previewing sends the URL to the server, which would be an information leak in encrypted messages.  When joining an encrypted room, or when encryption is turned on, Vector should disable URL previewing by default, and display a warning in the room settings that enabling previews may leak information.  Alternatively, add a setting for enabling/disabling URL previews for encrypted messages, since unencrypted messages in an encrypted room would bee fine to preview.

**Comment by richvdh** [comment]
Dup #2084
