### ISSUE TITLE
401 (Unauthorized) on ScrollUp for old historical links

### ISSUE THREAD

**Issue by pik** [vector-im/vector-web#2616]
After visiting old history links the client is unable to fetch further history on scroll-up (example): 

http://127.0.0.1:8080/#/room/#matrix-dev:matrix.org/$147164266743214YQjOp:matrix.org

```
https://matrix.org/_matrix/client/r0/rooms/!XqBunHwQIXUiqCaoxq%3Amatrix.org/messages?from=t76205-35798634_82495870_218046_6839801_45061_21493_64381&limit=20&dir=b&access_token=<access_token>
```

Returns a:
```
{"errcode":"M_UNKNOWN","error":"Unauthorized"}
```

Running Vector-web (riot) on commit 5cd4f88b8c6dd5348a8414c0c9cb04d7e4ab8509 (0.9.0).

**Comment by richvdh** [comment]
Any reason to believe this is a vector bug rather than a synapse one?

**Comment by richvdh** [comment]
(ftr this works absolutely fine for me)

**Comment by pik** [comment]
Hmm, I'll try connecting to the same room syncing with my own HS instead? It's the Matrix HS so I can't test it verbatim (btw does the Matrix HS declare it's version / commit somewhere exactly?)

**Comment by richvdh** [comment]
ok so I have investigated this and it is indeed a synapse bug. raised as https://github.com/matrix-org/synapse/issues/1648.
