### ISSUE TITLE
Specify port for vector to run on other than 8080

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/vector-web#2617]
Previously, the dev build web server would just try the first port it could grab. Currently, `npm start` will fail if the port is already in use (by a default synapse federation demo, for example).

Solution: allow port specification in some config somewhere or the CLI.

**Comment by lukebarnard1** [comment]
`npm run start:js -- --port 8083` is sufficient here.

**Comment by anoadragon453** [comment]
For me `npm run start -- --port=8083` worked.
