### ISSUE TITLE
[e2e] Impossible to read video sent via encrypted room

### ISSUE THREAD

**Issue by jeangb** [vector-im/vector-web#2631]
To reproduce:
- Create 1:1 room between device and webclient
- Enable encryption 
- Upload a video from the device (mine is very short: 1 second)
- Once it's done, try to read it or download it from the webclient

Control bar of the video are disabled.
![disabled control bar of video](https://cloud.githubusercontent.com/assets/22364949/20533945/ac94dee4-b0df-11e6-8393-e535debf11a3.jpg)

**Comment by richvdh** [comment]
@jeangb: I can't repeat this.

**Comment by richvdh** [comment]
Looks like it's being sent with "mimetype": "image/jpeg".

**Comment by jeangb** [comment]
@richvdh ok so this may be a bug on android client ?
