### ISSUE TITLE
Go back to the previous messages and send it again

### ISSUE THREAD

**Issue by floviolleau** [vector-im/vector-web#2649]
I would like to have the possibility to move (with up and down arrow in the input) in the history of my previous messages to send it again.

Could you please add this feature?

Kind regards

**Comment by ara4n** [comment]
this already exists and works (unless you have enabled the experimental 
rich text editor).

**Comment by floviolleau** [comment]
I already enabled rich text editor and it does not work.

With up and down arrows?

**Comment by ara4n** [comment]
dup https://github.com/vector-im/vector-web/issues/2127
