### ISSUE TITLE
500$ to install and configurate vector-web on my website

### ISSUE THREAD

**Issue by PegasusGo** [vector-im/vector-web#2651]
Hello

I need you help : I need someone who can install and configure vector-web on my website. Im using PHP & MySQL

Please contact me if you're interessed : bernardybernardy@gmail.com
https://www.upwork.com/jobs/~01634ae2b6e69aead2

Thanks

**Comment by uhoreg** [comment]
This isn't really the right place for technical support questions.  In any event, if you want to install your own instance of vector-web, just follow the instructions at https://github.com/vector-im/vector-web#getting-started.  vector-web is just a static web page, so it doesn't need PHP or MySQL.

You should note, though, that running your own instance of vector-web may not be all that useful if you don't also run your own homeserver, which you can do by installing [synapse](https://github.com/matrix-org/synapse/).  However, synapse requires Python and PostgreSQL, so you won't be able to run it if you just have PHP and MySQL.

If you have any further questions, please ask them in the [#riot:matrix.org room](https://riot.im/app/#/room/#riot:matrix.org).

**Comment by ara4n** [comment]
yup, this isn't a bug in vector-web, so we can't help here - sorry! suggest asking in #jobs:matrix.org.
