### ISSUE TITLE
Allow changing power levels that equal your own (as long as they're not related to other users)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#29]
Settings UI doesn't let creator change the event settings thresholds?
    ...and the settings UI doesn't let the creator change the event setting thresholds?
    <Erik> Yeah, that looks like a simple bug vector should let you change power levels that equal your own (as long as they're not related to other users)

**Comment by Kegsay** [comment]
```
<M-matthew> ignore it as vector's power settings are changing etirely
```
