### ISSUE TITLE
Gracefully disable VoIP/Video on browsers with insufficient WebRTC

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#291]
So:
 * Don't show inbound call ringing
 * Don't let users place calls or conferences - show the buttons but give an error dialog saying "unsupported" when the user tries.
 * Show ongoing conferences but say "but your browser doesn't support joining"
 * Show call records but say "(not supported by this browser)"

**Comment by ara4n** [comment]
related to #67

**Comment by Kegsay** [comment]
Fixed.
