### ISSUE TITLE
Display names and avatars are not always accurate.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#312]
There are several edge cases where we see stale avatars and display names for users, possibly with missing 'name changed' events shown in the timeline.  For instance:

@joonas:tesla.haapa.la joined the room.
Matthew (@matthew:matrix.org) joonas: welcome
Jontte hi

At what point did @joonas become Jontte?

Also, "Foo changed their avatar" shows the old avatar, not the new one, which is very confusing.

I think there are a few other scenarios where we show MXIDs when we should show display names, or show the wrong avatar, etc.

**Comment by Kegsay** [comment]
Having difficulties reproducing this...

**Comment by ara4n** [comment]
This is a federation bug - closing and moving to https://matrix.org/jira/browse/SYN-546

**Comment by ara4n** [comment]
Here's another instance of it weirdly breaking - how come we got it right at first, but then it broke?  This looks like more than a federation bug; reopening at lower priority.

<img width="972" alt="screen shot 2015-12-20 at 16 30 37" src="https://cloud.githubusercontent.com/assets/1294269/11918794/850bccfa-a737-11e5-837e-31da36124b21.png">

**Comment by ara4n** [comment]
It seems that the 'sentinels' in the js-sdk that are meant to cache and guard member profile data just get overwritten by new state events as they arrive on /sync - so that if synapse doesn't include the correct displayname/avatar_url fields in the content of the event, we simply don't display it.

@erikjohnston - why would federated users be missing their avatar & displayname?

**Comment by ara4n** [comment]
actually, I think this was probably fixed by https://github.com/matrix-org/matrix-js-sdk/pull/108.  Let's reopen if we see it again.
