### ISSUE TITLE
"Registration failed!" errors are utterly cryptic when registration fails

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#318]
Trying to register without an email address, or an email address which already exists, just blindly says "Registration failed!"

**Comment by ara4n** [comment]
in this instance, the actual error cause is that registration had been disabled on the server...

**Comment by ara4n** [comment]
...and if you try to register without an email address, you apparently get an NPE on flow in:

	    firstUncompletedStageIndex: function firstUncompletedStageIndex(flow) {
	        if (this.completedStages === undefined) return 0;
	        for (var i = 0; i < flow.stages.length; ++i) {
	            if (this.completedStages.indexOf(flow.stages[i]) == -1) {
	                return i;
	            }
	        }
	    },

**Comment by Kegsay** [comment]
Fixed now that the registration refactor branch has landed.
