### ISSUE TITLE
Default CSS-animation based spinner chews 100% CPU

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#329]
I can't find the original bug for this for some reason, and I thought @kegsay had fixed this.  But in practice, the spinner shown at launch and elsewhere is still a stupid CSS animation that chews all the CPU it can get to render as fast as possible.

**Comment by Kegsay** [comment]
I only added a gif spinner for my one thing to fix a bug (start chat iirc). I wanted to do the big switch in another PR to avoid blocking p1 bugs.

**Comment by ara4n** [comment]
sorry, i couldn't stand it any longer - fixed in 68c1ddd5d21d19fe699d70eee8b4936162e5ad60 and matrix-react-sdk 02ad2b515202781879db2b86dde5f6e6cb7321fb
