### ISSUE TITLE
Why are MemberAvatar and RoomAvatar different?

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#347]
There's such an overlap between these, should they not be the same atom?

**Comment by Kegsay** [comment]
I'd have thought it'd make sense just for it to accept a prop saying "load this image" and everything else is the same?

**Comment by ara4n** [comment]
This is already causing maintenance problems (dave fixed an a11y bug on MemberAvatar but forgot RoomAvatar, etc)

**Comment by Kegsay** [comment]
This is done and merged.
