### ISSUE TITLE
Support for registering without an email address

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#350]
Originally we said that vector users must enter an email address.  This is fine for the vector.im use case, but when running vector against a different HS it's quite possible that powerusers may want to break their dependency on the IS and register sans email address (e.g. when using CAS etc).

I assume this means adding m.login.password into the register controller?  Are there any gotchas with doing so?

**Comment by ara4n** [comment]
Apparently Vector was always meant to support registering without email addresses, so this is a regression.

**Comment by Kegsay** [comment]
Done in the registration refactor.
