### ISSUE TITLE
wldhx reports FF 44.0a2 failing to sync on Linux

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#412]
I can't reproduce on OSX though.  JS console logs as per:

http://pastebin.com/UADpdzFx
http://pastebin.com/CmETUvt2

Is a loop of

MatrixClient sync state => ERROR bundle.js:136:629
MatrixClient sync state => SYNCING bundle.js:136:629
/events error: {"cors":"rejected"} bundle.js:90:20191

**Comment by ara4n** [comment]
Apparently the pastebins expire, so:

    MatrixClient sync state => ERROR bundle.js:136:629
    MatrixClient sync state => SYNCING bundle.js:136:629
    /events error: {"cors":"rejected"} bundle.js:90:20191
     
    MatrixClient sync state => ERROR bundle.js:136:629
    MatrixClient sync state => SYNCING bundle.js:136:629
    /events error: {"cors":"rejected"} bundle.js:90:20191
     
    MatrixClient sync state => ERROR bundle.js:136:629
    MatrixClient sync state => SYNCING bundle.js:136:629
    /events error: {"cors":"rejected"} bundle.js:90:20191
     
    MatrixClient sync state => ERROR bundle.js:136:629
    MatrixClient sync state => SYNCING bundle.js:136:629
    /events error: {"cors":"rejected"} bundle.js:90:20191

and

    17:11:11.654 /events error: {"cors":"rejected"}1 bundle.js:90:20191
    h/<() bundle.js:90
    o() bundle.js:66
    g.prototype.then/</<() bundle.js:66
    k/t<.when() bundle.js:66
    g/r.promiseDispatch() bundle.js:66
    e/</<() bundle.js:66
    r() bundle.js:66
    e() bundle.js:66
    t.setImmediate</<() bundle.js:1
    o.prototype.run() bundle.js:1
    r() bundle.js:1
    (Async: setTimeout handler) a.nextTick() bundle.js:1
    t.setImmediate<() bundle.js:1
    Y</Y.runAfter() bundle.js:66
    C() bundle.js:66
    k() bundle.js:66
    h/o.reject() bundle.js:66
    i/<() bundle.js:40
    o() bundle.js:92
    r() bundle.js:91
    (Async: EventHandlerNonNull) t() bundle.js:92
    e() bundle.js:91
    e.exports.MatrixHttpApi.prototype._request() bundle.js:40
    e.exports.MatrixHttpApi.prototype.requestWithPrefix() bundle.js:40
    e.exports.MatrixHttpApi.prototype.request() bundle.js:40
    e.exports.MatrixHttpApi.prototype.authedRequest() bundle.js:40
    h() bundle.js:90
    h/<() bundle.js:90
    r() bundle.js:66
    g.prototype.then/</<() bundle.js:66
    g/r.promiseDispatch() bundle.js:66
    e/</<() bundle.js:66
    r() bundle.js:66
    e() bundle.js:66
    t.setImmediate</<() bundle.js:1
    o.prototype.run() bundle.js:1
    r() bundle.js:1
    (Async: setTimeout handler) a.nextTick() bundle.js:1
    t.setImmediate<() bundle.js:1
    Y</Y() bundle.js:66
    e/<() bundle.js:66
    e/<() bundle.js:66
    e() bundle.js:66
    h/o.resolve() bundle.js:66
    i/<() bundle.js:40
    l() bundle.js:92
    r() bundle.js:91
    (Async: EventHandlerNonNull) t() bundle.js:92
    e() bundle.js:91
    e.exports.MatrixHttpApi.prototype._request() bundle.js:40
    e.exports.MatrixHttpApi.prototype.requestWithPrefix() bundle.js:40
    e.exports.MatrixHttpApi.prototype.request() bundle.js:40
    e.exports.MatrixHttpApi.prototype.authedRequest() bundle.js:40
    h() bundle.js:90
    h/<() bundle.js:90
    r() bundle.js:66
    g.prototype.then/</<() bundle.js:66
    g/r.promiseDispatch() bundle.js:66
    e/</<() bundle.js:66
    r() bundle.js:66
    e() bundle.js:66
    t.setImmediate</<() bundle.js:1
    o.prototype.run() bundle.js:1
    r() bundle.js:1
    (Async: setTimeout handler) a.nextTick() bundle.js:1
    t.setImmediate<() bundle.js:1
    Y</Y() bundle.js:66
    e/<() bundle.js:66
    e/<() bundle.js:66
    e() bundle.js:66
    h/o.resolve() bundle.js:66
    i/<() bundle.js:40
    l() bundle.js:92
    r() bundle.js:91
    (Async: EventHandlerNonNull) t() bundle.js:92
    e() bundle.js:91

**Comment by alex-mayorga** [comment]
On Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0 ID:20151122030230 CSet: abbd213422a560f1180c4ec6e3bf4792c2ea81ba this appears on the "Browser Console":
```
/events error: {"cors":"rejected"} bundle.js:90
MatrixClient sync state => ERROR bundle.js:136
Error: CORS request rejected: https://matrix.org/_matrix/client/api/v1/rooms/!DgvjtOljKujDBrxyHk%3Amatrix.org/typing/%40alex_mayorga%3Amatrix.org?access_token=QGFsZXhfbWF6b2JnYTptYXRyaXgub1Jn.AiBrNkFTAnsLugtUfg
```
I tampered with the access token intentionally.

**Comment by ara4n** [comment]
folks, can you reproduce this? 'cos I can't.

**Comment by richvdh** [comment]
I think we should assume this is no longer an issue.
