### ISSUE TITLE
Global settings page re-work

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#42]

**Comment by AmandineLP** [comment]
Notification settings scope for v0:
* Only Unmute preset is configurable in global settings
* Mute is doable on a per room basis from room settings only
* One can enable/disable desktop notifs from global settings
* One can enable/disable ALL notifs from global settings

Notification settings in global settings for v1 - Private Preview: see attached
![vector global settings](https://cloud.githubusercontent.com/assets/8582858/12296491/43ec0440-ba08-11e5-8ba1-85d2c860aef2.JPG)

**Comment by ara4n** [comment]
The basics are there (in the PR).  Will open up a new bug to track all the other stuff remaining on global settings.
