### ISSUE TITLE
trying to back-paginate whilst offline now infinite-loops and chews 100% cpu

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#424]
Ends up with an infinite looping stacktrace looking a bit like:

    GET https://matrix.org/_matrix/client/api/v1/rooms/

    net::ERR_INTERNET_DISCONNECTED

    run_xhr @ index.js:218
    request @ index.js:179
    module.exports.MatrixHttpApi._request @ http-api.js:335
    module.exports.MatrixHttpApi.requestWithPrefix @ http-api.js:296
    module.exports.MatrixHttpApi.request @ http-api.js:234
    module.exports.MatrixHttpApi.authedRequest @ http-api.js:213
    MatrixClient.scrollback @ client.js:1766
    fillSpace @ RoomView.js:306
    componentDidUpdate @ RoomView.js:278
    assign.notifyAll @ CallbackQueue.js:65
    ON_DOM_READY_QUEUEING.close @ ReactReconcileTransaction.js:81
    Mixin.closeAll @ Transaction.js:202
    Mixin.perform @ Transaction.js:149
    Mixin.perform @ Transaction.js:136
    assign.perform @ ReactUpdates.js:86
    flushBatchedUpdates @ ReactUpdates.js:147
    wrapper @ ReactPerf.js:66
    Mixin.closeAll @ Transaction.js:202
    Mixin.perform @ Transaction.js:149
    ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62
    enqueueUpdate @ ReactUpdates.js:176
    enqueueUpdate @ ReactUpdateQueue.js:24
    ReactUpdateQueue.enqueueSetState @ ReactUpdateQueue.js:190
    ReactComponent.setState @ ReactComponent.js:65
    (anonymous function) @ RoomView.js:309
    Promise.apply @ q.js:1165
    Promise.promise.promiseDispatch @ q.js:788
    (anonymous function) @ q.js:1391
    runSingle @ q.js:137
    flush @ q.js:125
    onNextTick @ main.js:64
    Item.run @ browser.js:64
    drainQueue @ browser.js:34
    index.js:218

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/50
