### ISSUE TITLE
vector sends read receipts if you leave the cursor over the window

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-web#427]
Sometimes?

Guess chrome must generate a mouse move event if something happens underneath the cursor (which probably makes sense most of the time I guess).

**Comment by dbkr** [comment]
Seems to be only for the channel you're viewing so this is consistent. We should see if the cursor coordinates have changed.

**Comment by ara4n** [comment]
fixed in matrix-react-sdk ba090a6
