### ISSUE TITLE
Really weird 500ms delay in GeminiScrollbar's componentDidUpdate when switching to #matrix-dev

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#438]
The source map seems desynced - it could also be in componentDidUnmount.  Not seen when switching to other rooms, and happens regardless where you're switching from :/

<img width="1866" alt="screen shot 2015-11-29 at 12 50 40" src="https://cloud.githubusercontent.com/assets/1294269/11457104/1fa3395c-9698-11e5-939a-d0adbed96da6.png">

**Comment by Kegsay** [comment]
So testing this in Chrome 46 and that function takes 10ms to execute. Reliably. As your screenshot suggests, the lions share is taken up by an anonymous function call inside `update()`. There is a call to `_scrollHandler()` but this is accounted for in the graphs and is tiny.

```javascript
GeminiScrollbar.prototype.update = function update() {
        if (DONT_CREATE_GEMINI) {
            return this;
        }

        if (this._created === false) {
            console.warn('calling on a not-yet-created object');
            return this;
        }

        var heightPercentage, widthPercentage;

        this._viewElement.style.width = ((this.element.offsetWidth + SCROLLBAR_WIDTH).toString() + 'px');
        this._viewElement.style.height = ((this.element.offsetHeight + SCROLLBAR_WIDTH).toString() + 'px');

        heightPercentage = (this._viewElement.clientHeight * 100 / this._viewElement.scrollHeight);
        widthPercentage = (this._viewElement.clientWidth * 100 / this._viewElement.scrollWidth);

        this._thumbVerticalElement.style.height = (heightPercentage < 100) ? (heightPercentage + '%') : '';
        this._thumbHorizontalElement.style.width = (widthPercentage < 100) ? (widthPercentage + '%') : '';

        this._scrollHandler();

        return this;
};
```

I suspect the anonymous functions are the calls to assign `style.width` and `style.height` which most likely under-the-hood are done as:

```javascript
Object.defineProperty(this, 'width', {
    set: function (value) {
      // something which is slow here
    },
});
```

If that's true, there isn't much we can do about this to speed up this function as it's beyond our control. We may be able to not block on the scrollbar whilst swapping rooms though, but it looks like this is going to be hard to do as they are *eeeeverywhere* in the view hierarchy (for messages, rooms, member lists, etc). There will always be leakage from when say member lists update at the moment you try to change tabs and they are executed on the event loop first.

**Comment by ara4n** [comment]
I suspect the problem here is indeed that there was some pathological case in the CSS layout - i should have profiled the layout engine; i failed to realise that the JS might be blocked in layout engine.  I can't repro either now, so will close until we see this again (or more likely, it just falls into the overall bucket of speeding up CSS layout by avoiding dynamic layout & flexbox slowness etc).

@kegsay: thanks for digging into it.
