### ISSUE TITLE
Auto markdown converted to blank message

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#439]
When I try and send the text:

> [redacted]: https://github.com/matrix-org/purple-matrix/

The vector.im/beta client generates events of the form:

```json
{
  "origin_server_ts": 1448825055290,
  "user_id": "@erikj:jki.re",
  "event_id": "$1448825055370JDfQA:jki.re",
  "content": {
    "body": "[redacted]: https://github.com/matrix-org/purple-matrix/",
    "msgtype": "m.text",
    "formatted_body": "",
    "format": "org.matrix.custom.html"
  },
  "room_id": "!cURbafjkfsMDVwdRDQ:matrix.org",
  "type": "m.room.message",
  "age": 1638
}
```

This is unfortunate since half the clients will see the correct message, the other half will see the blank messages, depending on whether they support HTML formatting or not.

There were no errors in the JS console.

**Comment by ara4n** [comment]
This is because square-bracketed-term-followed-by-colon-followed-by-something in github flavoured markdown apparently causes it to mysteriously disappear.  Perhaps it's defining an anchor or something. An example follows here (and should be invisible): [redacted]:foo

**Comment by ara4n** [comment]
@silviof says:
`M-matthew: This is a reference to a link following later in the text. you [write] a text. then someweher you have a [write]:http://... for the real link`

**Comment by ara4n** [comment]
i think the moral of the story here is that we should make markdown a little button of some flavour to opt-in. unsure precisely what the UX should be; suggestions welcome.

**Comment by ara4n** [comment]
Going to close this in favour of #483.
