### ISSUE TITLE
undefined tag request

### ISSUE THREAD

**Issue by manuroe** [vector-im/vector-web#444]
If you move a room from "conversations" to the last position of the "favourites" section, the app makes a request to tag the room with "undefined":
https://matrix.org/_matrix/client/v2_alpha/user/%40Manu%3Amatrix.org/rooms/!GzvmKcFNOiOmXzAQgi%3Amatrix.org/tags/undefined?access_token=...

**Comment by ara4n** [comment]
The request is a DELETE, no?  So it's just trying to delete the previous 
non-existent tag on the untagged room?

**Comment by ara4n** [comment]
Hopefully fixed in 4409f07 - @manuroe can you confirm this is the bad behaviour you were seeing?

**Comment by manuroe** [comment]
Yes, this is a DELETE request.
