### ISSUE TITLE
Very strange scrollbars after plugging laptop back in after weekend

### ISSUE THREAD

**Issue by dbkr** [vector-im/vector-web#476]
Presumably some combination of plugging in and unplugging a mouse has caused gemini scrollbar to get very confused.

<img width="250" alt="screen shot 2015-12-07 at 11 06 38" src="https://cloud.githubusercontent.com/assets/986903/11625417/caa661ae-9cd2-11e5-818d-116a07cd1af1.png">

**Comment by ara4n** [comment]
gemini only recalculates its layout when you manually prod it to. i guess we'll need to find an onResize event of some kind that fires when the browser toggles the mouse...

**Comment by ara4n** [comment]
@richvdh saw something vaguely similar to this on linux after zooming way out in Chrome with ctrl minus'.  Interestingly it didn't fix itself after resizing the window, but did after refreshing the whole app. In his instance the real scrollbars were just about visible at the perimeter.

**Comment by ara4n** [comment]
i /think/ vdh's new gemini stuff should fix this.
