### ISSUE TITLE
Require a room alias when creating a public room

### ISSUE THREAD

**Issue by IvanSanchez** [vector-im/vector-web#484]
Right now, when creating a public room, the room alias is not required by default. This can lead to a user (i.e. me) to create a public room that doesn't appear in the list of public rooms, which leads to confusion. This is reproducible by creating a public room with just the room name.

Also, there is no (obvious, labelled) way to set the room alias from the room options.

**Comment by ara4n** [comment]
This will be fixed in new settings UI across the board.

**Comment by ara4n** [comment]
killing create_room page nukes this entirely.
