### ISSUE TITLE
Double date separator in #test:matrix.org

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#493]
<img width="1090" alt="screen shot 2015-12-11 at 00 03 25" src="https://cloud.githubusercontent.com/assets/1294269/11732294/aeb0c758-9f9a-11e5-9b73-757af2690822.png">

**Comment by richvdh** [comment]
Looking at this in relation to #431. I can't see the scrollback in question. Is it possible that the events in question are actually from different Mondays?

**Comment by ara4n** [comment]
Ah, I guess you don't have scrollback visibility :/  I just backpaginated a bit and found it fine by searching for centx, and it's still comically broken.  You can borrow my @matthew2:matrix.org account to test if you like, which has access to #test with sufficient scrollback.

<img width="996" alt="screen shot 2015-12-21 at 10 53 50" src="https://cloud.githubusercontent.com/assets/1294269/11929230/376c8c24-a7d1-11e5-8e2f-41cb1ad89370.png">

**Comment by richvdh** [comment]
Thanks. The problem here is that there are some delayed events in the timeline, between '@centx joined' and Erik's '> w I thi', which are not being shown, because they are m.room.member events which have no visible effect.

https://github.com/matrix-org/matrix-react-sdk/pull/64 fixes this as well.

**Comment by richvdh** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/64
