### ISSUE TITLE
Desktop notifs for invites to private 1:1 leak room IDs

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#494]

**Comment by ara4n** [comment]
This looks very related to #321.

**Comment by Kegsay** [comment]
I can't reproduce this. Can you give me some repro steps?

**Comment by ara4n** [comment]
To repro, I have two Chromes. One's logged in as @matthew:matrix.org; the other's incognito logged in as @matthew2:matrix.org.  The first one is in #test:matrix.org and types /invite @matthew2:matrix.org.  The second one receives a desktop notif with !vf3y7845y7824r or whatever as the label.

**Comment by ara4n** [comment]
oh, hang on, wrong bug; one second...

**Comment by ara4n** [comment]
Take 2: same setup, but @matthew:matrix.org invites @matthew2:matrix.org to a private room by hitting Create New Room, leaving as private (default), adding @matthew2:matrix.org as a user.  Result as shown below:

<img width="394" alt="screen shot 2015-12-14 at 16 48 33" src="https://cloud.githubusercontent.com/assets/1294269/11787283/c684b1ce-a282-11e5-9e7a-a16a6494c4f2.png">

**Comment by ara4n** [comment]
(also, surely these should show display names, not fugly user IDs?)

**Comment by Kegsay** [comment]
Thanks for the repro steps. I'm so confused. I'm *not getting* any desktop notifications for invites, even though I do when pinged and when spoken to in a 1:1 room. Looks like that will need to be fixed before I can dig into this further....

**Comment by Kegsay** [comment]
I don't believe this is blocked on anything.

**Comment by ara4n** [comment]
Presumably this is just because we have different push rules?

**Comment by Kegsay** [comment]
https://github.com/matrix-org/matrix-js-sdk/commit/77356f0007567c057e90bbff89cfadc65f206a33
