### ISSUE TITLE
New invites sometimes don't appear in the recents list without a refresh

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#5]
I saw this a few times, but it hasn't reproduced recently.

**Comment by ara4n** [comment]
This could be related to: "If I have two invites from the same person, it seems that one of them isn't shown in the room list."

**Comment by dbkr** [comment]
I can't reproduce this - reopen if it's still a problem.

**Comment by ara4n** [comment]
I see this almost every time someone invites me.  Can you (temporarily) steal my accesstoken and try to reproduce please?

**Comment by dbkr** [comment]
The only difference I can see is that when you refresh the page, the new invite ends up at the top of the list, where before some older invites were on top. Is it just this causing it to blend in with the rest until you refresh the page?

**Comment by ara4n** [comment]
nope. the invites are nowhere to be seen - either at top, middle or bottom. should be reproable trivially on my account.

**Comment by dbkr** [comment]
If I log in to your account, create a new room in a different account and invite you, the invite appears somewhere muddled up with the other invites. I've tried with public and private rooms, sharing history and not.

**Comment by ara4n** [comment]
I just reproduced this - David K invited me to a room called 'David & Katie'.  Nothing showed up in the invites - but I did catch a:

Uncaught TypeError: Cannot read property 'userId' of null
bundle.js:68 Presence: online

on the console (unhelpfully).  This was on a vector-web master.

**Comment by dbkr** [comment]
Ah, I bet this will be something assuming the user field of a member object exists

**Comment by ara4n** [comment]
am now on canary; tried reproing a few times but it seemed to be okay. will wait for it to fail next time...

**Comment by ara4n** [comment]
vdH just reproduced this:
<img width="337" alt="screen shot 2015-10-19 at 12 45 35" src="https://cloud.githubusercontent.com/assets/1294269/10576976/5668cdca-765f-11e5-8fd1-1d529c3a7522.png"> as part of bug #215
