### ISSUE TITLE
User popover UX inconsistencies

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/vector-web#504]
![screen shot 2015-12-11 at 7 58 37 pm](https://cloud.githubusercontent.com/assets/1923178/11759087/e674e032-a041-11e5-8afd-5130b2281316.png)

There are a few weird things about the popovers shown when clicking on a user's MXID:

- The popover can scroll off the screen
- Too much spacing over avatar
- The "X" button is not right-justified
- The "X" button does not close the popover (must click outside the popover)

**Comment by ara4n** [comment]
these shouldn't happen at all - it's a bug :) dup #411
