### ISSUE TITLE
Make invite UI match the designs.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#509]

**Comment by ara4n** [comment]
Specifically, it needs to try to autocomplete users from an addressbook.  As a first cut, this addressbook can simply be all the uses the client currently knows about (i.e. it saw in its initialsync).

**Comment by ara4n** [comment]
In future it would need to be a serverside "please let me search all publically visible users on the server" API.

**Comment by AmandineLP** [comment]
Not a blocker for the friendly beta IMO

**Comment by Kegsay** [comment]
Braindumping IRL:
 - The idea is to have the same layout as today, input box at top, member list in middle with invited list at bottom (within the same scroll area as the member list)
 - Input box hint should be "Invite / Search"
 - Typing into this box should create a new list directly below the input box, which occupies ~40% of the height (like Zeplin). This view should be scrollable and has the results of the search. It should search globally across all `m.presence` events (`User` objects). If the user:
    - Is not in the room: Display a + (like Zeplin) and clicking it will immediately invite that user (no prompt / confirmation dialog)
    - Is in the room: Do not display the +. Clicking it takes you to the RHS Member Info screen and dismisses the search.

**Comment by Kegsay** [comment]
This is mostly done now modulo sizing/CSS and searching presence events (with + invite for non-joined members).

**Comment by Kegsay** [comment]
Right, we now search presence events and display them correctly, just need layout/CSS and the + invite for non-joined members.

**Comment by Kegsay** [comment]
This is done now modulo CSS. This searches *everywhere* as of today.

**Comment by ara4n** [comment]
this happened.
