### ISSUE TITLE
Apparently username validation fails at signup (or invite?) and allows spaces(?)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#512]

**Comment by Kegsay** [comment]
I suspect this is at invite stage. Synapse really should validate the stuff clients pass it... I am unconvinced that this is something Vector specifically should fix (other than providing an immediate fonx).

**Comment by ara4n** [comment]
Absolutely agreed we need serverside validation, but we also need clientside validation.

**Comment by ara4n** [comment]
Complicated by spec-1 still being open.  For now, let's mandate that uri_encode(username) === username

**Comment by ara4n** [comment]
...and no colons!

**Comment by dbkr** [comment]
Do we actually need client side validation or would it be enough in this case to actually display the right error when the server rejects us?

**Comment by ara4n** [comment]
happy to let the server validate for now, although please drop prio rather than close.

**Comment by dbkr** [comment]
OK
