### ISSUE TITLE
Change favicon and change/flash title for notifications

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/vector-web#519]
Changing the favicon would make it more obvious when you receive a highlight or other notification - without this, notifications aren't noticeable once the desktop notification goes off-screen. Also, browsers typically seem to treat title changes as notifications for pinned tabs, so changing the title on a notification (to add the number of unread messages, for example) would make it obvious that something has notified you.

I'd imagine some users may not like this, so having the option to disable each would be worthwhile.

Goes along well with #167

**Comment by ara4n** [comment]
This is basically a dup of #281, which @dbkr was working on earlier today :)  We support both tracking missed notifs as well as missed unread msgs.
