### ISSUE TITLE
Message went entirely missing from the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#530]
Sent a message with ID $14502871052582LsFeY:matrix.org into Matrix Internal from @matthew2:matrix.org.  I /think/ that it appeared in grey briefly and then disappeared entirely from the timeline.  It was relayed fine to other users.  The /sync returned in the network view (with the right transaction ID) on Chrome before the /send completed.

**Comment by Kegsay** [comment]
Fixed, thanks!
