### ISSUE TITLE
After joining a room from an invite, your own avatar can go missing.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#539]
See screenshot.
<img width="1202" alt="screen shot 2015-12-17 at 23 28 19" src="https://cloud.githubusercontent.com/assets/1294269/11885049/f83dc1e8-a515-11e5-9165-aff42b96ee00.png">

**Comment by Kegsay** [comment]
Fixed in https://github.com/matrix-org/matrix-js-sdk/commit/e8f77256de3d1b37a40d6cf43c2232f4041d0c3e
