### ISSUE TITLE
Broken Login for LAN

### ISSUE THREAD

**Issue by Caerdwyn** [vector-im/vector-web#563]
Using the custom server option in Vector, I would expect it can connect to other local LAN servers. This used to be the case with other versions of Vector; not anymore. Using either http/https does not work, and defining either the machine's hostname or IP address does not work. When finished typing/clicking out of the text box, the little animated wheel spins to indicate it's trying to connect, and nothing ever happens; or most of the time, I get "Error Communicating with the Homeserver" in red.

**Comment by Kegsay** [comment]
Can you put the contents of your network tab please? I'm primarily interested in the URLs being hit and the response codes/body. It sounds like the request is timing out.

**Comment by Caerdwyn** [comment]
I don't understand what you mean by network tab, but I do know that Vector
can access my homeserver over LAN with a hairpin NAT route, my domain name,
accessed from within LAN.

**Comment by Caerdwyn** [comment]
Referencing #575 here because I think this may have something to do with it.

**Comment by ara4n** [comment]
@Caerdwyn is this still happening?

**Comment by Caerdwyn** [comment]
#575 Explains it pretty well. For the time being, I believe it was purely the self-signed certs throwing it off, though non-SSL HTTP connections are still not working. Since getting a properly signed SSL cert for my server, it has been working fine. 

Closing because I think we've discussed it at length enough on Matrix, @ara4n.
