### ISSUE TITLE
Rich text input

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#572]
It would be great to have the ability to inline formatted text when inputting it in future - using some kind of TinyMCE style rich-text editor.

This would also have the advantage of being able to dynamically highlight autocompleted terms and other nice eye-candy rather than just being a plain textarea.

**Comment by aviraldg** [comment]
[Draft.js](https://facebook.github.io/draft-js/) looks like a decent option for this - it's used by Facebook, meant for React, and is lightweight and flexible.

I recommend having two editor modes (configurable from the settings), one in which Markdown is used to style, and another in which shortcuts like C-b, C-i are used to style text. Emoji to image conversion will be supported in both.

**Comment by ara4n** [comment]
Draft.js is new to me, but looks very cool. Agreed that full RTE and markdown editors is good, although i would switch between them within the editor itself rather than go via Settings. Slightly worried that Draft may be much heavier than a textarea, in which case we may want to keep the markdown editor as a textarea complete with utf8 emoji. If Draft isn't that heavy then I totally agree that we should replace the textarea entirely with a markdown and full-rich one (probably defaulting to full-rich for ease of UX), so as to pull in canonical emoji.

This looks very cool - are you planning to work on it?

**Comment by aviraldg** [comment]
I'm working on this, and here's a very basic version:

![vector](https://cloud.githubusercontent.com/assets/238916/14582424/3597d14e-0422-11e6-8125-6a6cd27a8a44.png)

**Comment by eternaleye** [comment]
Copied from [#vector:matrix.org](https://vector.im/develop/#/room/!DgvjtOljKujDBrxyHk:matrix.org/$1460832357108857jBrwY:matrix.org):

> Hovering selection is not very discoverable at all, though - if someone doesn't know it does RTE, there's basically no reason to ever hilight.

> Personally, I think that the best hybrid is

> 1. If user types markdown, show live-preview above edit line and offer "MD Disable" button
> 2. If user does not, show "RTE Toolbar" button
> 3. Hover selected as alternative interaction pattern
> 4. Control-key works both as "stateful toggle" in cursor mode and "toggle for selection" in selection mode.

> Still one corner case, of if they use RTE and then type some markdown - should it convert the RTE to markdown, or should it assume they did not intend markdown and ignore it?

**Comment by ara4n** [comment]
I basically agree with @aviraldg eternaleye's suggestion, other than the idea of doing a live preview of MD in the status bar - the status bar is there for autocomplete and other stuff.  If the user wants to preview their MD, I suggest they should switch into RTE mode and do it WYSIWYG.

The discussion of where the actual formatting UI control should go is intimately linked to https://github.com/vector-im/vector-web/issues/483 (which debates how to toggle MD on & off for a given message).

My suggestion for semantics would be:
 a) Initially, no formatting button is shown.
 b) When the user starts typing, their input is interpreted as plain unformatted text and the editor acts in RTE WYSIWYG mode.  The formatting button is made visible, and clicking on it provides a contextual menu for selecting bold/italics/underline/etc - or the option to switch to markdown.
 c) If the user switches to markdown, the RTE message (including formatting) is replaced with the MD equivalent, and the experience degrades to the experience they have today.  The formatting button is updated somehow to show that they are in MD mode.
 d) Switching from MD to RTE switches the plain-text MD sourcecode into a WYSIWYG RTE representation of the same.
 e) Hover-over formatting menu for selections could be nice to have, but might be a bit too busy (especially when trying to manipulate the selection normally with the cursor).  A context menu RTE/MD button might be good enough.

In terms of the button itself, I think my preference would be to put it over on the RHS of the text input box, as per @AmandineLP's comments on #483.  With the voice/video buttons combined together in future, this doesn't use up an additional screen real estate than where we're at today.

The button itself could be a formatting or settings icon, with a MD logo overlay when MD mode is enabled, a bit like #483.  The contextual menu that pops up when you click on it would be split into the formatting options at the top of the menu, with the "switch to MD" or "switch to RTE" at the bottom.  The menu items could give keyboard shortcuts for RTE (Ctrl-B, Ctrl-I etc) as well as the synta reference for MD (`**foo**`, `*foo*` etc).

Open to alternatives on any of the above though :)   And @aviraldg - huge thanks for pushing this forwards!

**Comment by eternaleye** [comment]
@ara4n, my idea isn't to use the status bar for preview, but to place the preview in between the status bar and the input line (but only expanding it from zero-height when something has been typed).

While control-key formatting works for some basic cases (bold, underline, italic) more advanced things like links require mouse interaction - being able to just type, while still seeing that my message is formatted sensibly, is a much smoother workflow IMO. (The number of times I've done a markdown link and failed to properly close the parentheses the first time, or done a markdown numbered list and forgotten that without a blank line the following text gets jammed on the list, or the same with markdown quotes, or...)

I do agree with the rest of your workflow described, though I'd add that I think the MD/RTE switch should be "sticky" (via LocalStorage?), and that entering MD should enable the preview I described.

I definitely like the mode-switching button, as if other formats are added in the future, it extends naturally.

**Comment by aviraldg** [comment]
One option that I had in mind was to preview markdown such that it looks
like an unsent message (greyed out and at the bottom of the message list)

In other news, I'm afraid I'll be out of action for quite a bit: an entire
row of keys on my laptop's keyboard is busted. :(

**Comment by eternaleye** [comment]
Hm, previewing as an unsent message is a really neat option - I like it! The main trick will be making it clear it's a preview; perhaps giving it a subtle background hue.

**Comment by aviraldg** [comment]
Implemented in matrix-org/matrix-react-sdk#292
