### ISSUE TITLE
Self-signed SSL Certificates break Vector's ability to use custom homservers

### ISSUE THREAD

**Issue by Caerdwyn** [vector-im/vector-web#575]
Connecting to a homeserver that uses a self-signed SSL certificate or is otherwise "untrusted", causes Vector to immediately hang on connect with `Error: Unable to communicate with the homeserver`. 

Changing the homeserver's connection to http, :8008, yields somewhat better results, but causes Google Chrome users to have to accept a separate popup by clicking on the ![Shield in the address bar](http://i.imgur.com/2TXy82R.png) in the address bar, then clicking *Load Unsafe Scripts*. Only then will the page refresh and allow you to connect.

**Comment by Caerdwyn** [comment]
#563 and this go hand in hand, closing this because it's an SSL cert issue, not necessarily a bug in Vector. It seems to be Chrome having the issue.

**Comment by ara4n** [comment]
this is actually another facet of #898, and we can and should warn better.
