### ISSUE TITLE
Displayname changes are being shown as duplicate joins

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#588]
qnm is 'Rob Sharp', digibot is 'Digi Bot'; their duplicate joins seem to be camouflaging displayname changes in #test.
<img width="995" alt="screen shot 2016-01-06 at 01 42 33" src="https://cloud.githubusercontent.com/assets/1294269/12132751/e6d9f682-b416-11e5-9f0b-c8317ed8363c.png">

**Comment by Kegsay** [comment]
Fixed in https://github.com/matrix-org/matrix-js-sdk/commit/51fe73bc2707c0ba77f1cc8b5665719edc65cc12 - `getPrevContent()` is used to calculate what changed, and that was returning `undefined` due to v2 event formats.
