### ISSUE TITLE
Opening vector.im in IE displays a blank page

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#593]
Opening vector.im in IE redirects to vector.im/beta but displays a blank page.
IE version:
     Version: 11.0.9600.17041
     Update Version: 11.0.7 (KB2929437)

Error:
SCRIPT1003: Expected ':'
File: bundle.js, Line: 39, Column: 606

Line 39:
!function(){"use strict";function n(){for(var e="",t=0;t<arguments.length;t++){var r=arguments[t];if(r){var i=typeof r;if("string"===i||"number"===i)e+=" "+r;else if(Array.isArray(r))e+=" "+n.apply(null,r);else if("object"===i)for(var a in r)o.call(r,a)&&r[a]&&(e+=" "+a)}}return e.substr(1)}var o={}.hasOwnProperty;"undefined"!=typeof e&&e.exports?e.exports=n:(r=[],i=function(){return n}.apply(t,r),!(void 0!==i&&(e.exports=i)))}()},function(e,t,n){function r(t,n){return delete e.exports[t],e.exports[t]=n,n}var i=n(152),o=n(449);e.exports={Parser:i,Tokenizer:n(153),ElementType:n(45),DomHandler:o,get FeedHandler(){return r("FeedHandler",n(446))},get Stream(){return r("Stream",n(448))},get WritableStream(){return r("WritableStream",n(154))},get ProxyHandler(){return r("ProxyHandler",n(447))},get DomUtils(){return r("DomUtils",n(451))},get CollectingHandler(){return r("CollectingHandler",n(445))},DefaultHandler:o,get RssHandler(){return r("RssHandler",this.FeedHandler)},parseDOM:function(e,t){var n=new o(t);return new i(n,t).end(e),n.dom},parseFeed:function(t,n){var r=new e.exports.FeedHandler(n);return new i(r,n).end(t),r.dom},createDomStream:function(e,t,n){var r=new o(e,t,n);return new i(r,t)},EVENTS:{attribute:2,cdatastart:0,cdataend:0,text:1,processinginstruction:2,comment:1,commentend:0,closetag:1,opentag:2,opentagname:1,error:1,end:0}}},function(e,t){e.exports={Text:"text",Directive:"directive",Comment:"comment",Script:"script",Style:"style",Tag:"tag",CDATA:"cdata",Doctype:"doctype",isTag:function(e){return"tag"===e.type||"script"===e.type||"style"===e.type}}},function(e,t,n){function r(e){return null!=e&&o(i(e))}var i=n(536),o=n(63);e.exports=r},function(e,t,n){"use strict";var r=n(179),i=n(607),o=n(191),a=n(200),s=n(201),l=n(3),c=(n(6),{}),u=null,d=function(e,t){e&&(i.executeDispatchesInOrder(e,t),e.isPersistent()||e.constructor.release(e))},p=function(e){return d(e,!0)},m=function(e){return d(e,!1)},h=null,f={injection:{injectMount:i.injection.injectMount,injectInstanceHandle:function(e){h=e},getInstanceHandle:function(){return h},injectEventPluginOrder:r.injectEventPluginOrder,injectEventPluginsByName:r.injectEventPluginsByName},eventNameDispatchConfigs:r.eventNameDispatchConfigs,registrationNameModules:r.registrationNameModules,putListener:function(e,t,n){"function"!=typeof n?l(!1):void 0;var i=c[t]||(c[t]={});i[e]=n;var o=r.registrationNameModules[t];o&&o.didPutListener&&o.didPutListener(e,t,n)},getListener:function(e,t){var n=c[t];return n&&n[e]},deleteListener:function(e,t){var n=r.registrationNameModules[t];n&&n.willDeleteListener&&n.willDeleteListener(e,t);var i=c[t];i&&delete i[e]},deleteAllListeners:function(e){for(var t in c)if(c[t][e]){var n=r.registrationNameModules[t];n&&n.willDeleteListener&&n.willDeleteListener(e,t),delete c[t][e]}},extractEvents:function(e,t,n,i,o){for(var s,l=r.plugins,c=0;c<l.length;c++){var u=l[c];if(u){var d=u.extractEvents(e,t,n,i,o);d&&(s=a(s,d))}}return s},enqueueEvents:function(e){e&&(u=a(u,e))},processEventQueue:function(e){var t=u;u=null,e?s(t,p):s(t,m),u?l(!1):void 0,o.rethrowCaughtError()},__purge:function(){c={}},__getListenerBank:function(){return c}};e.exports=f},function(e,t,n){"use strict";function r(e,t,n){var r=t.dispatchConfig.phasedRegistrationNames[n];return _(e,r)}function i(e,t,n){var i=t?v.bubbled:v.captured,o=r(e,n,i);o&&(n._dispatchListeners=f(n._dispatchListeners,o),n._dispatchIDs=f(n._dispatchIDs,e))}function o(e){e&&e.dispatchConfig.phasedRegistrationNames&&h.injection.getInstanceHandle().traverseTwoPhase(e.dispatchMarker,i,e)}function a(e){e&&e.dispatchConfig.phasedRegistrationNames&&h.injection.getInstanceHandle().traverseTwoPhaseSkipTarget(e.dispatchMarker,i,e)}function s(e,t,n){if(n&&n.dispatchConfig.registrationName){var r=n.dispatchConfig.registrationName,i=_(e,r);i&&(n._dispatchListeners=f(n._dispatchListeners,i),n._dispatchIDs=f(n._dispatchIDs,e))}}function l(e){e&&e.dispatchConfig.registrationName&&s(e.dispatchMarker,null,e)}function c(e){g(e,o)}function u(e){g(e,a)}function d(e,t,n,r){h.injection.getInstanceHandle().traverseEnterLeave(n,r,s,e,t)}function p(e){g(e,l)}var m=n(21),h=n(47),f=(n(6),n(200)),g=n(201),v=m.PropagationPhases,_=h.getListener,b={accumulateTwoPhaseDispatches:c,accumulateTwoPhaseDispatchesSkipTarget:u,accumulateDirectDispatches:p,accumulateEnterLeaveDispatches:d};e.exports=b},function(e,t){"use strict";var n={remove:function(e){e._reactInternalInstance=void 0},get:function(e){return e._reactInternalInstance},has:function(e){return void 0!==e._reactInternalInstance},set:function(e,t){e._reactInternalInstance=t}};e.exports=n},function(e,t,n){"use strict";function r(e,t,n,r){i.call(this,e,t,n,r)}var i=n(29),o=n(113),a={view:function(e){if(e.view)return e.view;var t=o(e);if(null!=t&&t.window===t)return t;var n=t.ownerDocument;return n?n.defaultView||n.parentWindow:window},detail:function(e){return e.detail||0}};i.augmentClass(r,a),e.exports=r},function(e,t,n){"use strict";var r={};e.exports=r},function(e,t,n){(function(e){function n(e){return Array.isArray?Array.isArray(e):"[object Array]"===g(e)}function r(e){return"boolean"==typeof e}function i(e){return null===e}function o(e){return null==e}function a(e){return"number"==typeof e}function s(e){return"string"==typeof e}function l(e){return"symbol"==typeof e}function c(e){return void 0===e}function u(e){return"[object RegExp]"===g(e)}function d(e){return"object"==typeof e&&null!==e}function p(e){return"[object Date]"===g(e)}function m(e){return"[object Error]"===g(e)||e instanceof Error}function h(e){return"function"==typeof e}function f(e){return null===e||"boolean"==typeof e||"number"==typeof e||"string"==typeof e||"symbol"==typeof e||"undefined"==typeof e}function g(e){return Object.prototype.toString.call(e)}t.isArray=n,t.isBoolean=r,t.isNull=i,t.isNullOrUndefined=o,t.isNumber=a,t.isString=s,t.isSymbol=l,t.isUndefined=c,t.isRegExp=u,t.isObject=d,t.isDate=p,t.isError=m,t.isFunction=h,t.isPrimitive=f,t.isBuffer=e.isBuffer}).call(t,n(41).Buffer)},function(e,t){"function"==typeof Object.create?e.exports=function(e,t){e.super_=t,e.prototype=Object.create(t.prototype,{constructor:{value:e,enumerable:!1,writable:!0,configurable:!0}})}:e.exports=function(e,t){e.super_=t;var n=function(){};n.prototype=t.prototype,e.prototype=new n,e.prototype.constructor=e}},function(e,t,n){var r=n(11);e.exports={getHttpUriForMxc:function(e,t,n,i,o,a){if("string"!=typeof t||!t)return"";if(0!==t.indexOf("mxc://"))return a?t:"";var s=t.slice(6),l="/_matrix/media/v1/download/",c={};n&&(c.width=n),i&&(c.height=i),o&&(c.method=o),r.keys(c).length>0&&(l="/_matrix/media/v1/thumbnail/");var u=s.indexOf("#"),d="";return u>=0&&(d=s.substr(u),s=s.substr(0,u)),e+l+s+(0===r.keys(c).length?"":"?"+r.encodeParams(c))+d},getIdenticonUri:function(e,t,n,i){if(!t)return null;n||(n=96),i||(i=96);var o={width:n,height:i},a=r.encodeUri("/_matrix/media/v1/identicon/$ident",{$ident:t});return e+a+(0===r.keys(o).length?"":"?"+r.encodeParams(o))}}},function(e,t,n){(function(t){"use strict";var r=n(56),i=n(11);e.exports.PREFIX_V1="/_matrix/client/api/v1",e.exports.PREFIX_V2_ALPHA="/_matrix/client/v2_alpha",e.exports.PREFIX_IDENTITY_V1="/_matrix/identity/api/v1",e.exports.MatrixHttpApi=function(e){i.checkObjectHasKeys(e,["baseUrl","request","prefix"]),e.onlyData=e.onlyData||!1,this.opts=e,this.uploads=[]},e.exports.MatrixHttpApi.prototype={getContentUri:function(){var e={access_token:this.opts.accessToken};return{base:this.opts.baseUrl,path:"/_matrix/media/v1/upload",params:e}},uploadContent:function(e,n){if(void 0!==n&&!i.isFunction(n))throw Error("Expected callback to be a function but got "+typeof n);var a=r.defer(),s=this.opts.baseUrl+"/_matrix/media/v1/upload",l={loaded:0,total:0};if(t.XMLHttpRequest){var c=new t.XMLHttpRequest;l.xhr=c;var u=o(a,n,this.opts.onlyData),d=function(){c.abort(),u(new Error("Timeout"))};c.timeout_timer=setTimeout(d,3e4),c.onreadystatechange=function(){switch(c.readyState){case t.XMLHttpRequest.DONE:clearTimeout(c.timeout_timer);var e;if(!c.responseText)return e=new Error("No response body."),e.http_status=c.status,void u(e);var n=JSON.parse(c.responseText);if(void 0===n.content_uri)return e=Error("Bad response"),e.http_status=c.status,void u(e);u(void 0,c,n.content_uri)}},c.upload.addEventListener("progress",function(e){clearTimeout(c.timeout_timer),l.loaded=e.loaded,l.total=e.total,c.timeout_timer=setTimeout(d,3e4),a.notify(e)}),s+="?access_token="+encodeURIComponent(this.opts.accessToken),s+="&filename="+encodeURIComponent(e.name),c.open("POST",s),e.type?c.setRequestHeader("Content-Type",e.type):c.setRequestHeader("Content-Type","application/octet-stream"),c.send(e)}else{var p={filename:e.name,access_token:this.opts.accessToken};l.request=this.opts.request({uri:s,qs:p,method:"POST"},o(a,n,this.opts.onlyData)),e.stream.pipe(this.opts.request)}this.uploads.push(l);var m=this;return l.promise=a.promise"finally"{for(var e=Object.keys(m.uploads),t=0;t<e.length;++t)m.uploads[e[t]].promise===a.promise&&m.uploads.splice(e[t],1)}),l.promise},cancelUpload:function(e){for(var t=Object.keys(this.uploads),n=0;n<t.length;++n){var r=this.uploads[t[n]];if(r.promise===e){if(void 0!==r.xhr)return r.xhr.abort(),!0;if(void 0!==r.request)return r.request.abort(),!0}}return!1},getCurrentUploads:function(){return this.uploads},idServerRequest:function(e,t,n,a,s){var l=this.opts.idBaseUrl+s+n;if(void 0!==e&&!i.isFunction(e))throw Error("Expected callback to be a function but got "+typeof e);var c={uri:l,method:t,withCredentials:!1,json:!1,_matrix_opts:this.opts};"GET"==t?c.qs=a:c.form=a;var u=r.defer();return this.opts.request(c,o(u,e,this.opts.onlyData)),u.promise},authedRequest:function(e,t,n,r,i,o){return r||(r={}),r.access_token=this.opts.accessToken,this.request(e,t,n,r,i,o)},request:function(e,t,n,r,i,o){return this.requestWithPrefix(e,t,n,r,i,this.opts.prefix,o)},authedRequestWithPrefix:function(e,t,n,r,i,o,a){var s=this.opts.baseUrl+o+n;return r||(r={}),r.access_token=this.opts.accessToken,this._request(e,t,s,r,i,a)},requestWithPrefix:function(e,t,n,r,i,o,a){var s=this.opts.baseUrl+o+n;return r||(r={}),this._request(e,t,s,r,i,a)},getUrl:function(e,t,n){var r="";return t&&(r="?"+i.encodeParams(t)),this.opts.baseUrl+n+e+r},_request:function(t,n,a,s,l,c){if(void 0!==t&&!i.isFunction(t))throw Error("Expected callback to be a function but got "+typeof t);var u=this;if(s||(s={}),this.opts.extraParams)for(var d in this.opts.extraParams)this.opts.extraParams.hasOwnProperty(d)&&(s[d]=this.opts.extraParams[d]);var p,m=r.defer(),h=!1;c&&(p=setTimeout(function(){h=!0,m.reject(new e.exports.MatrixError({error:"Locally timed out waiting for a response",errcode:"ORG.MATRIX.JSSDK_TIMEOUT",timeout:c}))},c));try{this.opts.request({uri:a,method:n,withCredentials:!1,qs:s,body:l,json:!0,_matrix_opts:this.opts},function(e,n,r){if(!c||(clearTimeout(p),!h)){var i=o(m,t,u.opts.onlyData);i(e,n,r)}})}catch(f){m.reject(f),t&&t(f)}return m.promise}};var o=function(t,n,r){return n=n||function(){},function(i,o,a){if(!i&&o.statusCode>=400&&(i=new e.exports.MatrixError(a),i.httpStatus=o.statusCode),i)t.reject(i),n(i);else{var s={code:o.statusCode,headers:o.headers,data:a};t.resolve(r?a:s),n(null,r?a:s)}}};e.exports.MatrixError=function(e){this.errcode=e.errcode,this.name=e.errcode||"Unknown error code",this.message=e.error||"Unknown message",this.data=e},e.exports.MatrixError.prototype=Object.create(Error.prototype),e.exports.MatrixError.prototype.constructor=e.exports.MatrixError}).call(t,function(){return this}())},function(e,t,n){(function(t,n){

**Comment by ara4n** [comment]
@AmandineLP we can't repro this - can you check whether it's a caching problem?

**Comment by AmandineLP** [comment]
Can't repro after clearing the cache... Guess it is a caching problem
