### ISSUE TITLE
Inviting users should warn you if you're going to share history.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#60]

**Comment by Kegsay** [comment]
Is this still valid given you can't hide/show previous events in the room?

**Comment by ara4n** [comment]
it isn't. it should just warn you when you're about to share history, but not give you the option to try to change it.

**Comment by ara4n** [comment]
we're actually supporting sharing (and not sharing) history in the end (just not doing it retrospectively).  Let's warn once per session per room to avoid irritating users when inviting multiple people.
