### ISSUE TITLE
Implement the new design for the menu in LHS panel

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#601]
Haven't found a bug/feature for this. Please close if duplicate.
Probably missing the design, but I would expect the same chevron as for other categories

**Comment by AmandineLP** [comment]
See https://basecamp.com/1813112/projects/9700343/messages/52988927

**Comment by AmandineLP** [comment]
New design:
![image](https://cloud.githubusercontent.com/assets/8582858/12447660/97e07662-bf71-11e5-85ab-2aa244a01832.png)

**Comment by ara4n** [comment]
i did this.
