### ISSUE TITLE
What is the flow when you invite someone with the 'wrong' email address?

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#619]
A very common flow is that I try to invite amandine@matrix.org to a room, but it happens that she's signed up as amandine@vector.im.  How does this flow actually work out?  Do we need to manage multiple email address mappings in Global settings (as we did in Angular)?

**Comment by Kegsay** [comment]
Closed https://github.com/vector-im/vector-web/issues/529 as a result (dupe)

**Comment by ara4n** [comment]
Dave: now that you added 3PID editing support, please can you ensure that clicking on an invite email drops you into User Settings, populating up the 3PID editing UI with the email address in question to encourage you to link it to your existing account (if you're already signed in)?

**Comment by ara4n** [comment]
closing as a dup of #924
