### ISSUE TITLE
Allow autocomplete to add users

### ISSUE THREAD

**Issue by rtanalytics** [vector-im/vector-web#631]
It would be great to instantly show users that match search condition when adding users in "create new room" or in member list

**Comment by ara4n** [comment]
@kegsay was writing this yesterday :)

**Comment by Kegsay** [comment]
Yup. You might even see it land today (!)

**Comment by rtanalytics** [comment]
Wow, that's just amazing!

**Comment by Kegsay** [comment]
See #509 for the main issue. Closing this one.
