### ISSUE TITLE
tab completion for names using the right UX

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#64]
They should bring up the contextual menu thing at least.

**Comment by dbkr** [comment]
afaik this is implemented? Nicknames tab complete.

**Comment by ara4n** [comment]
not using the designed UI/UX tho

**Comment by ara4n** [comment]
as the comment said, it needs to show a contextual popup.

**Comment by ara4n** [comment]
We should order the list by most recently seen, too.
