### ISSUE TITLE
NPEs after going dir->room->dir again on xeserv.us

### ISSUE THREAD

**Issue by Xe** [vector-im/vector-web#661]
I click and click but nothing happens. Sample instance live at https://xeserv.us.

**Comment by Xe** [comment]
![](http://puu.sh/mzLtw/d320385d72.png)

**Comment by Kegsay** [comment]
Can you click the bundle line number and tell me the context around this please?

**Comment by Kegsay** [comment]
Alternatively if that is live I can actually do this myself <_< never mind!

**Comment by Kegsay** [comment]
Can't repro on https://xeserv.us as a guest - can you please stack trace me :)

**Comment by Xe** [comment]
Join one of the two channels and try to go back to the directory

**Comment by ara4n** [comment]
xeserv.us seems down atm - @Xe, please update to latest develop (which has moved on a lot in the last few days) and if you see any more null pointers please click through and c+p the source in question into here?  thanks!

**Comment by ara4n** [comment]
@Xe can you still repro this?

**Comment by ara4n** [comment]
i'm sure this would have come up in the last 8 months if it was still a bug.
