### ISSUE TITLE
Block browsers other than Chrome/Safari/Firefox/Opera etc

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#67]

**Comment by Kegsay** [comment]
Not allowing Edge?

**Comment by Kegsay** [comment]
Done in #283

**Comment by markwooff** [comment]
I know this issue is closed but just curious as to why Edge wasn't included in the allowed browsers? Assuming WebRTC is the breaking point when using IE, Edge does support it.

**Comment by Kegsay** [comment]
We don't block based on the browser. Check the PR.
