### ISSUE TITLE
Remove/delete room

### ISSUE THREAD

**Issue by floviolleau** [vector-im/vector-web#722]
It'd be nice to be able to delete/remove a room from the vector interface.

Here my case:
- I created a public room for testing
- I want to remove in order to not show it in the directory because it was a testing one

I tried to use the api directory but with no luck (https://matrix.org/docs/howtos/client-server.html#login and https://matrix.org/docs/api/client-server/#/).

**Comment by ara4n** [comment]
dup #906

**Comment by MurzNN** [comment]
Why this is dup of #906? #906 is about removing room aliases, but this is for total remove of whole group. #906 is already closed, does now we can remove room? I can't find the way to do this in Riot.

**Comment by saintger** [comment]
Perhaps with this script:
https://github.com/matrix-org/synapse/blob/master/scripts-dev/nuke-room-from-db.sh

**Comment by rgpublic** [comment]
Sigh. I've created an encrypted room. Now we found out, that encryption doesnt work with search yet. So we cannot use encryption. You cannot unencrypt the room, you cannot delete the room. Now, I've adapted the saintger's script to be a bit more usable (you don't need to become postgres user and you don't need to pipe into psql manually). Perhaps this is helful for others:

https://gist.github.com/rgpublic/0b7c44afafae71a8cc44732a5c217936

Make sure that you log out and log in in Riot afterwards to really make the room disappear.

**Comment by rgpublic** [comment]
PS:  I found that after applying the script, the room still shows up in the community room overview page. So, I added "group_rooms" to the script. Additionally, while searching for this issue, I found that the room-ID also shows up in "user_directory". Perhaps it's advisable to add to the script as well.

**Comment by karl007** [comment]
For everyone who search for a secure solution to delete a room (or something nearby), I create a php script as replacement for the `nuke-room-from-db` script, but use the API to kick all users and then let the garbage collector remove the empty room instead of deleting membership in the DB (and maybe miss something or screw up the DB): https://gist.github.com/rgpublic/0b7c44afafae71a8cc44732a5c217936

```bash
php riot_delete_room.php https://matrix.org "MDA...kYK" "#alias:domain.de"
```
The script only shows all members and the stop and ask if the members should kick. Then ask for a reason and a possible userId which should not kicked.

**Comment by LinuxOnTheDesktop** [comment]
Sorry, but what is the "MDA...kYK" and what is the "#alias:domain.de"? Which of those fields is the name of the room-to-be-deleted?

**Comment by karl007** [comment]
A look into the script or the execution without arguments had answered this question for  you:
```
USAGE: riot_delete_room.php <URL> <TOKEN> <ROOM ALIAS|ID>
```

**Comment by LinuxOnTheDesktop** [comment]
@ karl007: well OK, but I know little about Matrix or Riot - and that will be true of many people who are testing out 'rooms'. I think it is unbelievable that there is no official deletion method. Also: I hesitate to run the script in case it somehow breaks things.

**Comment by t3chguy** [comment]
Its like in e-mail, you can't force everyone to delete their copy. You can delete your copy by leaving the room. The person who starts an e-mail chain doesn't magically gain the ability to delete copies from other servers

**Comment by LinuxOnTheDesktop** [comment]
t3chguy: thank you. By 'leaving', you mean leaving permanently - not just closing the application/browser tab. (The application has chosen some poor terminology.)

Nor do I fully understand. Does the 'room' (unlike an e-mail, at least if that e-mail is not stored in the cloud) not have some existence independently of its members - some existence as something that one can enter into? Presuming that that is the case: can't such entering be prevented, even if people have their own copies (/transcripts?) of the room?

These complications go down badly with someone who merely and quickly wishes to setup a secure environment in which she or he can communication with some others.

The fact that I have _paid_ for this facility worsens matters; I have been in contact with 'Vector' support but I am waiting to hear back (and, unfortunately, I am in a hurry.

**Comment by t3chguy** [comment]
By leaving I mean choosing the "Leave room" option.
![image](https://user-images.githubusercontent.com/2403652/79701411-d182c380-8294-11ea-87e9-88520df6152d.png)

A room, if it becomes empty, becomes entirely inaccessible as there are 0 servers in the decentralized room to bootstrap a join into it.

**Comment by LinuxOnTheDesktop** [comment]
'By leaving I mean choosing the "Leave room" option': I know. I meant to convey that I knew. My points were that (1) I had to think about and that, for that reason (2) the terminology is confusing. :)

'A room, if it becomes empty, becomes entirely inaccessible'. Ah. OK. Still: that means that I can be in a room when . . I am not in it, i.e. when I am not visiting it. If I have that right, then that is pretty confusing too!

**Comment by xpseudonym** [comment]
Is this conceptually a dup of https://github.com/vector-im/riot-web/issues/2299
?

**Comment by ssaavedra** [comment]
I just found out that when removing a room by "Leaving room" and being the only user, if the room was part of a community, it seems that the community can no longer function properly, since it cannot find the room metadata anymore, but it doesn't seem to get properly deleted.

**Comment by anoadragon453** [comment]
> I just found out that when removing a room by "Leaving room" and being the only user, if the room was part of a community, it seems that the community can no longer function properly, since it cannot find the room metadata anymore, but it doesn't seem to get properly deleted.

This is a Synapse bug and should be fixed by https://github.com/matrix-org/synapse/pull/7465, due to land in the next release cycle.

**Comment by subins2000** [comment]
There should be a "Delete Room" option for admins/owner like the "Leave Room" button.
