### ISSUE TITLE
Guest access / nicknames / zero configuration

### ISSUE THREAD

**Issue by floviolleau** [vector-im/vector-web#724]
It'd be nice to be able to set up a nickname from the vector interface from the login page and do not do an autologin.

Here my case:
- I go to my vector web page
- Instead of seeing the login page with login/pass, I'm autologged as an anonymous user

This is not convenient with authentified users and anonymous users on the same server because when authentified users want to connect themselves, they must do the following thing:
- go to the vector page
- they are autologged as an anonymous user
- go to the settings
- logout
- login

And I think that adding in the login page a case for guest users and force them to fill in a captcha at the same time is a good idea. Isn't it?

**Comment by AmandineLP** [comment]
solved by the top bar
