### ISSUE TITLE
Editing room settings on a room where you have no power can result in 403s even if you don't change anything (other than the colour)

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#742]

**Comment by ara4n** [comment]
I can't repro this; just set my room colour on a random freenode channel fine. Are you sure the error wasn't for something else?  What was the error?

**Comment by AmandineLP** [comment]
Tried to set the colour on #vector:matrix.org (or whatever the alias is) and I got: "Failed to set state: M_FORBIDDEN: You don't have permission to post that to the room. user_level (0) < send_level (50)"

However now it seemed to work anyway.

**Comment by ara4n** [comment]
Reproduced this by trying to change #matrix-fr:matrix.org (where i don't have power) - it tried to set both name & visibility:

```
https://matrix.org/_matrix/client/api/v1/rooms/!OlrhyJPphBXggSaqWk%3Amatrix…e/m.room.name?access_token=Failed to load resource: the server responded with a status of 403 (Forbidden)
2016-01-25 12:07:10.939 https://matrix.org/_matrix/client/api/v1/rooms/!OlrhyJPphBXggSaqWk%3Amatrix…y_visibility/?access_token=Failed to load resource: the server responded with a status of 403 (Forbidden)
```

**Comment by AmandineLP** [comment]
Florent Violleau reproduced it with mute/unmute on HQ
