### ISSUE TITLE
Email for token validation should be explicit that only Chrome and Firefox are supported

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#743]
Hello,
We have received a request from xx.xx.xx.xx to use this email address on vector.im. If this was you who made this request, you may use the following link in Chrome or Firefox to complete the verification of your email address:
Complete email verification
...or copy this link into your web browser (Chrome or Firefox):
https://vector.im/_matrix/identity/api/v1/validate/email/submitToken?t......
If your client requires a code, the code is xxxxxx
If you aren't aware of making such a request, please disregard this email.

**Comment by ara4n** [comment]
I thought I did this mid last week - did it not work?

**Comment by AmandineLP** [comment]
Apparently not given I received an email without the mention Friday 22 at 11pm

**Comment by ara4n** [comment]
i did the invite, not the verification mail. fixed.
