### ISSUE TITLE
Until guests accepts to join a room, he should be peeking

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#760]
Today: clicking on Matrix HQ as a guest I get a "do you want to join message" but I don't see what is happening in the room (how do you want me to decide? :) )

So default state should be "peeking" until the user selects "yes"

**Comment by Kegsay** [comment]
Can't repro this. I suspect this was back when Matrix HQ was "guests can join but can't peek", which I fixed later that day. @AmandineLP - can you repro this now?

**Comment by AmandineLP** [comment]
nope seems to be fixed
Closing the issue
