### ISSUE TITLE
Joining confirmation message for guests

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#761]
Warning message before joining a room should be as follow (or similar), respecting the design (09.4):
"You have requested access to this room.
Would you like to join this room in order to participate in the discussion?

This is a preview of this room. Room interactions, files and other attachments have been disabled."

**Comment by ara4n** [comment]
@AmandineLP is the issue here to refine the wording? I hadn't seen the current preview prompt as a problem...

**Comment by AmandineLP** [comment]
Yes it is and "Join the room." is way to unclear about the consequences and that what is below is a preview and no interaction are allowed. 
We need to tell clearly the user:
- what he's seeing and what he can do
- what is going to happen if he clicks "join"

**Comment by AmandineLP** [comment]
Do you really think that this is clear?
![image](https://cloud.githubusercontent.com/assets/8582858/13054339/b0249008-d409-11e5-91db-e6271a95ab54.png)

**Comment by ara4n** [comment]
it now looks like this:

<img width="795" alt="screen shot 2016-03-17 at 19 19 14" src="https://cloud.githubusercontent.com/assets/1294269/13858139/2ea5e28c-ec75-11e5-9885-61375266a054.png">

@AmandineLP please reopen if that's not good enough.

**Comment by AmandineLP** [comment]
Looks good thanks!
