### ISSUE TITLE
Sometimes the unread bar on the left stays visible even if all messages are read (and the name is not bold)

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#763]
![image](https://cloud.githubusercontent.com/assets/8582858/12552809/36cfe6da-c374-11e5-9b36-f971294e393e.png)

**Comment by ara4n** [comment]
sounds like another variant of #623

**Comment by ara4n** [comment]
@dbkr i haven't seen this for a while - is it fixed?
