### ISSUE TITLE
Room settings should not be fully displayed to non privileged users

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#764]
Only the settings relevant to the user's privileges should be displayed

**Comment by ara4n** [comment]
@AmandineLP are you happy for them to just be greyed out?  Or do we really want to hide the config capabilities from mortal users?

**Comment by AmandineLP** [comment]
greyed out is fine for now but hiding them would be good in the future from a decluttering perspective.

**Comment by AmandineLP** [comment]
non-privileged users includes guests obviously

**Comment by dcampbell24** [comment]
I am planning to work on this over the weekend.

I don't know that we actually want to hide the settings since that would make it harder for the user to know what the current settings are. By "greyed out" I am taking that to mean set the disabled attribute on the widget.

**Comment by ara4n** [comment]
this got fixed.

**Comment by dcampbell24** [comment]
:+1:
