### ISSUE TITLE
Room settings: need a warning when setting a room public without address

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#767]
We really need a way to warn the user who creates a room and unchecks "Make this room pivate" that it won't be visible until he sets an address.
eg a line appearing in the settings under the box he checked saying "This room has no address so it won't be visible in the directory, even if not private".

Even I get confused

**Comment by AmandineLP** [comment]
#1059

**Comment by dbkr** [comment]
I think this is fixed by https://github.com/matrix-org/synapse/pull/664 ?

**Comment by ara4n** [comment]
i also added the warning.
