### ISSUE TITLE
Joining a room which doesn't share history, shares the join/leave state events in history

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#768]
tested with:
Amandine created a room which doesn't share history and doesn't allow preview, but does allow guest access
Guest joins, can't read older messages, but does see older events (join, rename, but not the leaving apparently)

**Comment by ara4n** [comment]
@erikjohnston do we have any hope of hiding these any time soon?

**Comment by erikjohnston** [comment]
I don't seem to be able to reproduce this. What exactly are people seeing? Is this in a new (ish) room and you see the creator's join?

**Comment by ara4n** [comment]
@AmandineLP: need moar info

**Comment by AmandineLP** [comment]
yup newish room. but haven't repro precisely the use case.
Might be confusion over the whole "is the timeline hidden?" info we miss
