### ISSUE TITLE
Push settings are loading forever for guests

### ISSUE THREAD

**Issue by manuroe** [vector-im/vector-web#772]
In guest access, the "Notifications" section in the user's settings pages shows a loading wheel forever.
The /pushrules request returns 403 FORBIDDEN.

Not sure what is wrong: the CS API not supporting /pushrules for guests or the UI displaying such settings for a guest.

**Comment by AmandineLP** [comment]
Surely as a guest I want push notifs on my desktop, so they should be supported and configurable

**Comment by ara4n** [comment]
looks like someone fixed this.
