### ISSUE TITLE
After trying to join a room as a guest via RoomDirectory and getting rejected, i get stuck on a spinner

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#777]
We shouldn't even allow onClick() to fire on RoomDirectory if there is no guest access or peek access.

**Comment by ara4n** [comment]
@richvdh - this looks very close to where you just were?

**Comment by richvdh** [comment]
Close, but different.

However, we no longer appear to get stuck on a spinner. We see a preview bar, with a "join" link; clicking on that results in "This room is private or inaccessible to guests. You may be able to join if you register." (I think this was improved in matrix-org/matrix-react-sdk#243).

There's still an argument that we shouldn't even let the user get that far - there is no point switching to the roomview if we know the join/peek is going to fail, but I think it makes this more a cosmetic bug.

@ara4n: wdyt?

**Comment by ara4n** [comment]
agreed - let's just fire an errordialog from RoomDirectory if the user tries to click into a room they can't join or peek.

**Comment by ara4n** [comment]
fixed by b431de8
