### ISSUE TITLE
Need a prompt on vector.im so that people can login or access as guests

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#778]
My take would be: 
Display the directory with a popup with a text input and 2 buttons: 

Set a display name to continue as guest or login
[Text input field pre-populated with a default editable human readable guest name]
[Log in]   [Continue as guest]

Clicking on "log in" redirects to the login screen as we have it today.

I like the idea of showing the directory as it feels more "ready to use". I considered a popup allowing you to login or just set a guest name, but I think it would make it too complex and scary.

**Comment by AmandineLP** [comment]
Actually people should be able to ** login / register** or access as guest, otherwise every new user will have guest usernames

**Comment by dbkr** [comment]
Not sure if you're in favour or against the idea of a popup from reading the description. If so, a modal dialog that blocks the rest of the app or something less intrusive? How would this interact with the guest warning bar?

**Comment by AmandineLP** [comment]
Agreed behavior:
accessing vector.im drops me in the directory as a guest. When wanting to join a room, a popup asks me to set a display name.

this is irrelevant now
