### ISSUE TITLE
Inexplicable 20-30s hangs after joining Matrix HQ as a guest

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#779]
Generally flakey behaviour with potential crashes, freezes, lag etc...

**Comment by ara4n** [comment]
Just repro'd this - Chrome entirely wedged for about 30s after joining HQ as a guest.  I tried to profile it, but the profiler was starved out and couldn't see anything.  The only thing in the JS console is:

`Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError`
