### ISSUE TITLE
Guests should be able to see presence info

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#780]
Only peekers don't have presence

**Comment by illicitonion** [comment]
Currently peeking guests can see but not provide presence. There are tests which show that this works. If that's not the case, let me know if you can reproduce.

I don't know anything about non-peeking guests. @NegativeMjark hopefully does.

For setting presence, we consciously decided not to do this. Can you talk through why the change?

**Comment by AmandineLP** [comment]
Peeking guests don't see presence. I don't know what is the ordering of the member list they see:
![image](https://cloud.githubusercontent.com/assets/8582858/12579380/d01439c8-c427-11e5-9c63-a517bf2ea2ca.png)
We maybe should open a different issue for this then.

I'm failing to remember any discussion where we decided that joined guests shouldn't be setting presence, so either I'm confused (highly possible) or I wasn't part of it. But when using it, it seems normal that guests who joined should behave like any other user, given they are real users, just not registered

**Comment by illicitonion** [comment]
I believe the concern was about guests generating a huge number of events, and spamming the system, both slowing synapse down and leading to a lot of federation traffic.

I'll nudge @Kegsay at the peeking users not seeing presence bug, as I believe it's client-side.

**Comment by ara4n** [comment]
bumping prio as the inability to see presence is ugly for guests.
