### ISSUE TITLE
Upgrading guest to registered user doesn't allow me to update my user name

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#781]
User name is greyed out in the registering form. 
I understand that technically it might be hard to upgrade a username, and this will be less useful when guests will have the opportunity to choose a username, but if they don't select one it would be good to allow them to replace it so that they're not stuck forever with @guest78468:matrix.org....

**Comment by dbkr** [comment]
I'm not sure what's desired here. The option to instead register a completely new account with a different username? What do you mean by, "if they don't select one"?

**Comment by AmandineLP** [comment]
Final behaviour should be:
1. When accessing as a guest I get prompted to set a display/user name pre-populated with a sensible default one e.g. @guest564:matrix.org (see #778 and #758)
2. When the guest decides to register, he should be able to override his user name, because if he didn't set one on step 1 and kept @guest564:matrix.org he will be stuck with it forever, which is not nice.

Clearer? Sorry for mangling it earlier.

**Comment by Kegsay** [comment]
We do not allow usernames to change. This is technically extremely hard (portable accounts). If the guest were to change their username when upgrading, they will lose all of the rooms they had joined as a guest, including scrollback. This is why we want to upgrade accounts with the same user id, and why it is greyed out in the UI.

**Comment by AmandineLP** [comment]
ok that's what I suspected
Then let's make sure we prompt guests when they first access to have them set a display name (#778, #758) and possibly to use it to create a sensible default username: is it doable? (#759)

**Comment by AmandineLP** [comment]
Others issues are trackign the problem and more relevant. closing this to remove the noise.
