### ISSUE TITLE
I managed to add to my profile an email I already used for upgrading a guest

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#782]
and it looks like it invited myself into a room... But that said I had an ongoing 1:1 chat with said guest which might explain the 1:1 with myself

**Comment by AmandineLP** [comment]
and when trying to login using it it was linked to my Amandine account (rather than guest): it required the password for this account to work.

Trying to login as the upgraded guest with its matrix ID failed with a 500 error

**Comment by dbkr** [comment]
This is correct: you can add the same email address to multiple matrix accounts, but the most recent one you added it to is the one that gets looked up when you invite by email, etc.
