### ISSUE TITLE
Would be nice to have the blur around the room settings panel as designed as it's really confusing otherwise

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#783]

**Comment by ara4n** [comment]
i hadn't noticed a blur - is this meant to be hiding the background contents of the screen? if so, this seems a bit of a shame as right now you can keep chatting whilst messing in settings (e.g. asking how to use settings...)

**Comment by AmandineLP** [comment]
The problem is that without it the limits of the settings pane are not clear enough and it's very confusing to me. Plus I still have an ugly scroll bar on Chrome. But agreed it's nice to continue chatting. So a compromise would be maybe a gradient? fully visible at the bottom and more and more blurred when it gets to the settings window?

From the design:
![image](https://cloud.githubusercontent.com/assets/8582858/13072136/d89ba22c-d497-11e5-98c5-8de102a5233a.png)

Current implementation:
![image](https://cloud.githubusercontent.com/assets/8582858/13071981/205865a6-d497-11e5-8c7a-18da622b2a82.png)

**Comment by ara4n** [comment]
ah, so you just want the background faded out. we can do that - i thought you were after a blur

**Comment by AmandineLP** [comment]
sorry for using the wrong terminology

**Comment by ara4n** [comment]
i did this last night.
