### ISSUE TITLE
Email used to register should be listed in the profile

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#786]
I noticed after upgrading a guest. Unsure what happens when registering a normal user (running out of email addresses for testing)

**Comment by ara4n** [comment]
empirically this works these days:

<img width="456" alt="screen shot 2016-03-21 at 00 57 52" src="https://cloud.githubusercontent.com/assets/1294269/13908693/fd90b996-eeff-11e5-8a2b-89ff421eecc8.png">
<img width="431" alt="screen shot 2016-03-21 at 00 56 24" src="https://cloud.githubusercontent.com/assets/1294269/13908694/fd9124da-eeff-11e5-89d6-0dc0afab65f1.png">
