### ISSUE TITLE
Show room name changes (and other state changes) in the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#79]

**Comment by Kegsay** [comment]
Define "other state changes". If I have a room with NEB in it, do you *really* want all of nebs random state changes to appear in Vector? Seems a bit too poweruser to me...

**Comment by ara4n** [comment]
Not every state change, but just the ones users care about: m.room.*

**Comment by ara4n** [comment]
room changes got done (by me) - dup of #266 and #68
