### ISSUE TITLE
Copy pasting the link from token validation email doesn't log the user in

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#791]
Coming from Gillian: 
she first clicked on the first link in the email (knowing that it woudl launch IE and wanting to see how it would fail)
Then after IE failed she went back and c+p'ed the big link in chrome and landed on driectory as a guest, not knowing if she was logged in or not

**Comment by dbkr** [comment]
I can't repro this: visiting the link asks me if I want to join the room. Only thing I've had is that sometimes it briefly displays the room directory before going to the room?

**Comment by AmandineLP** [comment]
Reproduced:
Using a private window in FF I created an account
I c+p'ed the second link into *another* private FF window and I ended up as guest instead of me.

Perhaps it is normal though and technically you need to open the link in the same session you registered?...

**Comment by dbkr** [comment]
Oh, I think I completely misunderstood this bug - Gillian had a pre-existing account?

**Comment by dbkr** [comment]
@AmandineLP Did you close the old firefox private window before opening the other, ie. are they sharing a session or not? I don't think we auto-log in users from invite links at all - we just log them in as guests.

**Comment by AmandineLP** [comment]
No she created a new account
And no I didn't close it because for me each window are private, I didn't know they were sharing the session. And it would feel normal to auto-login people when they click on the link surely? I can't remember how it works

**Comment by dbkr** [comment]
https://github.com/matrix-org/matrix-react-sdk/commit/401d18bcc622d1a77bcb9ff16fc7cc3c2f24ad89
