### ISSUE TITLE
Sometimes setting room name and changing colour fails with "Array.prototype.reduce called on null or undefine"

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#795]
reported by Yuval on new room creation (I created a new room, changed the name and the color and clicked "Saved", got the above message) and reproed by Kegan on a 1:1 nto new

![image](https://cloud.githubusercontent.com/assets/8582858/12594156/eb22b09e-c474-11e5-9213-90c223eda46c.png)

**Comment by Kegsay** [comment]
I repro'd by just changing the colour and hitting Save. I didn't change the room name.
