### ISSUE TITLE
Clicking on member invited by email doesn't open the user profile

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#801]
Emails are truncated in the member list. If I click on the emails I invited nothing happens: it should open the user profile so that I can see the email fully

**Comment by Kegsay** [comment]
We can't do this. The emails are truncated for privacy reasons, so people can't map emails to matrix user IDs. There is/was no guidance on what should be present on the user profile segment for 3PID users either (we don't really have anything else to display, hence why clicking does nothing).

**Comment by AmandineLP** [comment]
Yup that's what I was commenting to myself right now... Still annoying from the person inviting's perspective (have I made a typo?) but not sure there is much we can do.
/me closes the issue
