### ISSUE TITLE
Vector.im/beta  takes > 30s to launch when retrieving an existing session

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#814]
I was using Vector
I close chrome
I reopen it and go to vector.im= > have to wait 35s before getting something other than the loading wheel

**Comment by dbkr** [comment]
Dave (@dave:matrix.org)
Amandine: could you try https://github.com/vector-im/vector-web/issues/814 with latest /develop and see if it's any better?
@Amandine:matrix.org
ok
I assume that if I have no banner saying there is a new version I4m on latest develop?
* Amandine refreshes
@dave:matrix.org
@Amandine:matrix.org
Amandine
looks better
* Amandine tries other use cases
@Amandine:matrix.org
I love it dave :)
almost instant at login (2-3s) and 8s at refresh


Saying this can be closed for now then.
