### ISSUE TITLE
Saving room settings tries to set unchanged settings.

### ISSUE THREAD

**Issue by erikjohnston** [vector-im/vector-web#815]
In particular, when trying to change notification settings it attempts to set `m.room.history_visibility` in `#freenode_#ipfs:matrix.org` (`!yhqiEdqNjyPbxtUjzm:matrix.org`) to `invited`.

I did not click on anything except the "Mute notifications for this room" checkbox.

![screenshot from 2016-01-29 11 25 30](https://cloud.githubusercontent.com/assets/8428120/12674451/0527e704-c67b-11e5-85a0-0399a27fb7d6.png)

`m.room.history_visibility` is not set.

**Comment by AmandineLP** [comment]
linked to #742 ?
