### ISSUE TITLE
RoomDirectory is worryingly slow to load

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#820]

**Comment by AmandineLP** [comment]
including for registered users

**Comment by Kegsay** [comment]
This will be a combination of the HTTP hit taking forevar (*shirley* easy to cache server-side) and the component rendering hundreds of rows: `TruncatedList` to the rescue!

**Comment by AmandineLP** [comment]
it's much faster today: has this been fixed?
vector-27791c06ee27-react-bd73c4e0ccb2-js-977e33f1bd5c

**Comment by ara4n** [comment]
it's much faster for me now too. closing for now.
