### ISSUE TITLE
A leaving event in HQ brought the black unread bar but didn't bold the room name

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#828]

**Comment by dbkr** [comment]
Does this still happen? Member events should no longer generate notifications (ie. the black bar): it doesn't for me.

**Comment by AmandineLP** [comment]
gah I missed the comment.

Yes it does still happen

**Comment by dbkr** [comment]
Think the bug here is that there's a room rule set to notify for these rooms, so that's catching member events where it shouldn't be.

**Comment by dbkr** [comment]
Will require synapse redeploy.
