### ISSUE TITLE
No way to cancel a inbound invite, short of accepting it and immediately leaving the room

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#84]
General Matrix bug, duplicated here for completeness

**Comment by dbkr** [comment]
https://matrix.org/jira/browse/SPEC-215

**Comment by Kegsay** [comment]
So this is "implemented" in the JS SDK because you just leave the room. Removing label.

**Comment by Kegsay** [comment]
Removing `blocked` since it will be in the next Synapse release.

**Comment by Kegsay** [comment]
Done in https://github.com/vector-im/vector-web/pull/298
