### ISSUE TITLE
After closing Chrome I need to login again when hitting vector.im again

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#840]
And Erik swore to me I shouldn't :(

**Comment by ara4n** [comment]
i agree with erik.

**Comment by ara4n** [comment]
Can you grab me tomorrow at some point please and let me RDP in to your box to see what the hell is happening?

**Comment by ara4n** [comment]
This is because Amandine had enabled "clear local sessions when quitting brower" in settings://chrome/content.
