### ISSUE TITLE
1:1 invites still don't show metadata

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#847]
This is missing displayname and avatar.

<img width="2032" alt="screen shot 2016-02-02 at 18 08 52" src="https://cloud.githubusercontent.com/assets/1294269/12759313/43fd5e9a-c9d8-11e5-8142-f1697d3456f5.png">

**Comment by Kegsay** [comment]
I spy with my little eye an avatar url hit 503ing.

**Comment by ara4n** [comment]
that was ~20 mins before i received the invite, which was from displayname bupkes, whose avatar I'd already cached.

**Comment by ara4n** [comment]
the problem is that synapse is simply not sending us the metadata in the invite, still :(

**Comment by dbkr** [comment]
I think what's going on here is that synapse sends us a m.room.name and m.room.avatar state events if the room has them, which by default 1:1 invites do not. Expected behaviour (if no specific avatar/ name) is to show the avatar and display name of the other person, right?

**Comment by ara4n** [comment]
right. yes. indeed. doh. so let's just specialcase it to go and synthesise a name & avatar if the invite doesn't have explicit ones.

**Comment by dbkr** [comment]
Fixed by
https://github.com/matrix-org/matrix-js-sdk/pull/89 and
https://github.com/matrix-org/synapse/pull/607
