### ISSUE TITLE
3PID invites to private rooms do not let unbound 3PIDs actually join the room as guests (or using a preferred account)

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#852]
I can't test it as my 3PID invites are totally broken (issue #848), but if I create a private room and invite an unbound email address to it, can they actually follow the link in that email to launch as guest and actually enter the room (without having to sign up)?

**Comment by AmandineLP** [comment]
So you're talking specifically about private rooms allowing guest access. Which can be confusing (Rich raised an issue about it).
Private rooms today are invite-only, so when you're invited by email we want you to register to identify yourself. So today you get directly redirected to prepopulated login page.

I think the discussion to be had is more invite-only vs secret room. I think that it makes sense to receive an email to be invited to a secret room and be able to access it as a guest. But whether it makes sense to allow guests in invite-only only room is open to discussion. I would probably answer no.

**Comment by ara4n** [comment]
The answer is a firm no currently, but Dan & I designed a solution at https://docs.google.com/document/d/1nxcF1EKyOuxBXVNhF_CV45JZ9VkaQ34N87GWN8xbjfY/edit which can extend the current 3PID invite semantics to make them effectively a bearer-token process where *whoever* receives the email invite can use it to join a room.

This introduces a risk of guest account proliferation, and a bit of a security hole where anyone who intercepts the invite email can use it to hijack the invite and jump into the room, but we think the onboarding benefits make this worthwhile.

Turning this bug into a tracker for implementing the solution, which really is critical for smooth onboarding of new users.

**Comment by ara4n** [comment]
I'd assign this to @illicitonion if github would let me.

**Comment by ara4n** [comment]
This seems to be working modulo various tidy-up and polishing bugs, so going to close the main one.  Thanks @dbkr and @illicitonion!
