### ISSUE TITLE
trailing slash in homeserver URL breaks login 

### ISSUE THREAD

**Issue by rryan** [vector-im/vector-web#859]
I was trying to login to my homeserver and was pretty confused by the error messages I was getting when I accidentally included a trailing slash (this is a habit of mine since it's not a valid URL without a trailing slash):

Homeserver "https://example.com:8448" works fine.
Homeserver "https://example.com:8448/" fails with:
```
Error: Problem communicating with the given homeserver (M_UNRECOGNIZED)
```

It took me a little while to figure out what was wrong and I went down a few misguided rabbit holes before I noticed the double-slash in the API request made by vector.im. Handling this gracefully would be a nice bit of polish.

Maybe an alternate fix would be to make Synapse handle the double-slash gracefully instead of returning 400.

**Comment by Kegsay** [comment]
This has actually already been fixed, just not pushed to /beta yet. 

https://github.com/matrix-org/matrix-react-sdk/pull/125

**Comment by rryan** [comment]
Cool, thanks!
