### ISSUE TITLE
HTML messages

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#86]

**Comment by dbkr** [comment]
There is no Matrix standard for HTML messages currently, apart from the matrix.org custom one. We would need a standard one (or implement a Vector one but this would be contrary to the whole ethos of Matrix).

**Comment by ara4n** [comment]
Suggest we just use the matrix.org custom one for now

**Comment by dbkr** [comment]
I'd vote fairly strongly that we bite the bullet and get this specified now rather than make the problem worse still.

**Comment by ara4n** [comment]
Okay. Starting point would be whether React gives a nice HTML or CSS 
sanitiser we can use as an 'implementation is the reference' starting 
point.

Failing that, we'll be faffing around specifying a manual whitelist of 
HTML tags and attributes and optionally CSS styles... or using MD or RST 
or whatever as an intermediate representation and needing to render it in 
the client.

**Comment by dbkr** [comment]
https://matrix.org/jira/browse/SPEC-48

**Comment by ara4n** [comment]
given the spec stuff isn't progressing and I want this feature right now, I've implemented the org.matrix one for now in fdfa0cb

**Comment by ara4n** [comment]
(obviously I am *very* happy for the impl to be replaced once https://github.com/matrix-org/matrix-doc/pull/92 is sorted out and lands)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/element-hq/element-web/issues/86#issuecomment-152411113

@ara4n, does this include HTML support in Markdown markup?
