### ISSUE TITLE
Improve suggested display name for users who upgraded from guest (remove "Guest" before user name)

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#887]
Suggested display name for a user which has upgraded from guest when trying to join a room is "Guest `<username>`". Which is not great given they're not guests anymore. It would be nicer to have it as "`<username>`".

Also after a guest registered and logged in, he's dumped on the profile page and the display name field  is empty: can we have it as <username> there too?

**Comment by ara4n** [comment]
fixed ages ago and in matrix-org/matrix-react-sdk@a44ebdd respectively
