### ISSUE TITLE
Switching between two rooms with custom colors flashes the default green

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#896]
vector-27791c06ee27-react-bd73c4e0ccb2-js-977e33f1bd5c

**Comment by richvdh** [comment]
It's possible this was an existing issue which has been exacerbated by slightly slower room changes since the timeline stuff landed.

**Comment by richvdh** [comment]
It goes away in the [rav/roomview_works](https://github.com/matrix-org/matrix-react-sdk/tree/rav/roomview_works) branch, as a side-effect of  matrix-org/matrix-react-sdk#155, so I suggest we wait for that to land.

**Comment by richvdh** [comment]
well, that branch has now landed, and apparently it's still/again broken :(

**Comment by ara4n** [comment]
It seems to be working nicely for me on /develop atm?

**Comment by richvdh** [comment]
indeed. Apparently it's gone away again. If anyone manages to repeat it, tell me how.
