### ISSUE TITLE
Can't remove room aliases I set

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#906]
And it feels strange. Maybe only the same person able to remove aliases (server admins) should be able to set them?

We need to find a better UX, but suggestions welcome as I might be missing some of the tricks.

**Comment by ara4n** [comment]
There are a fleet of synapse bugs asking for the ability to delete room aliases.  Currently you can't at all. The intention is both for server admins and the alias creator to be able to do so - https://matrix.org/jira/browse/SYN-83 and friends (open since Sept 14 :( ).  Erik has the con.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/614

**Comment by erikjohnston** [comment]
The ability to delete your own aliases is now on develop.
