### ISSUE TITLE
Searching for a user to invite and then deleting the search term breaks layout on OSX Chrome

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#917]
It causes the MemberList to jump down the page until it's entirely off the screen.

**Comment by Kegsay** [comment]
This is VERY ANNOYING OH MY WORD. It's like the UI is teasing you. You can't select a member in the room you've searched for.

**Comment by ara4n** [comment]
glad you repro'd it ;)

**Comment by ara4n** [comment]
i think this is a regression in Chrome 48 related to flexbox voodoo - the reason Kegan won't have been able to reproduce it in the office is that he'd be stuck on his ancient non-autoupdating desktop linux Chrome

**Comment by ara4n** [comment]
fixed.
