### ISSUE TITLE
Invited users don't have correct metadata in memberlist immediately after inviting

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#918]
Should have the right displayname and avatar :(

<img width="259" alt="screen shot 2016-02-12 at 16 31 35" src="https://cloud.githubusercontent.com/assets/1294269/13013136/1534fcaa-d1a6-11e5-889c-80b695d3c767.png">

**Comment by ara4n** [comment]
It looks like the server just doesn't tell me the necessary profile data:

    "join": {
      "!SRCmDDSXJBsjdRoLMp:matrix.org": {
        "unread_notifications": {},
        "timeline": {
          "limited": false,
          "prev_batch": "s13742686_28990_26122_687945_4062",
          "events": [
            {
              "origin_server_ts": 1455754222148,
              "sender": "@matthew:matrix.org",
              "event_id": "$145575422237057KrfdH:matrix.org",
              "unsigned": {
                "age": 83,
                "invite_room_state": [
                  {
                    "content": {
                      "join_rule": "invite"
                    },
                    "type": "m.room.join_rules",
                    "sender": "@matthew:matrix.org",
                    "state_key": ""
                  }
                ]
              },
              "state_key": "@Amandine:matrix.org",
              "content": {
                "membership": "invite"
              },
              "type": "m.room.member"
            }
          ]
        },

@erikjohnston - where am I meant to get it from in your brave new presence world?

**Comment by erikjohnston** [comment]
We shouldn't be sending `invite_room_state` for invites to people already in the room, really.

I guess one possibility is to have the invite include the profile information (like joins), which we can do since we already require that invites are signed by the remote server before sending to the rest of the room.

**Comment by erikjohnston** [comment]
> I guess one possibility is to have the invite include the profile information (like joins)...

Looking at the code/federation protocol this would be non trivial to do.

**Comment by erikjohnston** [comment]
https://github.com/matrix-org/synapse/pull/624

**Comment by erikjohnston** [comment]
Synapse will now return profile information in invites as per joins.

**Comment by ara4n** [comment]
works beautifully - thanks @erikjohnston !
