### ISSUE TITLE
Message sending breaks when joining a room after peeking

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#937]
Testing guest access to a public guess-accessible room against my local synapse whilst flying back from tel aviv and it broke horribly: on joining the room, the first message got echoed and then none other at all (not even a local echo?!).  On refreshing vector, i got echos, but the most recent message was always stuck in the 'grey' state.

**Comment by ara4n** [comment]
(this against synapse 0.13.3)

**Comment by ara4n** [comment]
@richvdh, given i'm not even seeing a local echo, is it possible this is the JS SDK failing to update the timeline correctly (a bid like #901 ?)

**Comment by ara4n** [comment]
https://matrix.org/_matrix/media/v1/download/matrix.org/LjtRZqYgwKTnerhiKhJxVUav for a screencast of the failure mode i'm seeing.  This is with current synapse head and current vector/react/sdk develop.

**Comment by richvdh** [comment]
(the screencast also shows #943 happening, though that's a separate problem).

**Comment by richvdh** [comment]
for the record, it's not limited to guest access, though that is the more likely repro path.

**Comment by richvdh** [comment]
hopefully fixed by https://github.com/matrix-org/matrix-js-sdk/issues/81
