### ISSUE TITLE
Scroll-to-token is causing my browser to jump around erratically when the window is relatively small

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#946]
I assume something in the layout or wrapping logic is causing the scroll-to-token stuff to break badly - at seemingly random points the window scroll offset jumps up half a page - e.g. when alt-tabbing away and back again, or when someone speaks in the room, or when you speak, etc.  It's screwing up a demo i'm trying to record, so going to temporarily kill it on develop just so I can demo it properly.

https://matrix.org/_matrix/media/v1/download/matrix.org/jrQJJXgvXmnnmYxWRHvosjxZ

**Comment by richvdh** [comment]
oh, arse. sorry, I'll take a look.

**Comment by ara4n** [comment]
This superficially looks like it might be linked to me disabling permenant scrollbars in OSX this morning, which in turn disables gemini, and could be introducing new DOM layout changes which get confused for scroll events by ScrollPanel...

**Comment by richvdh** [comment]
For the record: I was able to reproduce this on Linux by editing `gemini-scrollbar/index.js` to `return 0` early in `getScrollBarWidth()`

**Comment by ara4n** [comment]
looks like 	3c659dc fixed it, thankfully. #947 seems to be intimately connected - something to do with the fact that the text would layout without wrapping with infinite width, and then flexbox would later layout and cause it to wrap down, changing the vertical height and causing a pseudo-scroll event.  Not entirely sure how the `overflow-x: auto` on middle panel fixes it, but it allows the horizontal flexboxing of left/middle/right to not be pushed out enormously by middle.
