### ISSUE TITLE
Guests can get in a state where joining a peeked room never completes

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#949]
1. I created a private test room in FF (logged in to local homeserver as a registered account), with a listed alias
2. I turned on history visibility to be world readable
3. I opened an incognito chrome window as guest and tried to join the alias from the room directory
4. It showed me the room history, but I couldn't join (guests not allowed)
5. I turned on guest access for the room
6. It showed me the room history, but I couldn't join (room is private; need invite)
7. I turned history visibility back to being members-only, just to make things interesting.
8. At this point I noticed that the guest could peek typing notifications for the room, but not history updates, but could see historical peeked history.   => I would expect to not be able to see any peeked contents at all with peeking having been turned off again.
8. I made the room public
9. The guest's attempt to join the room completed with 200 OK, but the guest sits stuck in a spinner in the RoomPreviewBar and can never actually joins the room.  No errors in synapse, which sees the join 200 fine.

**Comment by richvdh** [comment]
So, the problem here is specifically about guests joining rooms whose `history_visibility` is less than `world_readable`. It appears that synapse declines to send you your own `m.room.member` event; meanwhile, vector keeps blocking, pending its arrival.

For some reason this doesn't affect non-guests joining rooms whose `history_visibility` is `joined`. I'll look into this more.

**Comment by richvdh** [comment]
That is actually [specced](https://matrix.org/docs/spec/r0.0.1/client_server.html#id50) behaviour currently: "Servers are required to only return events to guest accounts for rooms where the room state at the event had the m.room.history_visibility state event present with history_visibility value world_readable.".

We now think this is wrong; guests should be treated the same as non-guests for event visibility.

**Comment by ara4n** [comment]
i'm not following why guests would fail to see their own join event - doesn't the join event happen "after" they have joined?

**Comment by richvdh** [comment]
Yes. but they are guests. so they don't get to see anything, as per the above line from the spec.

**Comment by richvdh** [comment]
Now fixed.
