### ISSUE TITLE
We seem to be leaking modal dialog background divs...

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#958]
See bottom of DOM

<img width="1863" alt="screen shot 2016-02-18 at 11 49 30" src="https://cloud.githubusercontent.com/assets/1294269/13142542/be5dc44a-d635-11e5-8f1b-adbec530cd79.png">

**Comment by richvdh** [comment]
Those aren't modal dialogs (the mx_dialog_container one is, but there's only one).

I believe they are part of the gemini-scrollbar implementation, which was fixed in gemini-scrollbar 1.3.2: https://github.com/noeldelgado/gemini-scrollbar/blob/v1.3.2/CHANGELOG.md
