### ISSUE TITLE
Clicking on a link to a room alias in vector.im will get lost by the time you log into vector.

### ISSUE THREAD

**Issue by ara4n** [vector-im/vector-web#96]

**Comment by ara4n** [comment]
We think this should work now.  Leaving it open until we actually finish wiring up 3PID invites...

**Comment by ara4n** [comment]
@kegsay can this be closed now?

**Comment by Kegsay** [comment]
3PID invites are wired up. I have not tested this specific issue.

**Comment by Kegsay** [comment]
Tested and it works fine!
