### ISSUE TITLE
Connectivity lost bar hides latest message from a room

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/vector-web#986]
I switched room during offline connectivity (ie I hadn't seen the last msg yet) and it was hidden by the connectivity bar. Switching back to the room I was in when connectivity was lot, I was seeing the last msg fine there (but I forgot to get back to the other room to see if going back again would fix)
![capture](https://cloud.githubusercontent.com/assets/8582858/13219667/ca4983ea-d971-11e5-8f9f-c7cab1212b5a.PNG)

**Comment by richvdh** [comment]
The behaviour I see is that the last message is covered by the status bar /before/ you switch room. I'm assuming that is what was going on here.

**Comment by richvdh** [comment]
fixed by https://github.com/matrix-org/matrix-react-sdk/pull/169
